/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaGUI;

import controlador.ManejadorJuegos;
import controlador.ManejadorObjetos;
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.CategoriaVideojuegos;
import modelo.Juegos;
import modelo.Marca;

/**
 *
 * @author Daniel
 */
public class MenuJuegosInter extends javax.swing.JFrame {

    /**
     * Creates new form MenuJuegosInter
     */
    ManejadorObjetos manobj;
    ManejadorJuegos manjueg;
    Integer idMarcaTemporal = null;
    String nombreMarcaTemporal = "";
    DefaultTableModel model;
    int indiceFila = 0;
    String[] dato = new String[9];
    public MenuJuegosInter() {
        initComponents();
        manobj = new ManejadorObjetos();
        manjueg = new ManejadorJuegos();
        model = new DefaultTableModel();
        model.addColumn("Id");              
        model.addColumn("Nombre Marca");
        model.addColumn("Nombre");
        model.addColumn("Cantidad");
        model.addColumn("Precio");
        model.addColumn("Género");
        model.addColumn("Restricción edad");
        model.addColumn("Plataforma");
        model.addColumn("Numero Jugadores");
        jTable1.setModel(model);
        model.insertRow(indiceFila, dato);
        inicializarComboBox();
    }

        public void inicializarComboBox(){
        for(int i=0;i<manobj.arregloMarcas.size();i++){
           jComboBoxMarca.addItem(manobj.arregloMarcas.get(i).getDescripcion());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelGenero = new javax.swing.JLabel();
        jLabelRestricciondeEdad = new javax.swing.JLabel();
        jLabelPlataforma = new javax.swing.JLabel();
        jLabelNumeroJugadores = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jComboBoxMarca = new javax.swing.JComboBox<>();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldCantidad = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldUrl = new javax.swing.JTextField();
        jTextFieldGenero = new javax.swing.JTextField();
        jTextFieldRestricciondeEdad = new javax.swing.JTextField();
        jTextFieldPlataforma = new javax.swing.JTextField();
        jTextFieldNumeroJugadores = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelUrl = new javax.swing.JLabel();
        jButtonBorrarUno = new javax.swing.JButton();
        jButtonBorrarTodos = new javax.swing.JButton();
        jButtonInsertar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonConsultarUno = new javax.swing.JButton();
        jButtonConsultarTodo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelMensaje = new javax.swing.JLabel();
        jButtonOrdenarID = new javax.swing.JButton();
        jButtonOrdenarNombreAsc = new javax.swing.JButton();
        jButtonOrdenarPrecioAsc = new javax.swing.JButton();
        jButtonOrdenarNombreDesc = new javax.swing.JButton();
        jButtonOrdenarPrecioDesc = new javax.swing.JButton();

        setTitle("VideoJuegos\n");

        jLabelGenero.setText("Género");

        jLabelRestricciondeEdad.setText("Restricción de Edad");

        jLabelPlataforma.setText("Plataforma");

        jLabelNumeroJugadores.setText("Numero Jugadores");

        jComboBoxMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMarcaItemStateChanged(evt);
            }
        });

        jLabelTitulo.setText("VideoJuegos");

        jLabelId.setText("ID");

        jLabelMarca.setText("Marca");

        jLabelNombre.setText("Nombre");

        jLabelCantidad.setText("Cantidad");

        jLabelPrecio.setText("Precio");

        jLabelUrl.setText("Url");

        jButtonBorrarUno.setText("Borrar Uno");
        jButtonBorrarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarUnoActionPerformed(evt);
            }
        });

        jButtonBorrarTodos.setText("Borrar Todos");
        jButtonBorrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTodosActionPerformed(evt);
            }
        });

        jButtonInsertar.setText("Insertar");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonConsultarUno.setText("Consultar Uno");
        jButtonConsultarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarUnoActionPerformed(evt);
            }
        });

        jButtonConsultarTodo.setText("Consultar Todo");
        jButtonConsultarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarTodoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabelMensaje.setText("Estado");

        jButtonOrdenarID.setText("Ordenar ID");
        jButtonOrdenarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarIDActionPerformed(evt);
            }
        });

        jButtonOrdenarNombreAsc.setText("Ordenar Nombre Ascendente");
        jButtonOrdenarNombreAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNombreAscActionPerformed(evt);
            }
        });

        jButtonOrdenarPrecioAsc.setText("Ordenar Precio Ascendente");
        jButtonOrdenarPrecioAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPrecioAscActionPerformed(evt);
            }
        });

        jButtonOrdenarNombreDesc.setText("Ordenar Nombre Descendente");
        jButtonOrdenarNombreDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNombreDescActionPerformed(evt);
            }
        });

        jButtonOrdenarPrecioDesc.setText("Ordenar Precio Descendente");
        jButtonOrdenarPrecioDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPrecioDescActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelId)
                            .addComponent(jLabelMarca)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelCantidad)
                            .addComponent(jLabelPrecio))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxMarca, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUrl)
                            .addComponent(jLabelGenero)
                            .addComponent(jLabelRestricciondeEdad)
                            .addComponent(jLabelPlataforma)
                            .addComponent(jLabelNumeroJugadores))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldPlataforma, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldRestricciondeEdad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldGenero, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldUrl, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNumeroJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonConsultarUno)
                    .addComponent(jButtonConsultarTodo)
                    .addComponent(jButtonBorrarUno)
                    .addComponent(jButtonBorrarTodos)
                    .addComponent(jButtonInsertar))
                .addGap(26, 26, 26))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonOrdenarNombreDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonOrdenarNombreAsc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonOrdenarPrecioDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonOrdenarPrecioAsc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addComponent(jButtonOrdenarID))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonInsertar)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonModificar)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonConsultarUno)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonConsultarTodo)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonBorrarUno)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBorrarTodos))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMarca)
                            .addComponent(jComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombre)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCantidad)
                            .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrecio)
                            .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUrl)
                            .addComponent(jTextFieldUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGenero)
                            .addComponent(jTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRestricciondeEdad)
                            .addComponent(jTextFieldRestricciondeEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPlataforma)
                            .addComponent(jTextFieldPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNumeroJugadores)
                            .addComponent(jTextFieldNumeroJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonOrdenarPrecioAsc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonOrdenarNombreAsc)
                                .addGap(14, 14, 14)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonOrdenarNombreDesc)
                            .addComponent(jButtonOrdenarPrecioDesc)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonOrdenarID)
                        .addGap(16, 16, 16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarTodoActionPerformed

        manjueg.consultarTodos();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaVideojuegos.arreglojuegos.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getGenero(), indiceFila, 5);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getRestedad(), indiceFila, 6);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getPlataforma(), indiceFila, 7);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getNumjugadores(), indiceFila, 8);
            indiceFila++;
        }
        
    }//GEN-LAST:event_jButtonConsultarTodoActionPerformed

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
       Juegos jueg = new Juegos();
       
       try {
            if (!ValidaEnteros.validaEnteros(jTextFieldId.getText())) {
                throw new ValidaEnteros();
            }
            if (!ValidaCantidad.validaCantidad(jTextFieldCantidad.getText())) {
               throw new ValidaCantidad();
           }
            if (!ValidaFlotantes.validaFlotantes(jTextFieldPrecio.getText())) {
                throw new ValidaFlotantes();
            }
            if (!ValidaNumeroJugadores.validaNumeroJugadores(jTextFieldNumeroJugadores.getText())) {
                throw new ValidaNumeroJugadores();
            }
        } catch (ValidaEnteros e) {
            jLabelMensaje.setText("El id que ingreso no es valido");
            jTextFieldId.setText("");
            return;
        } catch (ValidaCantidad e){
            jLabelMensaje.setText("La cantidad que ingreso no es valida");
            jTextFieldCantidad.setText("");
            return;
        }catch (ValidaFlotantes e){
            jLabelMensaje.setText("El precio que ingreso no es valido");
            jTextFieldPrecio.setText("");
            return;
        }catch (ValidaNumeroJugadores e){
            jLabelMensaje.setText("El numero de jugadores que ingreso no es valido");
            jTextFieldNumeroJugadores.setText("");
            return;
        }
       
       Marca mar = new Marca();
       jueg.setIdArticulo(Integer.parseInt(jTextFieldId.getText()));
       mar.setId(idMarcaTemporal);
       mar.setDescripcion(nombreMarcaTemporal);
       jueg.setMar(mar);
       jueg.setNombre(jTextFieldNombre.getText());
       jueg.setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
       jueg.setPrecio(Float.parseFloat(jTextFieldPrecio.getText()));
       jueg.setGenero(jTextFieldGenero.getText());
       jueg.setRestedad(jTextFieldRestricciondeEdad.getText());
       jueg.setPlataforma(jTextFieldPlataforma.getText());
       jueg.setNumjugadores(Integer.parseInt(jTextFieldNumeroJugadores.getText()));
       
        if (manjueg.insertar(jueg)) {
            jLabelMensaje.setText("El articulo " + jTextFieldNombre.getText() + " se insertó correctamente");
            //JOptionPane.showMessageDialog(this, "El articulo " + jTextFieldNombre.getText() + " se insertó correctamente");
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(jTextFieldId.getText(), indiceFila, 0);
            jTable1.setValueAt(nombreMarcaTemporal, indiceFila, 1);
            jTable1.setValueAt(jTextFieldNombre.getText(), indiceFila, 2);
            jTable1.setValueAt(jTextFieldCantidad.getText(), indiceFila, 3);
            jTable1.setValueAt(Float.parseFloat(jTextFieldPrecio.getText()), indiceFila, 4);
            jTable1.setValueAt(jTextFieldGenero.getText(), indiceFila, 5);
            jTable1.setValueAt(jTextFieldRestricciondeEdad.getText(), indiceFila, 6);
            jTable1.setValueAt(jTextFieldPlataforma.getText(), indiceFila, 7);
            jTable1.setValueAt(Integer.parseInt(jTextFieldNumeroJugadores.getText()), indiceFila, 8);
            indiceFila++;
            manjueg.consultarTodos();
        }
        else{
            jLabelMensaje.setText("Error al insertar");
            //JOptionPane.showMessageDialog(this, "Error al insertar");
        }
        
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed

        int filaSeleccionada = jTable1.getSelectedRow();
            System.out.println(filaSeleccionada);
        
            if (filaSeleccionada >= 0) {
            
            Juegos juegmod = new Juegos();
            int a = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            jTextFieldId.setText(jTable1.getValueAt(filaSeleccionada, 0).toString());
            String nombreMarcaMod = jTable1.getValueAt(filaSeleccionada, 1).toString();
            jTextFieldNombre.setText(jTable1.getValueAt(filaSeleccionada, 2).toString());
            jTextFieldCantidad.setText(jTable1.getValueAt(filaSeleccionada, 3).toString());
            jTextFieldPrecio.setText(jTable1.getValueAt(filaSeleccionada, 4).toString());
            jTextFieldGenero.setText(jTable1.getValueAt(filaSeleccionada, 5).toString());
            jTextFieldRestricciondeEdad.setText(jTable1.getValueAt(filaSeleccionada, 6).toString());
            jTextFieldPlataforma.setText(jTable1.getValueAt(filaSeleccionada, 7).toString());
            jTextFieldNumeroJugadores.setText(jTable1.getValueAt(filaSeleccionada, 8).toString());
            
            Marca marmod = new Marca();
            juegmod.setIdArticulo(Integer.parseInt(jTextFieldId.getText()));
            marmod.setId(a);
            marmod.setDescripcion(nombreMarcaMod);
            juegmod.setMar(marmod);
            juegmod.setNombre(jTextFieldNombre.getText());
            juegmod.setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
            juegmod.setPrecio(Float.parseFloat(jTextFieldPrecio.getText()));
            juegmod.setGenero(jTextFieldGenero.getText());
            juegmod.setRestedad(jTextFieldRestricciondeEdad.getText());
            juegmod.setPlataforma(jTextFieldPlataforma.getText());
            juegmod.setNumjugadores(Integer.parseInt(jTextFieldNumeroJugadores.getText()));
            
            //Marca marmod = new Marca(Integer.parseInt(jTextFieldId.getText()), jTextFieldMarca.getText());
            int posicion = manjueg.busquedaBinaria(a);
                    if (!(posicion==-1)) {
                    if (manjueg.modificar(posicion, juegmod)) {
                        JOptionPane.showMessageDialog(this, "Juego modificado exitosamente");
                        indiceFila--;
                    }
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Error al modificar");
                    }
        }
        
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonConsultarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarUnoActionPerformed

        int idBuscado = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el ID a buscar"));
            
        Juegos resultado = (Juegos) manjueg.consultarId(idBuscado);
        if (resultado == null) {
            JOptionPane.showMessageDialog(this, "Juego no encontrado");
        }
        else{
            JOptionPane.showMessageDialog(this, "El Juego encontrado es:\n" + resultado.toString());
        }
        
    }//GEN-LAST:event_jButtonConsultarUnoActionPerformed

    private void jButtonBorrarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarUnoActionPerformed

        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada >= 0) {
            int idEliminar = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            model.removeRow(filaSeleccionada);
            if (manjueg.borrar(idEliminar)) {
                    JOptionPane.showMessageDialog(this, "Juego borrado exitosamente");    
                    }
            else {
            JOptionPane.showMessageDialog(this, "Error al borrar");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar");
        }
        
    }//GEN-LAST:event_jButtonBorrarUnoActionPerformed

    private void jButtonBorrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTodosActionPerformed

        if (manjueg.borrarTodo()) {
            while (model.getRowCount() > 0) {
                model.removeRow(0);
            }
            indiceFila = 0;
            JOptionPane.showMessageDialog(this, "Todos los Juegos se borraron exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar todo");
        }
        
    }//GEN-LAST:event_jButtonBorrarTodosActionPerformed

    private void jComboBoxMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMarcaItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (jComboBoxMarca.getItemCount() > 0) {
                idMarcaTemporal = ManejadorObjetos.arregloMarcas.get(jComboBoxMarca.getSelectedIndex()).getId();
                nombreMarcaTemporal = ManejadorObjetos.arregloMarcas.get(jComboBoxMarca.getSelectedIndex()).getDescripcion();
            }
        }
        
    }//GEN-LAST:event_jComboBoxMarcaItemStateChanged

    private void jButtonOrdenarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarIDActionPerformed
        manjueg.sort();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaVideojuegos.arreglojuegos.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getGenero(), indiceFila, 5);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getRestedad(), indiceFila, 6);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getPlataforma(), indiceFila, 7);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getNumjugadores(), indiceFila, 8);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarIDActionPerformed

    private void jButtonOrdenarNombreAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNombreAscActionPerformed
        manjueg.ordenarMezcla();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaVideojuegos.arreglojuegos.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getGenero(), indiceFila, 5);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getRestedad(), indiceFila, 6);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getPlataforma(), indiceFila, 7);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getNumjugadores(), indiceFila, 8);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarNombreAscActionPerformed

    private void jButtonOrdenarPrecioAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPrecioAscActionPerformed
        manjueg.quicksort();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaVideojuegos.arreglojuegos.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getGenero(), indiceFila, 5);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getRestedad(), indiceFila, 6);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getPlataforma(), indiceFila, 7);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getNumjugadores(), indiceFila, 8);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarPrecioAscActionPerformed

    private void jButtonOrdenarNombreDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNombreDescActionPerformed
        manjueg.ordenarMezclaDesc();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaVideojuegos.arreglojuegos.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getGenero(), indiceFila, 5);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getRestedad(), indiceFila, 6);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getPlataforma(), indiceFila, 7);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getNumjugadores(), indiceFila, 8);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarNombreDescActionPerformed

    private void jButtonOrdenarPrecioDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPrecioDescActionPerformed
        manjueg.quicksortDesc();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaVideojuegos.arreglojuegos.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getGenero(), indiceFila, 5);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getRestedad(), indiceFila, 6);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getPlataforma(), indiceFila, 7);
            jTable1.setValueAt(CategoriaVideojuegos.arreglojuegos.get(i).getNumjugadores(), indiceFila, 8);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarPrecioDescActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuJuegosInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuJuegosInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuJuegosInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuJuegosInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuJuegosInter().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrarTodos;
    private javax.swing.JButton jButtonBorrarUno;
    private javax.swing.JButton jButtonConsultarTodo;
    private javax.swing.JButton jButtonConsultarUno;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonOrdenarID;
    private javax.swing.JButton jButtonOrdenarNombreAsc;
    private javax.swing.JButton jButtonOrdenarNombreDesc;
    private javax.swing.JButton jButtonOrdenarPrecioAsc;
    private javax.swing.JButton jButtonOrdenarPrecioDesc;
    private javax.swing.JComboBox<String> jComboBoxMarca;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumeroJugadores;
    private javax.swing.JLabel jLabelPlataforma;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelRestricciondeEdad;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUrl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumeroJugadores;
    private javax.swing.JTextField jTextFieldPlataforma;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldRestricciondeEdad;
    private javax.swing.JTextField jTextFieldUrl;
    // End of variables declaration//GEN-END:variables
}
