/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaGUI;

import controlador.ManejadorObjetos;
import controlador.ManejadorRopaDeportiva;
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.CategoriaRopa;
import modelo.Marca;
import modelo.RopaDeportiva;

/**
 *
 * @author danie
 */
public class MenuRopaDeportivaInter extends javax.swing.JFrame {

    /**
     * Creates new form MenuRopaDeportivaInter
     */
    ManejadorObjetos manobj;
    ManejadorRopaDeportiva manrop;
    Integer idMarcaTemporal = null;
    String nombreMarcaTemporal = "";
    DefaultTableModel model;
    int indiceFila = 0;
    String[] dato = new String[9];

    public MenuRopaDeportivaInter() {
        initComponents();
        manobj = new ManejadorObjetos();
        manrop = new ManejadorRopaDeportiva();
        model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Nombre Marca");
        model.addColumn("Nombre");
        model.addColumn("Cantidad");
        model.addColumn("Precio");
        model.addColumn("Color");
        model.addColumn("Tipo");
        model.addColumn("Talla");
        model.addColumn("Usuario");
        jTable1.setModel(model);
        model.insertRow(indiceFila, dato);
        inicializarComboBox();
    }

    public void inicializarComboBox() {
        for (int i = 0; i < manobj.arregloMarcas.size(); i++) {
            jComboBoxMarca.addItem(manobj.arregloMarcas.get(i).getDescripcion());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipo = new javax.swing.ButtonGroup();
        buttonGroupTalla = new javax.swing.ButtonGroup();
        buttonGroupUsuario = new javax.swing.ButtonGroup();
        jLabelNombre = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelColor = new javax.swing.JLabel();
        jTextFieldColor = new javax.swing.JTextField();
        jButtonConsultarUno = new javax.swing.JButton();
        jTextFieldId = new javax.swing.JTextField();
        jButtonConsultarTodo = new javax.swing.JButton();
        jComboBoxMarca = new javax.swing.JComboBox<>();
        jButtonBorrarUno = new javax.swing.JButton();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonBorrarTodos = new javax.swing.JButton();
        jTextFieldCantidad = new javax.swing.JTextField();
        jButtonInsertar = new javax.swing.JButton();
        jTextFieldPrecio = new javax.swing.JTextField();
        jLabelUrl = new javax.swing.JLabel();
        jTextFieldUrl = new javax.swing.JTextField();
        jLabelTipo = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelMensaje = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelTalla = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jButtonModificar = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jComboBoxTalla = new javax.swing.JComboBox<>();
        jComboBoxUsuario = new javax.swing.JComboBox<>();
        jButtonOrdenarNombreAsc = new javax.swing.JButton();
        jButtonOrdenarPrecioAsc = new javax.swing.JButton();
        jButtonOrdenarNombreDesc = new javax.swing.JButton();
        jButtonOrdenarPrecioDesc = new javax.swing.JButton();
        jButtonOrdenarID = new javax.swing.JButton();

        setTitle("Ropa Deportiva");

        jLabelNombre.setText("Nombre");

        jLabelPrecio.setText("Precio");

        jLabelColor.setText("Color");

        jButtonConsultarUno.setText("Consultar Uno");
        jButtonConsultarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarUnoActionPerformed(evt);
            }
        });

        jButtonConsultarTodo.setText("Consultar Todo");
        jButtonConsultarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarTodoActionPerformed(evt);
            }
        });

        jComboBoxMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMarcaItemStateChanged(evt);
            }
        });

        jButtonBorrarUno.setText("Borrar Uno");
        jButtonBorrarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarUnoActionPerformed(evt);
            }
        });

        jButtonBorrarTodos.setText("Borrar Todos");
        jButtonBorrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTodosActionPerformed(evt);
            }
        });

        jButtonInsertar.setText("Insertar");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });

        jLabelUrl.setText("Url");

        jLabelTipo.setText("Tipo");

        jLabelTitulo.setText("Ropa Deportiva");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabelMensaje.setText("Estado");

        jLabelId.setText("ID");

        jLabelTalla.setText("Talla");

        jLabelMarca.setText("Marca");

        jLabelCantidad.setText("Cantidad");

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jLabelUsuario.setText("Usuario");

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pantalon", "Camiseta", "Ropa interior" }));

        jComboBoxTalla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L", "XL", "XXL", "XXXL" }));

        jComboBoxUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Niño", "Niña", "Hombre", "Mujer" }));

        jButtonOrdenarNombreAsc.setText("Ordenar Nombre Ascendente");
        jButtonOrdenarNombreAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNombreAscActionPerformed(evt);
            }
        });

        jButtonOrdenarPrecioAsc.setText("Ordenar Precio Ascendente");
        jButtonOrdenarPrecioAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPrecioAscActionPerformed(evt);
            }
        });

        jButtonOrdenarNombreDesc.setText("Ordenar Nombre Descendente");
        jButtonOrdenarNombreDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNombreDescActionPerformed(evt);
            }
        });

        jButtonOrdenarPrecioDesc.setText("Ordenar Precio Descendente");
        jButtonOrdenarPrecioDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPrecioDescActionPerformed(evt);
            }
        });

        jButtonOrdenarID.setText("Ordenar ID");
        jButtonOrdenarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelId)
                        .addGap(77, 77, 77)
                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jLabelUrl)
                        .addGap(37, 37, 37)
                        .addComponent(jTextFieldUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201)
                        .addComponent(jButtonInsertar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMarca)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelCantidad))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTipo)
                                    .addComponent(jLabelTalla))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelUsuario)
                                .addGap(14, 14, 14)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTalla, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(201, 201, 201)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonModificar)
                            .addComponent(jButtonConsultarUno)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelPrecio)
                        .addGap(59, 59, 59)
                        .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(406, 406, 406)
                        .addComponent(jButtonConsultarTodo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelColor)
                        .addGap(63, 63, 63)
                        .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(406, 406, 406)
                        .addComponent(jButtonBorrarUno))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonOrdenarNombreDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonOrdenarNombreAsc, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonOrdenarPrecioDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonOrdenarPrecioAsc, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jButtonOrdenarID))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(jButtonBorrarTodos)))))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabelTitulo)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInsertar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelId)
                            .addComponent(jLabelUrl))))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelMarca)
                        .addGap(14, 14, 14)
                        .addComponent(jLabelNombre)
                        .addGap(14, 14, 14)
                        .addComponent(jLabelCantidad))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelTipo)
                        .addGap(14, 14, 14)
                        .addComponent(jLabelTalla))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jComboBoxTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUsuario)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButtonModificar)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonConsultarUno)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabelPrecio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonConsultarTodo))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelColor))
                    .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButtonBorrarUno)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonOrdenarNombreAsc)
                            .addComponent(jButtonOrdenarPrecioAsc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonOrdenarNombreDesc)
                            .addComponent(jButtonOrdenarPrecioDesc)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBorrarTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jButtonOrdenarID)
                        .addGap(16, 16, 16)))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarTodoActionPerformed

        manrop.consultarTodos();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaRopa.arregloropadeportiva.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getTalla(), indiceFila, 7);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getTipousuario(), indiceFila, 8);

            indiceFila++;
        }
    }//GEN-LAST:event_jButtonConsultarTodoActionPerformed

    private void jComboBoxMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMarcaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (jComboBoxMarca.getItemCount() > 0) {
                idMarcaTemporal = ManejadorObjetos.arregloMarcas.get(jComboBoxMarca.getSelectedIndex()).getId();
                nombreMarcaTemporal = ManejadorObjetos.arregloMarcas.get(jComboBoxMarca.getSelectedIndex()).getDescripcion();
            }
        }
    }//GEN-LAST:event_jComboBoxMarcaItemStateChanged

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
        RopaDeportiva ropdep = new RopaDeportiva();
        
        try {
            if (!ValidaEnteros.validaEnteros(jTextFieldId.getText())) {
                throw new ValidaEnteros();
            }
        } catch (ValidaEnteros e) {
            jLabelMensaje.setText("El id que ingreso no es valido");
            jTextFieldId.setText("");
            return;
        }
        
        Marca mar = new Marca();
        ropdep.setIdArticulo(Integer.parseInt(jTextFieldId.getText()));
        mar.setId(idMarcaTemporal);
        mar.setDescripcion(nombreMarcaTemporal);
        ropdep.setMar(mar);
        ropdep.setNombre(jTextFieldNombre.getText());
        ropdep.setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
        ropdep.setPrecio(Float.parseFloat(jTextFieldPrecio.getText()));
        ropdep.setColor(jTextFieldColor.getText());
        ropdep.setTipo(jComboBoxTipo.getItemAt(jComboBoxTipo.getSelectedIndex()));
        ropdep.setTalla(jComboBoxTalla.getItemAt(jComboBoxTalla.getSelectedIndex()));
        ropdep.setTipousuario(jComboBoxUsuario.getItemAt(jComboBoxUsuario.getSelectedIndex()));

        if (manrop.insertar(ropdep)) {
            jLabelMensaje.setText("El articulo " + jTextFieldNombre.getText() + " se insertó correctamente");
            //JOptionPane.showMessageDialog(this, "El articulo " + jTextFieldNombre.getText() + " se insertó correctamente");
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(jTextFieldId.getText(), indiceFila, 0);
            jTable1.setValueAt(nombreMarcaTemporal, indiceFila, 1);
            jTable1.setValueAt(jTextFieldNombre.getText(), indiceFila, 2);
            jTable1.setValueAt(jTextFieldCantidad.getText(), indiceFila, 3);
            jTable1.setValueAt(Float.parseFloat(jTextFieldPrecio.getText()), indiceFila, 4);
            jTable1.setValueAt(jTextFieldColor.getText(), indiceFila, 5);
            jTable1.setValueAt(jComboBoxTipo.getItemAt(jComboBoxTipo.getSelectedIndex()), indiceFila, 6);
            jTable1.setValueAt(jComboBoxTalla.getItemAt(jComboBoxTalla.getSelectedIndex()), indiceFila, 7);
            jTable1.setValueAt(jComboBoxUsuario.getItemAt(jComboBoxUsuario.getSelectedIndex()), indiceFila, 8);
            indiceFila++;
            manrop.consultarTodos();
        } else {
            jLabelMensaje.setText("Error al insertar");
            //JOptionPane.showMessageDialog(this, "Error al insertar");
        }
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        System.out.println(filaSeleccionada);

        if (filaSeleccionada >= 0) {

            RopaDeportiva ropdepmod = new RopaDeportiva();
            int a = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            jTextFieldId.setText(jTable1.getValueAt(filaSeleccionada, 0).toString());
            String nombreMarcaMod = jTable1.getValueAt(filaSeleccionada, 1).toString();
            jTextFieldNombre.setText(jTable1.getValueAt(filaSeleccionada, 2).toString());
            jTextFieldCantidad.setText(jTable1.getValueAt(filaSeleccionada, 3).toString());
            jTextFieldPrecio.setText(jTable1.getValueAt(filaSeleccionada, 4).toString());
            jTextFieldColor.setText(jTable1.getValueAt(filaSeleccionada, 5).toString());
            String tipo = (jTable1.getValueAt(filaSeleccionada, 6).toString());
            String talla = (jTable1.getValueAt(filaSeleccionada, 7).toString());
            String usuario = (jTable1.getValueAt(filaSeleccionada, 8).toString());

            Marca marmod = new Marca();
            ropdepmod.setIdArticulo(Integer.parseInt(jTextFieldId.getText()));
            marmod.setId(a);
            marmod.setDescripcion(nombreMarcaMod);
            ropdepmod.setMar(marmod);
            ropdepmod.setNombre(jTextFieldNombre.getText());
            ropdepmod.setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
            ropdepmod.setPrecio(Float.parseFloat(jTextFieldPrecio.getText()));
            ropdepmod.setColor(jTextFieldColor.getText());
            ropdepmod.setTipo(tipo);
            ropdepmod.setTalla(talla);
            ropdepmod.setTipousuario(usuario);

            //Marca marmod = new Marca(Integer.parseInt(jTextFieldId.getText()), jTextFieldMarca.getText());
            int posicion = manrop.busquedaBinaria(a);
            if (!(posicion == -1)) {
                if (manrop.modificar(posicion, ropdepmod)) {
                    JOptionPane.showMessageDialog(this, "La ropa deportiva se ha modificado exitosamente");
                    indiceFila--;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error al modificar");
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonConsultarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarUnoActionPerformed
        int idBuscado = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el ID a buscar"));

        RopaDeportiva resultado = (RopaDeportiva) manrop.consultarId(idBuscado);
        if (resultado == null) {
            JOptionPane.showMessageDialog(this, "Ropa deportiva no encontrada");
        } else {
            JOptionPane.showMessageDialog(this, "La ropa deportiva encontrada es:\n" + resultado.toString());
        }
    }//GEN-LAST:event_jButtonConsultarUnoActionPerformed

    private void jButtonBorrarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarUnoActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada >= 0) {
            int idEliminar = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            model.removeRow(filaSeleccionada);
            if (manrop.borrar(idEliminar)) {
                JOptionPane.showMessageDialog(this, "Ropa deportiva borrada exitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Error al borrar");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar");
        }
    }//GEN-LAST:event_jButtonBorrarUnoActionPerformed

    private void jButtonBorrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTodosActionPerformed
        if (manrop.borrarTodo()) {
            while (model.getRowCount() > 0) {
                model.removeRow(0);
            }
            indiceFila = 0;
            JOptionPane.showMessageDialog(this, "Todos la ropa deportiva se borro exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar todo");
        }
    }//GEN-LAST:event_jButtonBorrarTodosActionPerformed

    private void jButtonOrdenarNombreAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNombreAscActionPerformed
        manrop.ordenarMezcla();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaRopa.arregloropadeportiva.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getTalla(), indiceFila, 7);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getTipousuario(), indiceFila, 8);

            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarNombreAscActionPerformed

    private void jButtonOrdenarPrecioAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPrecioAscActionPerformed
        manrop.quicksort();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaRopa.arregloropadeportiva.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getTalla(), indiceFila, 7);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getTipousuario(), indiceFila, 8);

            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarPrecioAscActionPerformed

    private void jButtonOrdenarNombreDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNombreDescActionPerformed
        manrop.ordenarMezclaDesc();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaRopa.arregloropadeportiva.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getTalla(), indiceFila, 7);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getTipousuario(), indiceFila, 8);

            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarNombreDescActionPerformed

    private void jButtonOrdenarPrecioDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPrecioDescActionPerformed
        manrop.quicksortDesc();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaRopa.arregloropadeportiva.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getTalla(), indiceFila, 7);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getTipousuario(), indiceFila, 8);

            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarPrecioDescActionPerformed

    private void jButtonOrdenarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarIDActionPerformed
        manrop.sort();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaRopa.arregloropadeportiva.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getTalla(), indiceFila, 7);
            jTable1.setValueAt(CategoriaRopa.arregloropadeportiva.get(i).getTipousuario(), indiceFila, 8);

            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarIDActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuRopaDeportivaInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuRopaDeportivaInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuRopaDeportivaInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuRopaDeportivaInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuRopaDeportivaInter().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTalla;
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.ButtonGroup buttonGroupUsuario;
    private javax.swing.JButton jButtonBorrarTodos;
    private javax.swing.JButton jButtonBorrarUno;
    private javax.swing.JButton jButtonConsultarTodo;
    private javax.swing.JButton jButtonConsultarUno;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonOrdenarID;
    private javax.swing.JButton jButtonOrdenarNombreAsc;
    private javax.swing.JButton jButtonOrdenarNombreDesc;
    private javax.swing.JButton jButtonOrdenarPrecioAsc;
    private javax.swing.JButton jButtonOrdenarPrecioDesc;
    private javax.swing.JComboBox<String> jComboBoxMarca;
    private javax.swing.JComboBox<String> jComboBoxTalla;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JComboBox<String> jComboBoxUsuario;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTalla;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUrl;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldColor;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldUrl;
    // End of variables declaration//GEN-END:variables
}
