/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaGUI;

import controlador.ManejadorImpresores;
import controlador.ManejadorObjetos;
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.CategoriaElectronicosOficina;
import modelo.Impresores;
import modelo.Marca;

/**
 *
 * @author Daniel
 */
public class MenuImpresoresInter extends javax.swing.JFrame {

    /**
     * Creates new form MenuImpresoresInter
     */
    ManejadorObjetos manobj;
    ManejadorImpresores manimp;
    Integer idMarcaTemporal = null;
    String nombreMarcaTemporal = "";
    DefaultTableModel model;
    int indiceFila = 0;
    String[] dato = new String[10];

    public MenuImpresoresInter() {
        initComponents();
        manobj = new ManejadorObjetos();
        manimp = new ManejadorImpresores();
        model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Nombre Marca");
        model.addColumn("Nombre");
        model.addColumn("Cantidad");
        model.addColumn("Precio");
        model.addColumn("Color");
        model.addColumn("Tipo Impresor");
        model.addColumn("Interface de Red");
        model.addColumn("Paginas por Minuto");
        model.addColumn("Resolución");
        jTable1.setModel(model);
        model.insertRow(indiceFila, dato);
        inicializarComboBox();
    }

    public void inicializarComboBox() {
        for (int i = 0; i < manobj.arregloMarcas.size(); i++) {
            jComboBoxMarca.addItem(manobj.arregloMarcas.get(i).getDescripcion());
        }
    }

    public void limpiar() {
        jTextFieldId.setText("");
        jTextFieldNombre.setText("");
        jTextFieldCantidad.setText("");
        jTextFieldPrecio.setText("");
        jTextFieldColor.setText("");
        jTextFieldUrl.setText("");
        jTextFieldTipoImpresor.setText("");
        jTextFieldInterfaceRed.setText("");
        jTextFieldPaginasporMinuto.setText("");
        jTextFieldResolucion.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTipoInterfaceRed = new javax.swing.JLabel();
        jLabelPaginasporMinuto = new javax.swing.JLabel();
        jLabelResolucion = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jComboBoxMarca = new javax.swing.JComboBox<>();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldCantidad = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldUrl = new javax.swing.JTextField();
        jTextFieldTipoImpresor = new javax.swing.JTextField();
        jTextFieldInterfaceRed = new javax.swing.JTextField();
        jTextFieldPaginasporMinuto = new javax.swing.JTextField();
        jTextFieldResolucion = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelUrl = new javax.swing.JLabel();
        jLabelColor = new javax.swing.JLabel();
        jTextFieldColor = new javax.swing.JTextField();
        jLabelTipoImpresor = new javax.swing.JLabel();
        jButtonBorrarUno = new javax.swing.JButton();
        jButtonBorrarTodos = new javax.swing.JButton();
        jButtonInsertar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonConsultarUno = new javax.swing.JButton();
        jButtonConsultarTodo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelMensaje = new javax.swing.JLabel();
        jButtonOrdenarID = new javax.swing.JButton();
        jButtonOrdenarNombreAsc = new javax.swing.JButton();
        jButtonOrdenarPrecioAsc = new javax.swing.JButton();
        jButtonOrdenarNombreDesc = new javax.swing.JButton();
        jButtonOrdenarPrecioDesc = new javax.swing.JButton();

        setTitle("Impresores\n");

        jLabelTipoInterfaceRed.setText("Interface Red");

        jLabelPaginasporMinuto.setText("Paginas por Minuto");

        jLabelResolucion.setText("Resolucion");

        jComboBoxMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMarcaItemStateChanged(evt);
            }
        });

        jLabelTitulo.setText("Impresores");

        jLabelId.setText("ID");

        jLabelMarca.setText("Marca");

        jLabelCantidad.setText("Cantidad");

        jLabelNombre.setText("Nombre");

        jLabelPrecio.setText("Precio");

        jLabelUrl.setText("Url");

        jLabelColor.setText("Color");

        jLabelTipoImpresor.setText("Tipo Impresor");

        jButtonBorrarUno.setText("Borrar Uno");
        jButtonBorrarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarUnoActionPerformed(evt);
            }
        });

        jButtonBorrarTodos.setText("Borrar Todos");
        jButtonBorrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTodosActionPerformed(evt);
            }
        });

        jButtonInsertar.setText("Insertar");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonConsultarUno.setText("Consultar Uno");
        jButtonConsultarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarUnoActionPerformed(evt);
            }
        });

        jButtonConsultarTodo.setText("Consultar Todo");
        jButtonConsultarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarTodoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabelMensaje.setText("Estado");

        jButtonOrdenarID.setText("Ordenar ID");
        jButtonOrdenarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarIDActionPerformed(evt);
            }
        });

        jButtonOrdenarNombreAsc.setText("Ordenar Nombre Ascendente");
        jButtonOrdenarNombreAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNombreAscActionPerformed(evt);
            }
        });

        jButtonOrdenarPrecioAsc.setText("Ordenar Precio Ascendente");
        jButtonOrdenarPrecioAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPrecioAscActionPerformed(evt);
            }
        });

        jButtonOrdenarNombreDesc.setText("Ordenar Nombre Descendente");
        jButtonOrdenarNombreDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNombreDescActionPerformed(evt);
            }
        });

        jButtonOrdenarPrecioDesc.setText("Ordenar Precio Descendente");
        jButtonOrdenarPrecioDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPrecioDescActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabelTitulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelId)
                                    .addComponent(jLabelMarca)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jLabelCantidad)
                                    .addComponent(jLabelPrecio))
                                .addGap(45, 45, 45))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelColor)
                                .addGap(48, 48, 48)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxMarca, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPrecio)
                            .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUrl)
                            .addComponent(jLabelTipoImpresor)
                            .addComponent(jLabelTipoInterfaceRed)
                            .addComponent(jLabelPaginasporMinuto)
                            .addComponent(jLabelResolucion))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldPaginasporMinuto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldInterfaceRed, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTipoImpresor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldResolucion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldUrl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonModificar)
                            .addComponent(jButtonConsultarUno)
                            .addComponent(jButtonConsultarTodo)
                            .addComponent(jButtonBorrarUno)
                            .addComponent(jButtonBorrarTodos)
                            .addComponent(jButtonInsertar))
                        .addGap(34, 34, 34))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonOrdenarNombreAsc)
                            .addComponent(jButtonOrdenarNombreDesc))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonOrdenarPrecioDesc)
                            .addComponent(jButtonOrdenarPrecioAsc))
                        .addGap(40, 40, 40)
                        .addComponent(jButtonOrdenarID))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonInsertar)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonModificar)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonConsultarUno)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonConsultarTodo)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonBorrarUno)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBorrarTodos))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUrl)
                            .addComponent(jTextFieldUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTipoImpresor)
                            .addComponent(jTextFieldTipoImpresor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTipoInterfaceRed)
                            .addComponent(jTextFieldInterfaceRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPaginasporMinuto)
                            .addComponent(jTextFieldPaginasporMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelResolucion)
                            .addComponent(jTextFieldResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMarca)
                            .addComponent(jComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombre)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCantidad)
                            .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrecio)
                            .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelColor)
                            .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonOrdenarNombreAsc)
                            .addComponent(jButtonOrdenarPrecioAsc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonOrdenarNombreDesc)
                            .addComponent(jButtonOrdenarPrecioDesc)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonOrdenarID)
                        .addGap(16, 16, 16)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarTodoActionPerformed

        manimp.consultarTodos();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectronicosOficina.arregloimpresores.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getInterfacered(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getPaginasminuto(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getResolucion(), indiceFila, 9);
            indiceFila++;
        }

    }//GEN-LAST:event_jButtonConsultarTodoActionPerformed

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed

        Impresores imp = new Impresores();

        try {
            if (!ValidaEnteros.validaEnteros(jTextFieldId.getText())) {
                throw new ValidaEnteros();
            }
            if (!ValidaCantidad.validaCantidad(jTextFieldCantidad.getText())) {
                throw new ValidaCantidad();
            }
            if (!ValidaFlotantes.validaFlotantes(jTextFieldPrecio.getText())) {
                throw new ValidaFlotantes();
            }
            if (!ValidaPaginasMin.validaPaginasMin(jTextFieldPaginasporMinuto.getText())) {
                throw new ValidaPaginasMin();
            }
        } catch (ValidaEnteros e) {
            jLabelMensaje.setText("El id que ingreso no es valido");
            jTextFieldId.setText("");
            return;
        } catch (ValidaCantidad e) {
            jLabelMensaje.setText("La cantidad que ingreso no es valida");
            jTextFieldCantidad.setText("");
            return;
        } catch (ValidaFlotantes e) {
            jLabelMensaje.setText("El precio que ingreso no es valido");
            jTextFieldPrecio.setText("");
            return;
        } catch (ValidaPaginasMin e) {
            jLabelMensaje.setText("la cantidad de paginas que ingreso no es valida");
            jTextFieldPaginasporMinuto.setText("");
            return;
        }

        Marca mar = new Marca();
        imp.setIdArticulo(Integer.parseInt(jTextFieldId.getText()));
        mar.setId(idMarcaTemporal);
        mar.setDescripcion(nombreMarcaTemporal);
        imp.setMar(mar);
        imp.setNombre(jTextFieldNombre.getText());
        imp.setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
        imp.setPrecio(Float.parseFloat(jTextFieldPrecio.getText()));
        imp.setColor(jTextFieldColor.getText());
        imp.setTipo(jTextFieldTipoImpresor.getText());
        imp.setInterfacered(jTextFieldInterfaceRed.getText());
        imp.setPaginasminuto(Integer.parseInt(jTextFieldPaginasporMinuto.getText()));
        imp.setResolucion(jTextFieldResolucion.getText());

        if (manimp.insertar(imp)) {
            jLabelMensaje.setText("El articulo " + jTextFieldNombre.getText() + " se insertó correctamente");
            //JOptionPane.showMessageDialog(this, "El articulo " + jTextFieldNombre.getText() + " se insertó correctamente");
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(jTextFieldId.getText(), indiceFila, 0);
            jTable1.setValueAt(nombreMarcaTemporal, indiceFila, 1);
            jTable1.setValueAt(jTextFieldNombre.getText(), indiceFila, 2);
            jTable1.setValueAt(jTextFieldCantidad.getText(), indiceFila, 3);
            jTable1.setValueAt(Float.parseFloat(jTextFieldPrecio.getText()), indiceFila, 4);
            jTable1.setValueAt(jTextFieldColor.getText(), indiceFila, 5);
            jTable1.setValueAt(jTextFieldTipoImpresor.getText(), indiceFila, 6);
            jTable1.setValueAt(jTextFieldInterfaceRed.getText(), indiceFila, 7);
            jTable1.setValueAt(Integer.parseInt(jTextFieldPaginasporMinuto.getText()), indiceFila, 8);
            jTable1.setValueAt(jTextFieldResolucion.getText(), indiceFila, 9);
            indiceFila++;
            manimp.consultarTodos();
        } else {
            jLabelMensaje.setText("Error al insertar");
            //JOptionPane.showMessageDialog(this, "Error al insertar");
        }
        limpiar();
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed

        int filaSeleccionada = jTable1.getSelectedRow();
        System.out.println(filaSeleccionada);

        if (filaSeleccionada >= 0) {

            Impresores impmod = new Impresores();
            int a = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            jTextFieldId.setText(jTable1.getValueAt(filaSeleccionada, 0).toString());
            String nombreMarcaMod = jTable1.getValueAt(filaSeleccionada, 1).toString();
            jTextFieldNombre.setText(jTable1.getValueAt(filaSeleccionada, 2).toString());
            jTextFieldCantidad.setText(jTable1.getValueAt(filaSeleccionada, 3).toString());
            jTextFieldPrecio.setText(jTable1.getValueAt(filaSeleccionada, 4).toString());
            jTextFieldColor.setText(jTable1.getValueAt(filaSeleccionada, 5).toString());
            jTextFieldTipoImpresor.setText(jTable1.getValueAt(filaSeleccionada, 6).toString());
            jTextFieldInterfaceRed.setText(jTable1.getValueAt(filaSeleccionada, 7).toString());
            jTextFieldPaginasporMinuto.setText(jTable1.getValueAt(filaSeleccionada, 8).toString());
            jTextFieldResolucion.setText(jTable1.getValueAt(filaSeleccionada, 9).toString());

            try {
                if (!ValidaCantidad.validaCantidad(jTextFieldCantidad.getText())) {
                    throw new ValidaCantidad();
                }
                if (!ValidaFlotantes.validaFlotantes(jTextFieldPrecio.getText())) {
                    throw new ValidaFlotantes();
                }
                if (!ValidaPaginasMin.validaPaginasMin(jTextFieldPaginasporMinuto.getText())) {
                    throw new ValidaPaginasMin();
                }
            } catch (ValidaCantidad e) {
                jLabelMensaje.setText("La cantidad que ingreso no es valida");
                jTextFieldCantidad.setText("");
                return;
            } catch (ValidaFlotantes e) {
                jLabelMensaje.setText("El precio que ingreso no es valido");
                jTextFieldPrecio.setText("");
                return;
            } catch (ValidaPaginasMin e) {
                jLabelMensaje.setText("la cantidad de paginas que ingreso no es valida");
                jTextFieldPaginasporMinuto.setText("");
                return;
            }
            Marca marmod = new Marca();
            impmod.setIdArticulo(Integer.parseInt(jTextFieldId.getText()));
            marmod.setId(a);
            marmod.setDescripcion(nombreMarcaMod);
            impmod.setMar(marmod);
            impmod.setNombre(jTextFieldNombre.getText());
            impmod.setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
            impmod.setPrecio(Float.parseFloat(jTextFieldPrecio.getText()));
            impmod.setColor(jTextFieldColor.getText());
            impmod.setTipo(jTextFieldTipoImpresor.getText());
            impmod.setInterfacered(jTextFieldInterfaceRed.getText());
            impmod.setPaginasminuto(Integer.parseInt(jTextFieldPaginasporMinuto.getText()));
            impmod.setResolucion(jTextFieldResolucion.getText());

            //Marca marmod = new Marca(Integer.parseInt(jTextFieldId.getText()), jTextFieldMarca.getText());
            int posicion = manimp.busquedaBinaria(a);
            if (!(posicion == -1)) {
                if (manimp.modificar(posicion, impmod)) {
                    JOptionPane.showMessageDialog(this, "Impresor modificado exitosamente");
                    indiceFila--;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar");
            }
        }
        limpiar();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonConsultarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarUnoActionPerformed

        int idBuscado = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el ID a buscar"));

        Impresores resultado = (Impresores) manimp.consultarId(idBuscado);
        if (resultado == null) {
            JOptionPane.showMessageDialog(this, "Impresor no encontrado");
        } else {
            JOptionPane.showMessageDialog(this, "El impresor encontrado es:\n" + resultado.toString());
        }

    }//GEN-LAST:event_jButtonConsultarUnoActionPerformed

    private void jButtonBorrarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarUnoActionPerformed

        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada >= 0) {
            int idEliminar = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            model.removeRow(filaSeleccionada);
            if (manimp.borrar(idEliminar)) {
                JOptionPane.showMessageDialog(this, "Impresor borrado exitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Error al borrar");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar");
        }

    }//GEN-LAST:event_jButtonBorrarUnoActionPerformed

    private void jButtonBorrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTodosActionPerformed

        if (manimp.borrarTodo()) {
            while (model.getRowCount() > 0) {
                model.removeRow(0);
            }
            indiceFila = 0;
            JOptionPane.showMessageDialog(this, "Todos los impresores se borraron exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar todo");
        }

    }//GEN-LAST:event_jButtonBorrarTodosActionPerformed

    private void jComboBoxMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMarcaItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (jComboBoxMarca.getItemCount() > 0) {
                idMarcaTemporal = ManejadorObjetos.arregloMarcas.get(jComboBoxMarca.getSelectedIndex()).getId();
                nombreMarcaTemporal = ManejadorObjetos.arregloMarcas.get(jComboBoxMarca.getSelectedIndex()).getDescripcion();
            }
        }

    }//GEN-LAST:event_jComboBoxMarcaItemStateChanged

    private void jButtonOrdenarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarIDActionPerformed
        manimp.sort();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectronicosOficina.arregloimpresores.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getInterfacered(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getPaginasminuto(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getResolucion(), indiceFila, 9);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarIDActionPerformed

    private void jButtonOrdenarNombreAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNombreAscActionPerformed
        manimp.ordenarMezcla();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectronicosOficina.arregloimpresores.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getInterfacered(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getPaginasminuto(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getResolucion(), indiceFila, 9);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarNombreAscActionPerformed

    private void jButtonOrdenarPrecioAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPrecioAscActionPerformed
        manimp.quicksort();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectronicosOficina.arregloimpresores.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getInterfacered(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getPaginasminuto(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getResolucion(), indiceFila, 9);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarPrecioAscActionPerformed

    private void jButtonOrdenarNombreDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNombreDescActionPerformed
        manimp.ordenarMezclaDesc();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectronicosOficina.arregloimpresores.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getInterfacered(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getPaginasminuto(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getResolucion(), indiceFila, 9);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarNombreDescActionPerformed

    private void jButtonOrdenarPrecioDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPrecioDescActionPerformed
        manimp.quicksortDesc();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectronicosOficina.arregloimpresores.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getInterfacered(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getPaginasminuto(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectronicosOficina.arregloimpresores.get(i).getResolucion(), indiceFila, 9);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarPrecioDescActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuImpresoresInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuImpresoresInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuImpresoresInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuImpresoresInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuImpresoresInter().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrarTodos;
    private javax.swing.JButton jButtonBorrarUno;
    private javax.swing.JButton jButtonConsultarTodo;
    private javax.swing.JButton jButtonConsultarUno;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonOrdenarID;
    private javax.swing.JButton jButtonOrdenarNombreAsc;
    private javax.swing.JButton jButtonOrdenarNombreDesc;
    private javax.swing.JButton jButtonOrdenarPrecioAsc;
    private javax.swing.JButton jButtonOrdenarPrecioDesc;
    private javax.swing.JComboBox<String> jComboBoxMarca;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPaginasporMinuto;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelResolucion;
    private javax.swing.JLabel jLabelTipoImpresor;
    private javax.swing.JLabel jLabelTipoInterfaceRed;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUrl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldColor;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldInterfaceRed;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPaginasporMinuto;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldResolucion;
    private javax.swing.JTextField jTextFieldTipoImpresor;
    private javax.swing.JTextField jTextFieldUrl;
    // End of variables declaration//GEN-END:variables
}
