/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaGUI;

import controlador.ManejadorUsuario;
import controladorDB.ManejadorUsuarioBD;
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Usuario;

/**
 *
 * @author danie
 */
public class MenuUsuarioInter extends javax.swing.JFrame {

    /**
     * Creates new form MenuUsuarioInter
     */
    ManejadorUsuarioBD manusuBD;
    ManejadorUsuario manusu;
    DefaultTableModel model;
    int indiceFila = 0;
    String[] dato = new String[9];
    Integer idPermisosTemporal = null;

    public MenuUsuarioInter() {
        initComponents();
        this.setLocationRelativeTo(null);
        model = new DefaultTableModel();
        model.addColumn("Cédula");
        model.addColumn("Permisos");
        model.addColumn("Nombre");
        model.addColumn("Apellido");
        model.addColumn("email");
        model.addColumn("Teléfono");
        model.addColumn("Usuario");
        model.addColumn("Password");
        model.addColumn("Dirección");
        manusuBD = new ManejadorUsuarioBD();
        manusu = new ManejadorUsuario();
        jTable1.setModel(model);
        model.insertRow(indiceFila, dato);
        iniciarCombobox();
    }

    private void limpiar() {
        campoCedula.setText("");
        campoNombre.setText("");
        campoApellido.setText("");
        campoEmail.setText("");
        campoUsuario.setText("");
        campoTelefono.setText("");
        campoPassword.setText("");
        campoDireccion.setText("");
    }

    private void iniciarCombobox() {
        comboBoxPermisos.removeAllItems();
        comboBoxPermisos.addItem("Consulta");
        comboBoxPermisos.addItem("Ingresa datos");
        comboBoxPermisos.addItem("Administrador");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUsuario = new javax.swing.JLabel();
        labelCedula = new javax.swing.JLabel();
        campoCedula = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        labelApellido = new javax.swing.JLabel();
        campoApellido = new javax.swing.JTextField();
        labelDireccion = new javax.swing.JLabel();
        campoDireccion = new javax.swing.JTextField();
        botonInsertar = new javax.swing.JButton();
        botonConsultarUno = new javax.swing.JToggleButton();
        botonConsultarTodos = new javax.swing.JButton();
        botonModificar = new javax.swing.JToggleButton();
        botonBorrarUno = new javax.swing.JButton();
        botonBorrarTodos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelEmail = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        labelTelefono = new javax.swing.JLabel();
        campoTelefono = new javax.swing.JTextField();
        labelUser = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        campoPassword = new javax.swing.JTextField();
        comboBoxPermisos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        botonOrdenar = new javax.swing.JButton();

        setTitle("Usuario");

        labelUsuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelUsuario.setText("USUARIO");

        labelCedula.setText("Cédula");

        labelNombre.setText("Nombre");

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        labelApellido.setText("Apellido");

        labelDireccion.setText("Dirección");

        botonInsertar.setText("Insertar");
        botonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsertarActionPerformed(evt);
            }
        });

        botonConsultarUno.setText("Consultar por ID");
        botonConsultarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarUnoActionPerformed(evt);
            }
        });

        botonConsultarTodos.setText("Consultar todos");
        botonConsultarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarTodosActionPerformed(evt);
            }
        });

        botonModificar.setText("Modificar");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        botonBorrarUno.setText("Borrar uno");
        botonBorrarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarUnoActionPerformed(evt);
            }
        });

        botonBorrarTodos.setText("Borrar todos");
        botonBorrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarTodosActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        labelEmail.setText("email");

        labelTelefono.setText("Teléfono");

        labelUser.setText("Nombre de usuario");

        labelPassword.setText("Contraseña");

        comboBoxPermisos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxPermisos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxPermisosItemStateChanged(evt);
            }
        });
        comboBoxPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPermisosActionPerformed(evt);
            }
        });

        jLabel1.setText("Permisos de usuario");

        botonOrdenar.setText("Ordenar");
        botonOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrdenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(labelUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(labelTelefono)
                                .addGap(18, 18, 18)
                                .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelUser)
                                .addGap(9, 9, 9)
                                .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelDireccion)
                                        .addGap(18, 18, 18)
                                        .addComponent(campoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelPassword)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCedula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelApellido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonInsertar)
                                    .addComponent(botonConsultarUno)
                                    .addComponent(botonModificar)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonBorrarUno)
                                    .addComponent(botonConsultarTodos)
                                    .addComponent(botonBorrarTodos)
                                    .addComponent(botonOrdenar))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelUsuario)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonInsertar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCedula)
                        .addComponent(campoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelNombre)
                        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelApellido)
                        .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEmail)
                            .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTelefono)
                            .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelUser)
                            .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPassword)
                            .addComponent(campoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(labelDireccion)
                            .addComponent(campoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBorrarUno)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(botonModificar)
                        .addGap(5, 5, 5)
                        .addComponent(botonConsultarUno)
                        .addGap(8, 8, 8)
                        .addComponent(botonConsultarTodos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBorrarTodos)
                .addGap(9, 9, 9)
                .addComponent(botonOrdenar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void botonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsertarActionPerformed
        Usuario usuarioInsertar = new Usuario();
        usuarioInsertar.setCedula(Integer.parseInt(campoCedula.getText()));
        usuarioInsertar.setPermisos(comboBoxPermisos.getSelectedIndex());
        usuarioInsertar.setNombre(campoNombre.getText());
        usuarioInsertar.setApellido(campoApellido.getText());
        usuarioInsertar.setEmail(campoEmail.getText());
        usuarioInsertar.setTelefono(campoTelefono.getText());
        usuarioInsertar.setUsuario(campoUsuario.getText());
        usuarioInsertar.setPassword(campoPassword.getText());
        usuarioInsertar.setDireccion(campoDireccion.getText());
        if (manusuBD.insertar(usuarioInsertar)) {
            JOptionPane.showMessageDialog(this, "El usuario " + campoUsuario.getText() + " se insertó correctamente");
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(campoCedula.getText(), indiceFila, 0);
            jTable1.setValueAt(comboBoxPermisos.getSelectedIndex(), indiceFila, 1);
            jTable1.setValueAt(campoNombre.getText(), indiceFila, 2);
            jTable1.setValueAt(campoApellido.getText(), indiceFila, 3);
            jTable1.setValueAt(campoEmail.getText(), indiceFila, 4);
            jTable1.setValueAt(campoTelefono.getText(), indiceFila, 5);
            jTable1.setValueAt(campoUsuario.getText(), indiceFila, 6);
            jTable1.setValueAt(campoPassword.getText(), indiceFila, 7);
            jTable1.setValueAt(campoDireccion.getText(), indiceFila, 8);
            limpiar();
            indiceFila++;
        } else {
            JOptionPane.showMessageDialog(this, "Error al insertar");
        }
    }//GEN-LAST:event_botonInsertarActionPerformed

    private void botonConsultarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarUnoActionPerformed
        try {
            int idBuscado = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite la cédula a buscar"));
            Usuario resultado = (Usuario) manusuBD.consultarId(idBuscado);
            JOptionPane.showMessageDialog(this, "El usuario encontrado es:\n" + resultado.toString());
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Elemento no encontrado");
        }
    }//GEN-LAST:event_botonConsultarUnoActionPerformed

    private void botonConsultarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarTodosActionPerformed
        manusuBD.consultarTodos();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < ManejadorUsuario.arregloUsuario.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(ManejadorUsuario.arregloUsuario.get(i).getCedula(), indiceFila, 0);
            jTable1.setValueAt(ManejadorUsuario.arregloUsuario.get(i).getPermisos(), indiceFila, 1);
            jTable1.setValueAt(ManejadorUsuario.arregloUsuario.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(ManejadorUsuario.arregloUsuario.get(i).getApellido(), indiceFila, 3);
            jTable1.setValueAt(ManejadorUsuario.arregloUsuario.get(i).getEmail(), indiceFila, 4);
            jTable1.setValueAt(ManejadorUsuario.arregloUsuario.get(i).getTelefono(), indiceFila, 5);
            jTable1.setValueAt(ManejadorUsuario.arregloUsuario.get(i).getUsuario(), indiceFila, 6);
            jTable1.setValueAt(ManejadorUsuario.arregloUsuario.get(i).getPassword(), indiceFila, 7);
            jTable1.setValueAt(ManejadorUsuario.arregloUsuario.get(i).getDireccion(), indiceFila, 8);
            indiceFila++;
        }
    }//GEN-LAST:event_botonConsultarTodosActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();

        if (filaSeleccionada >= 0) {
            int id = Integer.parseInt(campoCedula.getText());
            campoCedula.setText(jTable1.getValueAt(filaSeleccionada, 0).toString());
            campoNombre.setText(jTable1.getValueAt(filaSeleccionada, 2).toString());
            campoApellido.setText(jTable1.getValueAt(filaSeleccionada, 3).toString());
            campoEmail.setText(jTable1.getValueAt(filaSeleccionada, 4).toString());
            campoTelefono.setText(jTable1.getValueAt(filaSeleccionada, 5).toString());
            campoUsuario.setText(jTable1.getValueAt(filaSeleccionada, 6).toString());
            campoPassword.setText(jTable1.getValueAt(filaSeleccionada, 7).toString());
            campoDireccion.setText(jTable1.getValueAt(filaSeleccionada, 8).toString());
            Usuario usuarioModificado = new Usuario();
            usuarioModificado.setCedula(Integer.parseInt(campoCedula.getText()));
            usuarioModificado.setPermisos((int) idPermisosTemporal);
            usuarioModificado.setNombre(campoNombre.getText());
            usuarioModificado.setApellido(campoApellido.getText());
            usuarioModificado.setEmail(campoEmail.getText());
            usuarioModificado.setTelefono(campoTelefono.getText());
            usuarioModificado.setUsuario(campoUsuario.getText());
            usuarioModificado.setPassword(campoPassword.getText());
            usuarioModificado.setDireccion(campoDireccion.getText());
            if (manusuBD.modificar(id, usuarioModificado)) {
                JOptionPane.showMessageDialog(this, "Usuario modificado exitosamente");
                indiceFila--;
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar");
            }
        }
    }//GEN-LAST:event_botonModificarActionPerformed

    private void botonBorrarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarUnoActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada >= 0) {
            int idEliminar = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            model.removeRow(filaSeleccionada);
            manusuBD.borrar(idEliminar);
            JOptionPane.showMessageDialog(this, "Usuario borrado exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar");
        }
    }//GEN-LAST:event_botonBorrarUnoActionPerformed

    private void botonBorrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarTodosActionPerformed
        if (manusuBD.borrarTodo()) {
            while (model.getRowCount() > 0) {
                model.removeRow(0);
            }
            indiceFila = 0;
            JOptionPane.showMessageDialog(this, "Todos los usuarios se borraron exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar todo");
        }
    }//GEN-LAST:event_botonBorrarTodosActionPerformed

    private void comboBoxPermisosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxPermisosItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (comboBoxPermisos.getItemCount() > 0) {
                idPermisosTemporal = comboBoxPermisos.getSelectedIndex();
            }
        }
    }//GEN-LAST:event_comboBoxPermisosItemStateChanged

    private void comboBoxPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPermisosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxPermisosActionPerformed

    private void botonOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrdenarActionPerformed
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        indiceFila = 0;
        manusu.sort();
        for (int i = 0; i < ManejadorUsuario.arregloUsuario.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(ManejadorUsuario.arregloUsuario.get(i).getCedula(), indiceFila, 0);
            jTable1.setValueAt(ManejadorUsuario.arregloUsuario.get(i).getPermisos(), indiceFila, 1);
            jTable1.setValueAt(ManejadorUsuario.arregloUsuario.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(ManejadorUsuario.arregloUsuario.get(i).getApellido(), indiceFila, 3);
            jTable1.setValueAt(ManejadorUsuario.arregloUsuario.get(i).getEmail(), indiceFila, 4);
            jTable1.setValueAt(ManejadorUsuario.arregloUsuario.get(i).getTelefono(), indiceFila, 5);
            jTable1.setValueAt(ManejadorUsuario.arregloUsuario.get(i).getUsuario(), indiceFila, 6);
            jTable1.setValueAt(ManejadorUsuario.arregloUsuario.get(i).getPassword(), indiceFila, 7);
            jTable1.setValueAt(ManejadorUsuario.arregloUsuario.get(i).getDireccion(), indiceFila, 8);
            indiceFila++;
        }
    }//GEN-LAST:event_botonOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuUsuarioInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuUsuarioInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuUsuarioInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuUsuarioInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuUsuarioInter().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrarTodos;
    private javax.swing.JButton botonBorrarUno;
    private javax.swing.JButton botonConsultarTodos;
    private javax.swing.JToggleButton botonConsultarUno;
    private javax.swing.JButton botonInsertar;
    private javax.swing.JToggleButton botonModificar;
    private javax.swing.JButton botonOrdenar;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoCedula;
    private javax.swing.JTextField campoDireccion;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoPassword;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JComboBox<String> comboBoxPermisos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelCedula;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelUser;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables
}
