/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaGUI;

import controlador.ManejadorObjetos;
import controlador.ManejadorSierras;
import controladorDB.ManejadorMarcasDB;
import controladorDB.ManejadorSierraBD;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import modelo.CategoriaHerramientas;
import modelo.Marca;
import modelo.Sierras;

/**
 *
 * @author danie
 */
public class MenuSierrasInter extends javax.swing.JFrame {

    /**
     * Creates new form MenuSierrasInter
     */
    ManejadorObjetos manobj;
    ManejadorSierras mansie;
    ManejadorMarcasDB manmarDB;
    ManejadorSierraBD mansieBD;
    Integer idMarcaTemporal = null;
    String nombreMarcaTemporal = "";
    DefaultTableModel model;
    int indiceFila = 0;
    String[] dato = new String[11];
    JFileChooser fileChooser = new JFileChooser();
    ImageIcon image = null;
    File archivo = null;
    String ruta = "E:\\daniel\\Descargas\\graySquare.jpeg";
    JLabel labelImagen = new JLabel("", new ImageIcon(ruta), JLabel.CENTER);

    public MenuSierrasInter() {
        initComponents();
        this.setLocationRelativeTo(null);
        manobj = new ManejadorObjetos();
        mansie = new ManejadorSierras();
        manmarDB = new ManejadorMarcasDB();
        mansieBD = new ManejadorSierraBD();
        model = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int column) {
                switch (column) {
                    case 11:
                        return ImageIcon.class;
                    default:
                        return String.class;
                }
            }
        };;
        model.addColumn("Id");
        model.addColumn("Nombre Marca");
        model.addColumn("Nombre");
        model.addColumn("Cantidad");
        model.addColumn("Precio");
        model.addColumn("Color");
        model.addColumn("Tipo");
        model.addColumn("Potencia");
        model.addColumn("Velocidad");
        model.addColumn("Peso");
        model.addColumn("Diametro Disco");
        model.addColumn("Imagen");
        jTable1.setModel(model);
        jTable1.getColumnModel().getColumn(0).setMinWidth(30);
        jTable1.getColumnModel().getColumn(11).setMinWidth(150);
        model.insertRow(indiceFila, dato);
        inicializarComboBox();
        fileChooser.setAcceptAllFileFilterUsed(false);
        FileFilter imageFilter = new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());
        fileChooser.addChoosableFileFilter(imageFilter);
        panelImagen.setPreferredSize(new Dimension(132, 132));
        panelImagen.add(labelImagen, BorderLayout.CENTER);
        jTable1.setRowHeight(150);
        jTable1.setRowMargin(5);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.jpg")).getImage());
        ImageIcon ilogo = new ImageIcon(getClass().getResource("/imagenes/icono.jpg"));
        ImageIcon logo = new ImageIcon(ilogo.getImage().getScaledInstance(jlogo.getWidth(), jlogo.getHeight(), Image.SCALE_DEFAULT));
        jlogo.setIcon(logo);
    }

//    public void inicializarComboBox() {
//        for (int i = 0; i < manobj.arregloMarcas.size(); i++) {
//            jComboBoxMarca.addItem(manobj.arregloMarcas.get(i).getDescripcion());
//        }
//    }
    public void inicializarComboBox() {
        manmarDB.consultarTodos();
        for (int i = 0; i < ManejadorObjetos.arregloMarcas.size(); i++) {
            jComboBoxMarca.addItem(ManejadorObjetos.arregloMarcas.get(i).getDescripcion());
        }
    }

    public void limpiar() {
        jTextFieldId.setText("");
        jTextFieldNombre.setText("");
        jTextFieldCantidad.setText("");
        jTextFieldPrecio.setText("");
        jTextFieldColor.setText("");
        jTextFieldTipo.setText("");
        jTextFieldPotencia.setText("");
        jTextFieldVelocidad.setText("");
        jTextFieldPeso.setText("");
        jTextFieldDiametroDisco.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMarca = new javax.swing.JLabel();
        jLabelPotencia = new javax.swing.JLabel();
        jLabelColor = new javax.swing.JLabel();
        jButtonBorrarUno = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonModificar = new javax.swing.JButton();
        jTextFieldColor = new javax.swing.JTextField();
        jComboBoxMarca = new javax.swing.JComboBox<>();
        jLabelTipo = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelMensaje = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldTipo = new javax.swing.JTextField();
        jLabelCantidad = new javax.swing.JLabel();
        jTextFieldPotencia = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldVelocidad = new javax.swing.JTextField();
        jLabelVelocidad = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonBorrarTodos = new javax.swing.JButton();
        jButtonConsultarUno = new javax.swing.JButton();
        jLabelId = new javax.swing.JLabel();
        jButtonConsultarTodo = new javax.swing.JButton();
        jButtonInsertar = new javax.swing.JButton();
        jTextFieldId = new javax.swing.JTextField();
        jLabelPeso = new javax.swing.JLabel();
        jLabelDiametroDisco = new javax.swing.JLabel();
        jTextFieldPeso = new javax.swing.JTextField();
        jTextFieldDiametroDisco = new javax.swing.JTextField();
        jButtonOrdenarNombreAsc = new javax.swing.JButton();
        jButtonOrdenarPrecioAsc = new javax.swing.JButton();
        jButtonOrdenarNombreDesc = new javax.swing.JButton();
        jButtonOrdenarPrecioDesc = new javax.swing.JButton();
        jButtonOrdenarID = new javax.swing.JButton();
        panelImagen = new javax.swing.JPanel();
        botonFileChooser = new javax.swing.JButton();
        jlogo = new javax.swing.JLabel();

        setTitle("Sierras");

        jLabelMarca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMarca.setText("Marca");

        jLabelPotencia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPotencia.setText("Potencia");

        jLabelColor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelColor.setText("Color");

        jButtonBorrarUno.setText("Borrar Uno");
        jButtonBorrarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarUnoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jComboBoxMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMarcaItemStateChanged(evt);
            }
        });

        jLabelTipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTipo.setText("Tipo");

        jLabelMensaje.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMensaje.setText("Estado");

        jTextFieldTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoActionPerformed(evt);
            }
        });

        jLabelCantidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCantidad.setText("Cantidad");

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNombre.setText("Nombre");

        jLabelVelocidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelVelocidad.setText("Velocidad");

        jLabelPrecio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPrecio.setText("Precio");

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI Historic", 3, 36)); // NOI18N
        jLabelTitulo.setText("Sierras");

        jButtonBorrarTodos.setText("Borrar Todos");
        jButtonBorrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTodosActionPerformed(evt);
            }
        });

        jButtonConsultarUno.setText("Consultar Uno");
        jButtonConsultarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarUnoActionPerformed(evt);
            }
        });

        jLabelId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId.setText("ID");

        jButtonConsultarTodo.setText("Consultar Todo");
        jButtonConsultarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarTodoActionPerformed(evt);
            }
        });

        jButtonInsertar.setText("Insertar");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });

        jLabelPeso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPeso.setText("Peso");

        jLabelDiametroDisco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDiametroDisco.setText("Diametro Disco");

        jButtonOrdenarNombreAsc.setText("Ordenar Nombre Ascendente");
        jButtonOrdenarNombreAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNombreAscActionPerformed(evt);
            }
        });

        jButtonOrdenarPrecioAsc.setText("Ordenar Precio Ascendente");
        jButtonOrdenarPrecioAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPrecioAscActionPerformed(evt);
            }
        });

        jButtonOrdenarNombreDesc.setText("Ordenar Nombre Descendente");
        jButtonOrdenarNombreDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNombreDescActionPerformed(evt);
            }
        });

        jButtonOrdenarPrecioDesc.setText("Ordenar Precio Descendente");
        jButtonOrdenarPrecioDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPrecioDescActionPerformed(evt);
            }
        });

        jButtonOrdenarID.setText("Ordenar ID");
        jButtonOrdenarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarIDActionPerformed(evt);
            }
        });

        panelImagen.setBackground(new java.awt.Color(204, 204, 204));
        panelImagen.setLayout(new java.awt.BorderLayout());

        botonFileChooser.setText("Examinar...");
        botonFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFileChooserActionPerformed(evt);
            }
        });

        jlogo.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonOrdenarNombreDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonOrdenarNombreAsc, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonOrdenarPrecioDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonOrdenarPrecioAsc, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addComponent(jButtonOrdenarID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelId)
                                            .addComponent(jLabelMarca)
                                            .addComponent(jLabelNombre)
                                            .addComponent(jLabelCantidad)
                                            .addComponent(jLabelPrecio))
                                        .addGap(45, 45, 45))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelColor)
                                        .addGap(48, 48, 48)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxMarca, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldId, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPrecio)
                                    .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelTipo)
                                            .addComponent(jLabelPotencia)
                                            .addComponent(jLabelVelocidad)
                                            .addComponent(jLabelPeso))
                                        .addGap(78, 78, 78)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldPeso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                            .addComponent(jTextFieldVelocidad, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldPotencia, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldTipo, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabelDiametroDisco)
                                        .addGap(46, 46, 46)
                                        .addComponent(jTextFieldDiametroDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(botonFileChooser)
                                        .addGap(66, 66, 66)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonModificar)
                            .addComponent(jButtonConsultarUno)
                            .addComponent(jButtonConsultarTodo)
                            .addComponent(jButtonBorrarUno)
                            .addComponent(jButtonBorrarTodos)
                            .addComponent(jButtonInsertar))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitulo))
                    .addComponent(jlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelId)
                                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelMarca)
                                            .addComponent(jComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelNombre)
                                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelCantidad)
                                            .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelPrecio)
                                            .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelColor)
                                    .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelTipo)
                                    .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelPotencia)
                                    .addComponent(jTextFieldPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelVelocidad)
                                    .addComponent(jTextFieldVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPeso))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldDiametroDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDiametroDisco))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonOrdenarNombreAsc)
                                    .addComponent(jButtonOrdenarPrecioAsc))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonOrdenarNombreDesc)
                                    .addComponent(jButtonOrdenarPrecioDesc)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonOrdenarID)
                                .addGap(14, 14, 14))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonInsertar)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonModificar)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonConsultarUno)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonConsultarTodo)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonBorrarUno)
                            .addComponent(botonFileChooser))
                        .addGap(10, 10, 10)
                        .addComponent(jButtonBorrarTodos)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoActionPerformed

    private void jButtonConsultarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarTodoActionPerformed
        mansieBD.consultarTodos();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaHerramientas.arreglosierras.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getPotencia(), indiceFila, 7);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getVelocidad(), indiceFila, 8);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getPeso(), indiceFila, 9);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getDiametrodisco(), indiceFila, 10);
            jTable1.setValueAt(new ImageIcon(CategoriaHerramientas.arreglosierras.get(i).getImagen()), indiceFila, 11);

            indiceFila++;
        }
    }//GEN-LAST:event_jButtonConsultarTodoActionPerformed

    private void jComboBoxMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMarcaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (jComboBoxMarca.getItemCount() > 0) {
                idMarcaTemporal = ManejadorObjetos.arregloMarcas.get(jComboBoxMarca.getSelectedIndex()).getId();
                nombreMarcaTemporal = ManejadorObjetos.arregloMarcas.get(jComboBoxMarca.getSelectedIndex()).getDescripcion();
            }
        }
    }//GEN-LAST:event_jComboBoxMarcaItemStateChanged

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
        Sierras sie = new Sierras();

        try {
            if (!ValidaEnteros.validaEnteros(jTextFieldId.getText())) {
                throw new ValidaEnteros();
            }
            if (!ValidaCantidad.validaCantidad(jTextFieldCantidad.getText())) {
                throw new ValidaCantidad();
            }
            if (!ValidaFlotantes.validaFlotantes(jTextFieldPrecio.getText())) {
                throw new ValidaFlotantes();
            }
            if (!ValidaPotencia.validaPotencia(jTextFieldPotencia.getText())) {
                throw new ValidaPotencia();
            }
            if (!ValidaVelocidad.validaVelocidad(jTextFieldVelocidad.getText())) {
                throw new ValidaVelocidad();
            }
            if (!ValidaPesoR.validaPesoR(jTextFieldPeso.getText())) {
                throw new ValidaPesoR();
            }
            if (!ValidaDiametroDisco.validaDiametroDisco(jTextFieldDiametroDisco.getText())) {
                throw new ValidaDiametroDisco();
            }
        } catch (ValidaEnteros e) {
            jLabelMensaje.setText("El id que ingreso no es valido");
            jTextFieldId.setText("");
            return;
        } catch (ValidaCantidad e) {
            jLabelMensaje.setText("La cantidad que ingreso no es valida");
            jTextFieldCantidad.setText("");
            return;
        } catch (ValidaFlotantes e) {
            jLabelMensaje.setText("El precio que ingreso no es valido");
            jTextFieldPrecio.setText("");
            return;
        } catch (ValidaPotencia e) {
            jLabelMensaje.setText("La potencia que ingreso no es valida");
            jTextFieldPotencia.setText("");
            return;
        } catch (ValidaVelocidad e) {
            jLabelMensaje.setText("La velocidad que ingreso no es valido");
            jTextFieldVelocidad.setText("");
            return;
        } catch (ValidaPesoR e) {
            jLabelMensaje.setText("El peso que ingreso no es valido");
            jTextFieldPeso.setText("");
            return;
        } catch (ValidaDiametroDisco e) {
            jLabelMensaje.setText("El diametro que ingreso no es valido");
            jTextFieldDiametroDisco.setText("");
            return;
        }

        Marca mar = new Marca();
        sie.setIdArticulo(Integer.parseInt(jTextFieldId.getText()));
        mar.setId(idMarcaTemporal);
        mar.setDescripcion(nombreMarcaTemporal);
        sie.setMar(mar);
        sie.setNombre(jTextFieldNombre.getText());
        sie.setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
        sie.setPrecio(Float.parseFloat(jTextFieldPrecio.getText()));
        sie.setColor(jTextFieldColor.getText());
        sie.setImagen(ruta);
        sie.setTipo(jTextFieldTipo.getText());
        sie.setPotencia(Integer.parseInt(jTextFieldPotencia.getText()));
        sie.setVelocidad(Integer.parseInt(jTextFieldVelocidad.getText()));
        sie.setPeso(Float.parseFloat(jTextFieldPeso.getText()));
        sie.setDiametrodisco(Float.parseFloat(jTextFieldDiametroDisco.getText()));

        if (mansieBD.insertar(sie)) {
            jLabelMensaje.setText("El articulo " + jTextFieldNombre.getText() + " se insertó correctamente");
            //JOptionPane.showMessageDialog(this, "El articulo " + jTextFieldNombre.getText() + " se insertó correctamente");
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(jTextFieldId.getText(), indiceFila, 0);
            jTable1.setValueAt(nombreMarcaTemporal, indiceFila, 1);
            jTable1.setValueAt(jTextFieldNombre.getText(), indiceFila, 2);
            jTable1.setValueAt(jTextFieldCantidad.getText(), indiceFila, 3);
            jTable1.setValueAt(jTextFieldPrecio.getText(), indiceFila, 4);
            jTable1.setValueAt(jTextFieldColor.getText(), indiceFila, 5);
            jTable1.setValueAt(jTextFieldTipo.getText(), indiceFila, 6);
            jTable1.setValueAt(jTextFieldPotencia.getText(), indiceFila, 7);
            jTable1.setValueAt(jTextFieldVelocidad.getText(), indiceFila, 8);
            jTable1.setValueAt(jTextFieldPeso.getText(), indiceFila, 9);
            jTable1.setValueAt(jTextFieldDiametroDisco.getText(), indiceFila, 10);
            jTable1.setValueAt(ruta, indiceFila, 11);
            jTable1.setValueAt(new ImageIcon(ruta), indiceFila, 11);
            ruta = "E:\\daniel\\Descargas\\graySquare.jpeg";
            image = new ImageIcon(ruta);
            labelImagen.setIcon(image);
            indiceFila++;
            mansieBD.consultarTodos();
        } else {
            jLabelMensaje.setText("Error al insertar");
            //JOptionPane.showMessageDialog(this, "Error al insertar");
        }
        limpiar();
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        System.out.println(filaSeleccionada);

        if (filaSeleccionada >= 0) {

            Sierras siemod = new Sierras();
            int a = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            jTextFieldId.setText(jTable1.getValueAt(filaSeleccionada, 0).toString());
            String nombreMarcaMod = jTable1.getValueAt(filaSeleccionada, 1).toString();
            jTextFieldNombre.setText(jTable1.getValueAt(filaSeleccionada, 2).toString());
            jTextFieldCantidad.setText(jTable1.getValueAt(filaSeleccionada, 3).toString());
            jTextFieldPrecio.setText(jTable1.getValueAt(filaSeleccionada, 4).toString());
            jTextFieldColor.setText(jTable1.getValueAt(filaSeleccionada, 5).toString());
            jTextFieldTipo.setText(jTable1.getValueAt(filaSeleccionada, 6).toString());
            jTextFieldPotencia.setText(jTable1.getValueAt(filaSeleccionada, 7).toString());
            jTextFieldVelocidad.setText(jTable1.getValueAt(filaSeleccionada, 8).toString());
            jTextFieldPeso.setText(jTable1.getValueAt(filaSeleccionada, 9).toString());
            jTextFieldDiametroDisco.setText(jTable1.getValueAt(filaSeleccionada, 10).toString());
            String img = jTable1.getValueAt(filaSeleccionada, 11).toString();

            try {

                if (!ValidaCantidad.validaCantidad(jTextFieldCantidad.getText())) {
                    throw new ValidaCantidad();
                }
                if (!ValidaFlotantes.validaFlotantes(jTextFieldPrecio.getText())) {
                    throw new ValidaFlotantes();
                }
                if (!ValidaPotencia.validaPotencia(jTextFieldPotencia.getText())) {
                    throw new ValidaPotencia();
                }
                if (!ValidaVelocidad.validaVelocidad(jTextFieldVelocidad.getText())) {
                    throw new ValidaVelocidad();
                }
                if (!ValidaPesoR.validaPesoR(jTextFieldPeso.getText())) {
                    throw new ValidaPesoR();
                }
                if (!ValidaDiametroDisco.validaDiametroDisco(jTextFieldDiametroDisco.getText())) {
                    throw new ValidaDiametroDisco();
                }
            } catch (ValidaCantidad e) {
                jLabelMensaje.setText("La cantidad que ingreso no es valida");
                jTextFieldCantidad.setText("");
                return;
            } catch (ValidaFlotantes e) {
                jLabelMensaje.setText("El precio que ingreso no es valido");
                jTextFieldPrecio.setText("");
                return;
            } catch (ValidaPotencia e) {
                jLabelMensaje.setText("La potencia que ingreso no es valida");
                jTextFieldPotencia.setText("");
                return;
            } catch (ValidaVelocidad e) {
                jLabelMensaje.setText("La velocidad que ingreso no es valido");
                jTextFieldVelocidad.setText("");
                return;
            } catch (ValidaPesoR e) {
                jLabelMensaje.setText("El peso que ingreso no es valido");
                jTextFieldPeso.setText("");
                return;
            } catch (ValidaDiametroDisco e) {
                jLabelMensaje.setText("El diametro que ingreso no es valido");
                jTextFieldDiametroDisco.setText("");
                return;
            }

            Marca marmod = new Marca();
            siemod.setIdArticulo(Integer.parseInt(jTextFieldId.getText()));
            marmod.setId(a);
            marmod.setDescripcion(nombreMarcaMod);
            siemod.setMar(marmod);
            siemod.setNombre(jTextFieldNombre.getText());
            siemod.setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
            siemod.setPrecio(Float.parseFloat(jTextFieldPrecio.getText()));
            siemod.setColor(jTextFieldColor.getText());
            siemod.setTipo(jTextFieldTipo.getText());
            siemod.setPotencia(Integer.parseInt(jTextFieldPotencia.getText()));
            siemod.setVelocidad(Integer.parseInt(jTextFieldVelocidad.getText()));
            siemod.setPeso(Float.parseFloat(jTextFieldPeso.getText()));
            siemod.setDiametrodisco(Float.parseFloat(jTextFieldDiametroDisco.getText()));
            if (ruta.equals("E:\\daniel\\Descargas\\graySquare.jpeg")) {
                siemod.setImagen(img);
            } else {
                siemod.setImagen(ruta);
                ruta = "E:\\daniel\\Descargas\\graySquare.jpeg";
                image = new ImageIcon(ruta);
                labelImagen.setIcon(image);
            }

            //Marca marmod = new Marca(Integer.parseInt(jTextFieldId.getText()), jTextFieldMarca.getText());
//            int posicion = mansie.busquedaBinaria(a);
//            if (!(posicion == -1)) {
//                if (mansie.modificar(posicion, siemod)) {
//                    JOptionPane.showMessageDialog(this, "La sierra se ha modificado exitosamente");
//                    indiceFila--;
//                }
//            } else {
//                JOptionPane.showMessageDialog(this, "Error al modificar");
//            }
//        } else {
//            JOptionPane.showMessageDialog(this, "Error al modificar");
//        }
            if (mansieBD.modificar(a, siemod)) {
                JOptionPane.showMessageDialog(this, "La sierra modificada exitosamente");
                indiceFila--;
                mansieBD.consultarTodos();

            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar");
            }
        }

        limpiar();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonConsultarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarUnoActionPerformed
//        int idBuscado = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el ID a buscar"));
//
//        Sierras resultado = (Sierras) mansie.consultarId(idBuscado);
//        if (resultado == null) {
//            JOptionPane.showMessageDialog(this, "Sierra no encontrada");
//        } else {
//            JOptionPane.showMessageDialog(this, "La sierra encontrada es:\n" + resultado.toString());
//        }
        try {
            int idBuscado = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el ID a buscar"));
            Sierras resultado = (Sierras) mansieBD.consultarId(idBuscado);
            JOptionPane.showMessageDialog(this, "La sierra encontrada es:\n" + resultado.toString());
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Sierra no encontrada");

        }
    }//GEN-LAST:event_jButtonConsultarUnoActionPerformed

    private void jButtonBorrarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarUnoActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada >= 0) {
            int idEliminar = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            model.removeRow(filaSeleccionada);
            if (mansieBD.borrar(idEliminar)) {
                JOptionPane.showMessageDialog(this, "Sierra borrada exitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Error al borrar");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar");
        }
    }//GEN-LAST:event_jButtonBorrarUnoActionPerformed

    private void jButtonBorrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTodosActionPerformed
        if (mansieBD.borrarTodo()) {
            while (model.getRowCount() > 0) {
                model.removeRow(0);
            }
            indiceFila = 0;
            JOptionPane.showMessageDialog(this, "Todos las sierras se borraron exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar todo");
        }
    }//GEN-LAST:event_jButtonBorrarTodosActionPerformed

    private void jButtonOrdenarNombreAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNombreAscActionPerformed
        mansie.ordenarMezcla();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaHerramientas.arreglosierras.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getPotencia(), indiceFila, 7);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getVelocidad(), indiceFila, 8);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getPeso(), indiceFila, 9);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getDiametrodisco(), indiceFila, 10);
            jTable1.setValueAt(new ImageIcon(CategoriaHerramientas.arreglosierras.get(i).getImagen()), indiceFila, 11);

            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarNombreAscActionPerformed

    private void jButtonOrdenarPrecioAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPrecioAscActionPerformed
        mansie.quicksort();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaHerramientas.arreglosierras.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getPotencia(), indiceFila, 7);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getVelocidad(), indiceFila, 8);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getPeso(), indiceFila, 9);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getDiametrodisco(), indiceFila, 10);
            jTable1.setValueAt(new ImageIcon(CategoriaHerramientas.arreglosierras.get(i).getImagen()), indiceFila, 11);

            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarPrecioAscActionPerformed

    private void jButtonOrdenarNombreDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNombreDescActionPerformed
        mansie.ordenarMezclaDesc();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaHerramientas.arreglosierras.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getPotencia(), indiceFila, 7);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getVelocidad(), indiceFila, 8);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getPeso(), indiceFila, 9);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getDiametrodisco(), indiceFila, 10);
            jTable1.setValueAt(new ImageIcon(CategoriaHerramientas.arreglosierras.get(i).getImagen()), indiceFila, 11);

            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarNombreDescActionPerformed

    private void jButtonOrdenarPrecioDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPrecioDescActionPerformed
        mansie.quicksortDesc();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaHerramientas.arreglosierras.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getPotencia(), indiceFila, 7);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getVelocidad(), indiceFila, 8);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getPeso(), indiceFila, 9);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getDiametrodisco(), indiceFila, 10);
            jTable1.setValueAt(new ImageIcon(CategoriaHerramientas.arreglosierras.get(i).getImagen()), indiceFila, 11);

            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarPrecioDescActionPerformed

    private void jButtonOrdenarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarIDActionPerformed
        mansie.sort();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaHerramientas.arreglosierras.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getPotencia(), indiceFila, 7);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getVelocidad(), indiceFila, 8);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getPeso(), indiceFila, 9);
            jTable1.setValueAt(CategoriaHerramientas.arreglosierras.get(i).getDiametrodisco(), indiceFila, 10);
            jTable1.setValueAt(new ImageIcon(CategoriaHerramientas.arreglosierras.get(i).getImagen()), indiceFila, 11);

            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarIDActionPerformed

    private void botonFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFileChooserActionPerformed
        fileChooser.showDialog(this, "Choose"); //
        archivo = fileChooser.getSelectedFile();
        ruta = archivo.getAbsolutePath();
        image = new ImageIcon(ruta);
        labelImagen.setIcon(image);
    }//GEN-LAST:event_botonFileChooserActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuSierrasInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuSierrasInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuSierrasInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuSierrasInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuSierrasInter().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonFileChooser;
    private javax.swing.JButton jButtonBorrarTodos;
    private javax.swing.JButton jButtonBorrarUno;
    private javax.swing.JButton jButtonConsultarTodo;
    private javax.swing.JButton jButtonConsultarUno;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonOrdenarID;
    private javax.swing.JButton jButtonOrdenarNombreAsc;
    private javax.swing.JButton jButtonOrdenarNombreDesc;
    private javax.swing.JButton jButtonOrdenarPrecioAsc;
    private javax.swing.JButton jButtonOrdenarPrecioDesc;
    private javax.swing.JComboBox<String> jComboBoxMarca;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelDiametroDisco;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelPotencia;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelVelocidad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldColor;
    private javax.swing.JTextField jTextFieldDiametroDisco;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPeso;
    private javax.swing.JTextField jTextFieldPotencia;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldTipo;
    private javax.swing.JTextField jTextFieldVelocidad;
    private javax.swing.JLabel jlogo;
    private javax.swing.JPanel panelImagen;
    // End of variables declaration//GEN-END:variables
}
