/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaGUI;

import controlador.ManejadorObjetos;
import controlador.ManejadorRaquetas;
import controladorDB.ManejadorMarcasDB;
import controladorDB.ManejadorRaquetaBD;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import modelo.CategoriaDeportivos;
import modelo.Marca;
import modelo.Raquetas;

/**
 *
 * @author danie
 */
public class MenuRaquetasInter extends javax.swing.JFrame {

    /**
     * Creates new form MenuRaquetasInter
     */
    ManejadorObjetos manobj;
    ManejadorRaquetas manraq;
    ManejadorMarcasDB manmarDB;
    ManejadorRaquetaBD manraqBD;
    Integer idMarcaTemporal = null;
    String nombreMarcaTemporal = "";
    DefaultTableModel model;
    int indiceFila = 0;
    String[] dato = new String[9];
    JFileChooser fileChooser = new JFileChooser();
    ImageIcon image = null;
    File archivo = null;
    String ruta = "E:\\daniel\\Descargas\\graySquare.jpeg";
    JLabel labelImagen = new JLabel("", new ImageIcon(ruta), JLabel.CENTER);

    public MenuRaquetasInter() {
        initComponents();
        this.setLocationRelativeTo(null);
        manobj = new ManejadorObjetos();
        manraq = new ManejadorRaquetas();
        manmarDB = new ManejadorMarcasDB();
        manraqBD = new ManejadorRaquetaBD();
        model = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int column) {
                switch (column) {
                    case 10:
                        return ImageIcon.class;
                    default:
                        return String.class;
                }
            }
        };;
        model.addColumn("Id");
        model.addColumn("Nombre Marca");
        model.addColumn("Nombre");
        model.addColumn("Cantidad");
        model.addColumn("Precio");
        model.addColumn("Color");
        model.addColumn("Tipo Marco");
        model.addColumn("Longitud");
        model.addColumn("Ancho");
        model.addColumn("Peso");
        model.addColumn("Imagen");
        jTable1.setModel(model);
        jTable1.getColumnModel().getColumn(0).setMinWidth(30);
        jTable1.getColumnModel().getColumn(10).setMinWidth(150);
        model.insertRow(indiceFila, dato);
        inicializarComboBox();
        fileChooser.setAcceptAllFileFilterUsed(false);
        FileFilter imageFilter = new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());
        fileChooser.addChoosableFileFilter(imageFilter);
        panelImagen.setPreferredSize(new Dimension(132, 132));
        panelImagen.add(labelImagen, BorderLayout.CENTER);
        jTable1.setRowHeight(150);
        jTable1.setRowMargin(5);
    }

//    public void inicializarComboBox() {
//        for (int i = 0; i < manobj.arregloMarcas.size(); i++) {
//            jComboBoxMarca.addItem(manobj.arregloMarcas.get(i).getDescripcion());
//        }
//    }
    public void inicializarComboBox() {
        manmarDB.consultarTodos();
        for (int i = 0; i < ManejadorObjetos.arregloMarcas.size(); i++) {
            jComboBoxMarca.addItem(ManejadorObjetos.arregloMarcas.get(i).getDescripcion());
        }
    }

    public void limpiar() {
        jTextFieldId.setText("");
        jTextFieldNombre.setText("");
        jTextFieldCantidad.setText("");
        jTextFieldPrecio.setText("");
        jTextFieldColor.setText("");
        jTextFieldMarco.setText("");
        jTextFieldLongitud.setText("");
        jTextFieldAncho.setText("");
        jTextFieldPeso.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConsultarUno = new javax.swing.JButton();
        jButtonConsultarTodo = new javax.swing.JButton();
        jLabelLongitud = new javax.swing.JLabel();
        jButtonBorrarUno = new javax.swing.JButton();
        jLabelAncho = new javax.swing.JLabel();
        jButtonBorrarTodos = new javax.swing.JButton();
        jLabelPeso = new javax.swing.JLabel();
        jButtonInsertar = new javax.swing.JButton();
        jTextFieldId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBoxMarca = new javax.swing.JComboBox<>();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelMensaje = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldMarco = new javax.swing.JTextField();
        jTextFieldLongitud = new javax.swing.JTextField();
        jTextFieldAncho = new javax.swing.JTextField();
        jTextFieldPeso = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelColor = new javax.swing.JLabel();
        jButtonModificar = new javax.swing.JButton();
        jTextFieldColor = new javax.swing.JTextField();
        jLabelMarco = new javax.swing.JLabel();
        jButtonOrdenarNombreAsc = new javax.swing.JButton();
        jButtonOrdenarPrecioAsc = new javax.swing.JButton();
        jButtonOrdenarNombreDesc = new javax.swing.JButton();
        jButtonOrdenarPrecioDesc = new javax.swing.JButton();
        jButtonOrdenarID = new javax.swing.JButton();
        panelImagen = new javax.swing.JPanel();
        botonFileChooser = new javax.swing.JButton();

        setTitle("Raquetas");

        jButtonConsultarUno.setText("Consultar Uno");
        jButtonConsultarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarUnoActionPerformed(evt);
            }
        });

        jButtonConsultarTodo.setText("Consultar Todo");
        jButtonConsultarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarTodoActionPerformed(evt);
            }
        });

        jLabelLongitud.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLongitud.setText("Longitud");

        jButtonBorrarUno.setText("Borrar Uno");
        jButtonBorrarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarUnoActionPerformed(evt);
            }
        });

        jLabelAncho.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAncho.setText("Ancho");

        jButtonBorrarTodos.setText("Borrar Todos");
        jButtonBorrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTodosActionPerformed(evt);
            }
        });

        jLabelPeso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPeso.setText("Peso");

        jButtonInsertar.setText("Insertar");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jComboBoxMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMarcaItemStateChanged(evt);
            }
        });
        jComboBoxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMarcaActionPerformed(evt);
            }
        });

        jLabelMensaje.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMensaje.setText("Estado");

        jTextFieldMarco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMarcoActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI Historic", 3, 36)); // NOI18N
        jLabelTitulo.setText("Raquetas");

        jLabelId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId.setText("ID");

        jLabelMarca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMarca.setText("Marca");

        jLabelCantidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCantidad.setText("Cantidad");

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNombre.setText("Nombre");

        jLabelPrecio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPrecio.setText("Precio");

        jLabelColor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelColor.setText("Color");

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jLabelMarco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMarco.setText("Tipo Marco");

        jButtonOrdenarNombreAsc.setText("Ordenar Nombre Ascendente");
        jButtonOrdenarNombreAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNombreAscActionPerformed(evt);
            }
        });

        jButtonOrdenarPrecioAsc.setText("Ordenar Precio Ascendente");
        jButtonOrdenarPrecioAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPrecioAscActionPerformed(evt);
            }
        });

        jButtonOrdenarNombreDesc.setText("Ordenar Nombre Descendente");
        jButtonOrdenarNombreDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNombreDescActionPerformed(evt);
            }
        });

        jButtonOrdenarPrecioDesc.setText("Ordenar Precio Descendente");
        jButtonOrdenarPrecioDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPrecioDescActionPerformed(evt);
            }
        });

        jButtonOrdenarID.setText("Ordenar ID");
        jButtonOrdenarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarIDActionPerformed(evt);
            }
        });

        panelImagen.setBackground(new java.awt.Color(204, 204, 204));
        panelImagen.setLayout(new java.awt.BorderLayout());

        botonFileChooser.setText("Examinar...");
        botonFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelId)
                                    .addComponent(jLabelMarca)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jLabelCantidad)
                                    .addComponent(jLabelPrecio))
                                .addGap(45, 45, 45))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelColor)
                                .addGap(48, 48, 48)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxMarca, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPrecio)
                            .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonFileChooser)
                                .addGap(67, 67, 67))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMarco)
                                    .addComponent(jLabelLongitud)
                                    .addComponent(jLabelAncho)
                                    .addComponent(jLabelPeso))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldAncho, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldLongitud, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMarco, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPeso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                                .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonOrdenarNombreDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonOrdenarNombreAsc, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonOrdenarPrecioDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonOrdenarPrecioAsc, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(jButtonOrdenarID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonConsultarUno)
                    .addComponent(jButtonConsultarTodo)
                    .addComponent(jButtonBorrarUno)
                    .addComponent(jButtonBorrarTodos)
                    .addComponent(jButtonInsertar))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelId)
                                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelMarca)
                                            .addComponent(jComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelNombre)
                                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelCantidad)
                                            .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelMarco)
                                            .addComponent(jTextFieldMarco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelLongitud)
                                            .addComponent(jTextFieldLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelAncho)
                                            .addComponent(jTextFieldAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelPeso)
                                            .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelPrecio)
                                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelColor)
                                    .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(botonFileChooser)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonOrdenarNombreAsc)
                                    .addComponent(jButtonOrdenarPrecioAsc))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonOrdenarNombreDesc)
                                    .addComponent(jButtonOrdenarPrecioDesc)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonOrdenarID)
                                .addGap(16, 16, 16)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonInsertar)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonModificar)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonConsultarUno)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonConsultarTodo)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonBorrarUno)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBorrarTodos)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarTodoActionPerformed
        manraqBD.consultarTodos();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaDeportivos.arregloraquetas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getTipomarco(), indiceFila, 6);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getLongitud(), indiceFila, 7);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getAncho(), indiceFila, 8);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getPeso(), indiceFila, 9);
            jTable1.setValueAt(new ImageIcon(CategoriaDeportivos.arregloraquetas.get(i).getImagen()), indiceFila, 10);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonConsultarTodoActionPerformed

    private void jTextFieldMarcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMarcoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMarcoActionPerformed

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
        Raquetas raque = new Raquetas();

        try {
            if (!ValidaEnteros.validaEnteros(jTextFieldId.getText())) {
                throw new ValidaEnteros();
            }
            if (!ValidaCantidad.validaCantidad(jTextFieldCantidad.getText())) {
                throw new ValidaCantidad();
            }
            if (!ValidaFlotantes.validaFlotantes(jTextFieldPrecio.getText())) {
                throw new ValidaFlotantes();
            }
            if (!ValidaLongitud.validaLongitud(jTextFieldLongitud.getText())) {
                throw new ValidaLongitud();
            }
            if (!ValidaAncho.validaAncho(jTextFieldAncho.getText())) {
                throw new ValidaAncho();
            }
            if (!ValidaPesoR.validaPesoR(jTextFieldPeso.getText())) {
                throw new ValidaPesoR();
            }
        } catch (ValidaEnteros e) {
            jLabelMensaje.setText("El id que ingreso no es valido");
            jTextFieldId.setText("");
            return;
        } catch (ValidaCantidad e) {
            jLabelMensaje.setText("La cantidad que ingreso no es valida");
            jTextFieldCantidad.setText("");
            return;
        } catch (ValidaFlotantes e) {
            jLabelMensaje.setText("El precio que ingreso no es valido");
            jTextFieldPrecio.setText("");
            return;
        } catch (ValidaLongitud e) {
            jLabelMensaje.setText("La longitud que ingreso no es valida");
            jTextFieldLongitud.setText("");
            return;
        } catch (ValidaAncho e) {
            jLabelMensaje.setText("El ancho que ingreso no es valida");
            jTextFieldAncho.setText("");
            return;
        } catch (ValidaPesoR e) {
            jLabelMensaje.setText("El peso que ingreso no es valido");
            jTextFieldPeso.setText("");
            return;
        }

        Marca mar = new Marca();
        raque.setIdArticulo(Integer.parseInt(jTextFieldId.getText()));
        mar.setId(idMarcaTemporal);
        mar.setDescripcion(nombreMarcaTemporal);
        raque.setMar(mar);
        raque.setNombre(jTextFieldNombre.getText());
        raque.setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
        raque.setPrecio(Float.parseFloat(jTextFieldPrecio.getText()));
        raque.setColor(jTextFieldColor.getText());
        raque.setImagen(ruta);
        raque.setTipomarco(jTextFieldMarco.getText());
        raque.setLongitud(Integer.parseInt(jTextFieldLongitud.getText()));
        raque.setAncho(Float.parseFloat(jTextFieldAncho.getText()));
        raque.setPeso(Float.parseFloat(jTextFieldPeso.getText()));

        if (manraqBD.insertar(raque)) {
            jLabelMensaje.setText("El articulo " + jTextFieldNombre.getText() + " se insertó correctamente");
            //JOptionPane.showMessageDialog(this, "El articulo " + jTextFieldNombre.getText() + " se insertó correctamente");
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(jTextFieldId.getText(), indiceFila, 0);
            jTable1.setValueAt(nombreMarcaTemporal, indiceFila, 1);
            jTable1.setValueAt(jTextFieldNombre.getText(), indiceFila, 2);
            jTable1.setValueAt(jTextFieldCantidad.getText(), indiceFila, 3);
            jTable1.setValueAt(jTextFieldPrecio.getText(), indiceFila, 4);
            jTable1.setValueAt(jTextFieldColor.getText(), indiceFila, 5);
            jTable1.setValueAt(jTextFieldMarco.getText(), indiceFila, 6);
            jTable1.setValueAt(jTextFieldLongitud.getText(), indiceFila, 7);
            jTable1.setValueAt(jTextFieldAncho.getText(), indiceFila, 8);
            jTable1.setValueAt(jTextFieldPeso.getText(), indiceFila, 9);
            jTable1.setValueAt(ruta, indiceFila, 10);
            jTable1.setValueAt(new ImageIcon(ruta), indiceFila, 10);
            ruta = "E:\\daniel\\Descargas\\graySquare.jpeg";
            image = new ImageIcon(ruta);
            labelImagen.setIcon(image);
            indiceFila++;
            manraqBD.consultarTodos();
        } else {
            jLabelMensaje.setText("Error al insertar");
            //JOptionPane.showMessageDialog(this, "Error al insertar");
        }

        limpiar();
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        System.out.println(filaSeleccionada);

        if (filaSeleccionada >= 0) {

            Raquetas raqmod = new Raquetas();
            int a = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            jTextFieldId.setText(jTable1.getValueAt(filaSeleccionada, 0).toString());
            //int idMarcaMod = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 1).toString());
            String nombreMarcaMod = jTable1.getValueAt(filaSeleccionada, 1).toString();
            jTextFieldNombre.setText(jTable1.getValueAt(filaSeleccionada, 2).toString());
            jTextFieldCantidad.setText(jTable1.getValueAt(filaSeleccionada, 3).toString());
            jTextFieldPrecio.setText(jTable1.getValueAt(filaSeleccionada, 4).toString());
            jTextFieldColor.setText(jTable1.getValueAt(filaSeleccionada, 5).toString());
            jTextFieldMarco.setText(jTable1.getValueAt(filaSeleccionada, 6).toString());
            jTextFieldLongitud.setText(jTable1.getValueAt(filaSeleccionada, 7).toString());
            jTextFieldAncho.setText(jTable1.getValueAt(filaSeleccionada, 8).toString());
            jTextFieldPeso.setText(jTable1.getValueAt(filaSeleccionada, 9).toString());
            String img = jTable1.getValueAt(filaSeleccionada, 10).toString();
            try {
                if (!ValidaCantidad.validaCantidad(jTextFieldCantidad.getText())) {
                    throw new ValidaCantidad();
                }
                if (!ValidaFlotantes.validaFlotantes(jTextFieldPrecio.getText())) {
                    throw new ValidaFlotantes();
                }
                if (!ValidaLongitud.validaLongitud(jTextFieldLongitud.getText())) {
                    throw new ValidaLongitud();
                }
                if (!ValidaAncho.validaAncho(jTextFieldAncho.getText())) {
                    throw new ValidaAncho();
                }
                if (!ValidaPesoR.validaPesoR(jTextFieldPeso.getText())) {
                    throw new ValidaPesoR();
                }
            } catch (ValidaCantidad e) {
                jLabelMensaje.setText("La cantidad que ingreso no es valida");
                jTextFieldCantidad.setText("");
                return;
            } catch (ValidaFlotantes e) {
                jLabelMensaje.setText("El precio que ingreso no es valido");
                jTextFieldPrecio.setText("");
                return;
            } catch (ValidaLongitud e) {
                jLabelMensaje.setText("La longitud que ingreso no es valida");
                jTextFieldLongitud.setText("");
                return;
            } catch (ValidaAncho e) {
                jLabelMensaje.setText("El ancho que ingreso no es valida");
                jTextFieldAncho.setText("");
                return;
            } catch (ValidaPesoR e) {
                jLabelMensaje.setText("El peso que ingreso no es valido");
                jTextFieldPeso.setText("");
                return;
            }

            Marca marmod = new Marca();
            raqmod.setIdArticulo(Integer.parseInt(jTextFieldId.getText()));
            marmod.setId(a);
            marmod.setDescripcion(nombreMarcaMod);
            raqmod.setMar(marmod);
            raqmod.setNombre(jTextFieldNombre.getText());
            raqmod.setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
            raqmod.setPrecio(Float.parseFloat(jTextFieldPrecio.getText()));
            raqmod.setColor(jTextFieldColor.getText());
            raqmod.setTipomarco(jTextFieldMarco.getText());
            raqmod.setLongitud(Integer.parseInt(jTextFieldLongitud.getText()));
            raqmod.setAncho(Float.parseFloat(jTextFieldAncho.getText()));
            raqmod.setPeso(Float.parseFloat(jTextFieldPeso.getText()));
            raqmod.setImagen(img);
            //Marca marmod = new Marca(Integer.parseInt(jTextFieldId.getText()), jTextFieldMarca.getText());
//            int posicion = manraq.busquedaBinaria(a);
//            if (!(posicion == -1)) {
//                if (manraq.modificar(posicion, raqmod)) {
//                    JOptionPane.showMessageDialog(this, "Raqueta modificada exitosamente");
//                    indiceFila--;
//                }
//            } else {
//                JOptionPane.showMessageDialog(this, "Error al modificar");
//            }

            if (manraqBD.modificar(a, raqmod)) {
                JOptionPane.showMessageDialog(this, "Raqueta modificada exitosamente");
                indiceFila--;
                manraqBD.consultarTodos();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error al modificar");
        }

        limpiar();

    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonConsultarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarUnoActionPerformed
//        int idBuscado = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el ID a buscar"));
//
//        Raquetas resultado = (Raquetas) manraq.consultarId(idBuscado);
//        if (resultado == null) {
//            JOptionPane.showMessageDialog(this, "Raqueta no encontrada");
//        } else {
//            JOptionPane.showMessageDialog(this, "La raqueta encontrada es:\n" + resultado.toString());
//        }
        try {
            int idBuscado = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el ID a buscar"));
            Raquetas resultado = (Raquetas) manraqBD.consultarId(idBuscado);
            JOptionPane.showMessageDialog(this, "La raqueta encontrada es:\n" + resultado.toString());
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Raqueta no encontrada");

        }
    }//GEN-LAST:event_jButtonConsultarUnoActionPerformed

    private void jButtonBorrarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarUnoActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada >= 0) {
            int idEliminar = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            model.removeRow(filaSeleccionada);
            if (manraqBD.borrar(idEliminar)) {
                JOptionPane.showMessageDialog(this, "Raqueta borrada exitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Error al borrar");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar");
        }

    }//GEN-LAST:event_jButtonBorrarUnoActionPerformed

    private void jButtonBorrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTodosActionPerformed
        if (manraqBD.borrarTodo()) {
            while (model.getRowCount() > 0) {
                model.removeRow(0);
            }
            indiceFila = 0;
            JOptionPane.showMessageDialog(this, "Todos las raquetas se borraron exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar todo");
        }
    }//GEN-LAST:event_jButtonBorrarTodosActionPerformed

    private void jComboBoxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMarcaActionPerformed


    }//GEN-LAST:event_jComboBoxMarcaActionPerformed

    private void jComboBoxMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMarcaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (jComboBoxMarca.getItemCount() > 0) {
                idMarcaTemporal = ManejadorObjetos.arregloMarcas.get(jComboBoxMarca.getSelectedIndex()).getId();
                nombreMarcaTemporal = ManejadorObjetos.arregloMarcas.get(jComboBoxMarca.getSelectedIndex()).getDescripcion();
            }
        }
    }//GEN-LAST:event_jComboBoxMarcaItemStateChanged

    private void jButtonOrdenarNombreAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNombreAscActionPerformed
        manraq.ordenarMezcla();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaDeportivos.arregloraquetas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getTipomarco(), indiceFila, 6);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getLongitud(), indiceFila, 7);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getAncho(), indiceFila, 8);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getPeso(), indiceFila, 9);
            jTable1.setValueAt(new ImageIcon(CategoriaDeportivos.arregloraquetas.get(i).getImagen()), indiceFila, 10);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarNombreAscActionPerformed

    private void jButtonOrdenarPrecioAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPrecioAscActionPerformed
        manraq.quicksort();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaDeportivos.arregloraquetas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getTipomarco(), indiceFila, 6);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getLongitud(), indiceFila, 7);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getAncho(), indiceFila, 8);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getPeso(), indiceFila, 9);
            jTable1.setValueAt(new ImageIcon(CategoriaDeportivos.arregloraquetas.get(i).getImagen()), indiceFila, 10);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarPrecioAscActionPerformed

    private void jButtonOrdenarNombreDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNombreDescActionPerformed
        manraq.ordenarMezclaDesc();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaDeportivos.arregloraquetas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getTipomarco(), indiceFila, 6);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getLongitud(), indiceFila, 7);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getAncho(), indiceFila, 8);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getPeso(), indiceFila, 9);
            jTable1.setValueAt(new ImageIcon(CategoriaDeportivos.arregloraquetas.get(i).getImagen()), indiceFila, 10);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarNombreDescActionPerformed

    private void jButtonOrdenarPrecioDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPrecioDescActionPerformed
        manraq.quicksortDesc();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaDeportivos.arregloraquetas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getTipomarco(), indiceFila, 6);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getLongitud(), indiceFila, 7);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getAncho(), indiceFila, 8);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getPeso(), indiceFila, 9);
            jTable1.setValueAt(new ImageIcon(CategoriaDeportivos.arregloraquetas.get(i).getImagen()), indiceFila, 10);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarPrecioDescActionPerformed

    private void jButtonOrdenarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarIDActionPerformed
        manraq.sort();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaDeportivos.arregloraquetas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getTipomarco(), indiceFila, 6);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getLongitud(), indiceFila, 7);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getAncho(), indiceFila, 8);
            jTable1.setValueAt(CategoriaDeportivos.arregloraquetas.get(i).getPeso(), indiceFila, 9);
            jTable1.setValueAt(new ImageIcon(CategoriaDeportivos.arregloraquetas.get(i).getImagen()), indiceFila, 10);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarIDActionPerformed

    private void botonFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFileChooserActionPerformed
        fileChooser.showDialog(this, "Choose"); //
        archivo = fileChooser.getSelectedFile();
        ruta = archivo.getAbsolutePath();
        image = new ImageIcon(ruta);
        labelImagen.setIcon(image);
    }//GEN-LAST:event_botonFileChooserActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuRaquetasInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuRaquetasInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuRaquetasInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuRaquetasInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuRaquetasInter().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonFileChooser;
    private javax.swing.JButton jButtonBorrarTodos;
    private javax.swing.JButton jButtonBorrarUno;
    private javax.swing.JButton jButtonConsultarTodo;
    private javax.swing.JButton jButtonConsultarUno;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonOrdenarID;
    private javax.swing.JButton jButtonOrdenarNombreAsc;
    private javax.swing.JButton jButtonOrdenarNombreDesc;
    private javax.swing.JButton jButtonOrdenarPrecioAsc;
    private javax.swing.JButton jButtonOrdenarPrecioDesc;
    private javax.swing.JComboBox<String> jComboBoxMarca;
    private javax.swing.JLabel jLabelAncho;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelLongitud;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelMarco;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldAncho;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldColor;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldLongitud;
    private javax.swing.JTextField jTextFieldMarco;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPeso;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JPanel panelImagen;
    // End of variables declaration//GEN-END:variables
}
