/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaGUI;

import controlador.ManejadorMartillos;
import controlador.ManejadorObjetos;
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.CategoriaHerramientas;
import modelo.Marca;
import modelo.Martillos;

/**
 *
 * @author Daniel
 */
public class MenuMartillosInter extends javax.swing.JFrame {

    /**
     * Creates new form MenuMartillosInter
     */
    ManejadorObjetos manobj;
    ManejadorMartillos manmart;
    Integer idMarcaTemporal = null;
    String nombreMarcaTemporal = "";
    DefaultTableModel model;
    int indiceFila = 0;
    String[] dato = new String[11];

    public MenuMartillosInter() {
        initComponents();
        this.setLocationRelativeTo(null);
        manobj = new ManejadorObjetos();
        manmart = new ManejadorMartillos();
        model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Nombre Marca");
        model.addColumn("Nombre");
        model.addColumn("Cantidad");
        model.addColumn("Precio");
        model.addColumn("Color");
        model.addColumn("Tipo Martillo");
        model.addColumn("Material Mango");
        model.addColumn("Material Cabezal");
        model.addColumn("Peso Martillo");
        model.addColumn("Tamaño Martillo");
        jTable1.setModel(model);
        model.insertRow(indiceFila, dato);
        inicializarComboBox();
    }

    public void inicializarComboBox() {
        for (int i = 0; i < manobj.arregloMarcas.size(); i++) {
            jComboBoxMarca.addItem(manobj.arregloMarcas.get(i).getDescripcion());
        }
    }

    public void limpiar() {
        jTextFieldId.setText("");
        jTextFieldNombre.setText("");
        jTextFieldCantidad.setText("");
        jTextFieldPrecio.setText("");
        jTextFieldColor.setText("");
        jTextFieldUrl.setText("");
        jTextFieldTipoMartillo.setText("");
        jTextFieldMaterialMango.setText("");
        jTextFieldMaterialCabezal.setText("");
        jTextFieldPesoMartillo.setText("");
        jTextFieldTamañoMartillo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMarca = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelTamañoMartillo = new javax.swing.JLabel();
        jLabelUrl = new javax.swing.JLabel();
        jTextFieldTamañoMartillo = new javax.swing.JTextField();
        jLabelColor = new javax.swing.JLabel();
        jTextFieldColor = new javax.swing.JTextField();
        jLabelTipoMartillo = new javax.swing.JLabel();
        jLabelMaterialMango = new javax.swing.JLabel();
        jLabelMaterialCabezal = new javax.swing.JLabel();
        jLabelPesoMartillo = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jComboBoxMarca = new javax.swing.JComboBox<>();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldCantidad = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldUrl = new javax.swing.JTextField();
        jTextFieldTipoMartillo = new javax.swing.JTextField();
        jTextFieldMaterialMango = new javax.swing.JTextField();
        jTextFieldMaterialCabezal = new javax.swing.JTextField();
        jTextFieldPesoMartillo = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jButtonBorrarUno = new javax.swing.JButton();
        jButtonBorrarTodos = new javax.swing.JButton();
        jButtonInsertar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonConsultarUno = new javax.swing.JButton();
        jButtonConsultarTodo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelMensaje = new javax.swing.JLabel();
        jButtonOrdenarID = new javax.swing.JButton();
        jButtonOrdenarNombreAsc = new javax.swing.JButton();
        jButtonOrdenarPrecioAsc = new javax.swing.JButton();
        jButtonOrdenarNombreDesc = new javax.swing.JButton();
        jButtonOrdenarPrecioDesc = new javax.swing.JButton();

        setTitle("Martillos");

        jLabelMarca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMarca.setText("Marca");

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNombre.setText("Nombre");

        jLabelPrecio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPrecio.setText("Precio");

        jLabelTamañoMartillo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTamañoMartillo.setText("Tamaño Martillo");

        jLabelUrl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelUrl.setText("Url");

        jLabelColor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelColor.setText("Color");

        jLabelTipoMartillo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTipoMartillo.setText("Tipo Martillo");

        jLabelMaterialMango.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMaterialMango.setText("Material Mango");

        jLabelMaterialCabezal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMaterialCabezal.setText("Material Cabezal");

        jLabelPesoMartillo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPesoMartillo.setText("Peso Martillo");

        jComboBoxMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMarcaItemStateChanged(evt);
            }
        });

        jTextFieldTipoMartillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoMartilloActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI Historic", 3, 36)); // NOI18N
        jLabelTitulo.setText("Martillos");

        jLabelId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId.setText("ID");

        jLabelCantidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCantidad.setText("Cantidad");

        jButtonBorrarUno.setText("Borrar Uno");
        jButtonBorrarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarUnoActionPerformed(evt);
            }
        });

        jButtonBorrarTodos.setText("Borrar Todos");
        jButtonBorrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTodosActionPerformed(evt);
            }
        });

        jButtonInsertar.setText("Insertar");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonConsultarUno.setText("Consultar Uno");
        jButtonConsultarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarUnoActionPerformed(evt);
            }
        });

        jButtonConsultarTodo.setText("Consultar Todo");
        jButtonConsultarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarTodoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabelMensaje.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMensaje.setText("Estado");

        jButtonOrdenarID.setText("Ordenar ID");
        jButtonOrdenarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarIDActionPerformed(evt);
            }
        });

        jButtonOrdenarNombreAsc.setText("Ordenar Nombre Ascendente");
        jButtonOrdenarNombreAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNombreAscActionPerformed(evt);
            }
        });

        jButtonOrdenarPrecioAsc.setText("Ordenar Precio Ascendente");
        jButtonOrdenarPrecioAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPrecioAscActionPerformed(evt);
            }
        });

        jButtonOrdenarNombreDesc.setText("Ordenar Nombre Descendente");
        jButtonOrdenarNombreDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNombreDescActionPerformed(evt);
            }
        });

        jButtonOrdenarPrecioDesc.setText("Ordenar Precio Descendente");
        jButtonOrdenarPrecioDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPrecioDescActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelId)
                                    .addComponent(jLabelMarca)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jLabelCantidad)
                                    .addComponent(jLabelPrecio))
                                .addGap(45, 45, 45))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelColor)
                                .addGap(48, 48, 48)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxMarca, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPrecio)
                            .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUrl)
                            .addComponent(jLabelTipoMartillo)
                            .addComponent(jLabelMaterialMango)
                            .addComponent(jLabelMaterialCabezal)
                            .addComponent(jLabelPesoMartillo)
                            .addComponent(jLabelTamañoMartillo))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldMaterialCabezal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMaterialMango, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTipoMartillo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldUrl, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPesoMartillo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTamañoMartillo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonOrdenarNombreAsc)
                            .addComponent(jButtonOrdenarNombreDesc))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonOrdenarPrecioDesc)
                            .addComponent(jButtonOrdenarPrecioAsc))
                        .addGap(40, 40, 40)
                        .addComponent(jButtonOrdenarID)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonConsultarUno)
                    .addComponent(jButtonConsultarTodo)
                    .addComponent(jButtonBorrarUno)
                    .addComponent(jButtonBorrarTodos)
                    .addComponent(jButtonInsertar))
                .addGap(18, 18, 18))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButtonInsertar)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonModificar)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonConsultarUno)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonConsultarTodo)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonBorrarUno))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelId)
                                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelMarca)
                                    .addComponent(jComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelCantidad)
                                    .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelPrecio)
                                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelColor)
                                    .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelUrl)
                                    .addComponent(jTextFieldUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelTipoMartillo)
                                    .addComponent(jTextFieldTipoMartillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelMaterialMango)
                                    .addComponent(jTextFieldMaterialMango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelMaterialCabezal)
                                    .addComponent(jTextFieldMaterialCabezal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelPesoMartillo)
                                    .addComponent(jTextFieldPesoMartillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelTamañoMartillo)
                                    .addComponent(jTextFieldTamañoMartillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(10, 10, 10)
                .addComponent(jButtonBorrarTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonOrdenarNombreAsc)
                            .addComponent(jButtonOrdenarPrecioAsc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonOrdenarNombreDesc)
                            .addComponent(jButtonOrdenarPrecioDesc)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonOrdenarID)
                        .addGap(16, 16, 16)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTipoMartilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoMartilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoMartilloActionPerformed

    private void jButtonConsultarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarTodoActionPerformed

        manmart.consultarTodos();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaHerramientas.arreglomartillos.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getMatmango(), indiceFila, 7);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getMatcabezal(), indiceFila, 8);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getPeso(), indiceFila, 9);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getTamaño(), indiceFila, 10);
            indiceFila++;
        }

    }//GEN-LAST:event_jButtonConsultarTodoActionPerformed

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed

        Martillos mart = new Martillos();

        try {
            if (!ValidaEnteros.validaEnteros(jTextFieldId.getText())) {
                throw new ValidaEnteros();
            }
            if (!ValidaCantidad.validaCantidad(jTextFieldCantidad.getText())) {
                throw new ValidaCantidad();
            }
            if (!ValidaFlotantes.validaFlotantes(jTextFieldPrecio.getText())) {
                throw new ValidaFlotantes();
            }
            if (!ValidaPeso.validaPeso(jTextFieldPesoMartillo.getText())) {
                throw new ValidaPeso();
            }
            if (!ValidaTamRueda.validaTamRueda(jTextFieldTamañoMartillo.getText())) {
                throw new ValidaTamRueda();
            }
        } catch (ValidaEnteros e) {
            jLabelMensaje.setText("El id que ingreso no es valido");
            jTextFieldId.setText("");
            return;
        } catch (ValidaCantidad e) {
            jLabelMensaje.setText("La cantidad que ingreso no es valida");
            jTextFieldCantidad.setText("");
            return;
        } catch (ValidaFlotantes e) {
            jLabelMensaje.setText("El precio que ingreso no es valido");
            jTextFieldPrecio.setText("");
            return;
        } catch (ValidaPeso e) {
            jLabelMensaje.setText("El peso de martillo que ingreso no es valido");
            jTextFieldPesoMartillo.setText("");
            return;
        } catch (ValidaTamRueda e) {
            jLabelMensaje.setText("El tamaño del martillo que ingreso no es valido");
            jTextFieldTamañoMartillo.setText("");
            return;
        }
        Marca mar = new Marca();
        mart.setIdArticulo(Integer.parseInt(jTextFieldId.getText()));
        mar.setId(idMarcaTemporal);
        mar.setDescripcion(nombreMarcaTemporal);
        mart.setMar(mar);
        mart.setNombre(jTextFieldNombre.getText());
        mart.setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
        mart.setPrecio(Float.parseFloat(jTextFieldPrecio.getText()));
        mart.setColor(jTextFieldColor.getText());
        mart.setTipo(jTextFieldTipoMartillo.getText());
        mart.setMatmango(jTextFieldMaterialMango.getText());
        mart.setMatcabezal(jTextFieldMaterialCabezal.getText());
        mart.setPeso(Integer.parseInt(jTextFieldPesoMartillo.getText()));
        mart.setTamaño(jTextFieldTamañoMartillo.getText());

        if (manmart.insertar(mart)) {
            jLabelMensaje.setText("El articulo " + jTextFieldNombre.getText() + " se insertó correctamente");
            //JOptionPane.showMessageDialog(this, "El articulo " + jTextFieldNombre.getText() + " se insertó correctamente");
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(jTextFieldId.getText(), indiceFila, 0);
            jTable1.setValueAt(nombreMarcaTemporal, indiceFila, 1);
            jTable1.setValueAt(jTextFieldNombre.getText(), indiceFila, 2);
            jTable1.setValueAt(jTextFieldCantidad.getText(), indiceFila, 3);
            jTable1.setValueAt(Float.parseFloat(jTextFieldPrecio.getText()), indiceFila, 4);
            jTable1.setValueAt(jTextFieldColor.getText(), indiceFila, 5);
            jTable1.setValueAt(jTextFieldTipoMartillo.getText(), indiceFila, 6);
            jTable1.setValueAt(jTextFieldMaterialMango.getText(), indiceFila, 7);
            jTable1.setValueAt(jTextFieldMaterialCabezal.getText(), indiceFila, 8);
            jTable1.setValueAt(Integer.parseInt(jTextFieldPesoMartillo.getText()), indiceFila, 9);
            jTable1.setValueAt(jTextFieldTamañoMartillo.getText(), indiceFila, 10);
            indiceFila++;
            manmart.consultarTodos();
        } else {
            jLabelMensaje.setText("Error al insertar");
            //JOptionPane.showMessageDialog(this, "Error al insertar");
        }
        limpiar();
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed

        int filaSeleccionada = jTable1.getSelectedRow();
        System.out.println(filaSeleccionada);

        if (filaSeleccionada >= 0) {

            Martillos martmod = new Martillos();
            int a = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            jTextFieldId.setText(jTable1.getValueAt(filaSeleccionada, 0).toString());
            String nombreMarcaMod = jTable1.getValueAt(filaSeleccionada, 1).toString();
            jTextFieldNombre.setText(jTable1.getValueAt(filaSeleccionada, 2).toString());
            jTextFieldCantidad.setText(jTable1.getValueAt(filaSeleccionada, 3).toString());
            jTextFieldPrecio.setText(jTable1.getValueAt(filaSeleccionada, 4).toString());
            jTextFieldColor.setText(jTable1.getValueAt(filaSeleccionada, 5).toString());
            jTextFieldTipoMartillo.setText(jTable1.getValueAt(filaSeleccionada, 6).toString());
            jTextFieldMaterialMango.setText(jTable1.getValueAt(filaSeleccionada, 7).toString());
            jTextFieldMaterialCabezal.setText(jTable1.getValueAt(filaSeleccionada, 8).toString());
            jTextFieldPesoMartillo.setText(jTable1.getValueAt(filaSeleccionada, 9).toString());
            jTextFieldTamañoMartillo.setText(jTable1.getValueAt(filaSeleccionada, 10).toString());

            try {

                if (!ValidaCantidad.validaCantidad(jTextFieldCantidad.getText())) {
                    throw new ValidaCantidad();
                }
                if (!ValidaFlotantes.validaFlotantes(jTextFieldPrecio.getText())) {
                    throw new ValidaFlotantes();
                }
                if (!ValidaPeso.validaPeso(jTextFieldPesoMartillo.getText())) {
                    throw new ValidaPeso();
                }
                if (!ValidaTamRueda.validaTamRueda(jTextFieldTamañoMartillo.getText())) {
                    throw new ValidaTamRueda();
                }
            } catch (ValidaCantidad e) {
                jLabelMensaje.setText("La cantidad que ingreso no es valida");
                jTextFieldCantidad.setText("");
                return;
            } catch (ValidaFlotantes e) {
                jLabelMensaje.setText("El precio que ingreso no es valido");
                jTextFieldPrecio.setText("");
                return;
            } catch (ValidaPeso e) {
                jLabelMensaje.setText("El peso de martillo que ingreso no es valido");
                jTextFieldPesoMartillo.setText("");
                return;
            } catch (ValidaTamRueda e) {
                jLabelMensaje.setText("El tamaño del martillo que ingreso no es valido");
                jTextFieldTamañoMartillo.setText("");
                return;
            }

            Marca marmod = new Marca();
            martmod.setIdArticulo(Integer.parseInt(jTextFieldId.getText()));
            marmod.setId(a);
            marmod.setDescripcion(nombreMarcaMod);
            martmod.setMar(marmod);
            martmod.setNombre(jTextFieldNombre.getText());
            martmod.setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
            martmod.setPrecio(Float.parseFloat(jTextFieldPrecio.getText()));
            martmod.setColor(jTextFieldColor.getText());
            martmod.setTipo(jTextFieldTipoMartillo.getText());
            martmod.setMatmango(jTextFieldMaterialMango.getText());
            martmod.setTipo(jTextFieldMaterialCabezal.getText());
            martmod.setTipo(jTextFieldPesoMartillo.getText());
            martmod.setTipo(jTextFieldTamañoMartillo.getText());

            //Marca marmod = new Marca(Integer.parseInt(jTextFieldId.getText()), jTextFieldMarca.getText());
            int posicion = manmart.busquedaBinaria(a);
            if (!(posicion == -1)) {
                if (manmart.modificar(posicion, martmod)) {
                    JOptionPane.showMessageDialog(this, "Martillo modificado exitosamente");
                    indiceFila--;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar");
            }
        }

        limpiar();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonConsultarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarUnoActionPerformed

        int idBuscado = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el ID a buscar"));

        Martillos resultado = (Martillos) manmart.consultarId(idBuscado);
        if (resultado == null) {
            JOptionPane.showMessageDialog(this, "Martillo no encontrado");
        } else {
            JOptionPane.showMessageDialog(this, "El Martillo encontrado es:\n" + resultado.toString());
        }

    }//GEN-LAST:event_jButtonConsultarUnoActionPerformed

    private void jButtonBorrarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarUnoActionPerformed

        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada >= 0) {
            int idEliminar = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            model.removeRow(filaSeleccionada);
            if (manmart.borrar(idEliminar)) {
                JOptionPane.showMessageDialog(this, "Martillo borrado exitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Error al borrar");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar");
        }

    }//GEN-LAST:event_jButtonBorrarUnoActionPerformed

    private void jButtonBorrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTodosActionPerformed

        if (manmart.borrarTodo()) {
            while (model.getRowCount() > 0) {
                model.removeRow(0);
            }
            indiceFila = 0;
            JOptionPane.showMessageDialog(this, "Todos los Martillos se borraron exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar todo");
        }

    }//GEN-LAST:event_jButtonBorrarTodosActionPerformed

    private void jComboBoxMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMarcaItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (jComboBoxMarca.getItemCount() > 0) {
                idMarcaTemporal = ManejadorObjetos.arregloMarcas.get(jComboBoxMarca.getSelectedIndex()).getId();
                nombreMarcaTemporal = ManejadorObjetos.arregloMarcas.get(jComboBoxMarca.getSelectedIndex()).getDescripcion();
            }
        }

    }//GEN-LAST:event_jComboBoxMarcaItemStateChanged

    private void jButtonOrdenarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarIDActionPerformed
        manmart.sort();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaHerramientas.arreglomartillos.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getMatmango(), indiceFila, 7);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getMatcabezal(), indiceFila, 8);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getPeso(), indiceFila, 9);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getTamaño(), indiceFila, 10);
            indiceFila++;
        }

    }//GEN-LAST:event_jButtonOrdenarIDActionPerformed

    private void jButtonOrdenarNombreAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNombreAscActionPerformed
        manmart.ordenarMezcla();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaHerramientas.arreglomartillos.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getMatmango(), indiceFila, 7);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getMatcabezal(), indiceFila, 8);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getPeso(), indiceFila, 9);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getTamaño(), indiceFila, 10);
            indiceFila++;
        }

    }//GEN-LAST:event_jButtonOrdenarNombreAscActionPerformed

    private void jButtonOrdenarPrecioAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPrecioAscActionPerformed
        manmart.quicksort();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaHerramientas.arreglomartillos.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getMatmango(), indiceFila, 7);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getMatcabezal(), indiceFila, 8);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getPeso(), indiceFila, 9);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getTamaño(), indiceFila, 10);
            indiceFila++;
        }

    }//GEN-LAST:event_jButtonOrdenarPrecioAscActionPerformed

    private void jButtonOrdenarNombreDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNombreDescActionPerformed
        manmart.ordenarMezclaDesc();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaHerramientas.arreglomartillos.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getMatmango(), indiceFila, 7);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getMatcabezal(), indiceFila, 8);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getPeso(), indiceFila, 9);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getTamaño(), indiceFila, 10);
            indiceFila++;
        }

    }//GEN-LAST:event_jButtonOrdenarNombreDescActionPerformed

    private void jButtonOrdenarPrecioDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPrecioDescActionPerformed
        manmart.quicksortDesc();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaHerramientas.arreglomartillos.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getMatmango(), indiceFila, 7);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getMatcabezal(), indiceFila, 8);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getPeso(), indiceFila, 9);
            jTable1.setValueAt(CategoriaHerramientas.arreglomartillos.get(i).getTamaño(), indiceFila, 10);
            indiceFila++;
        }

    }//GEN-LAST:event_jButtonOrdenarPrecioDescActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuMartillosInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuMartillosInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuMartillosInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuMartillosInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuMartillosInter().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrarTodos;
    private javax.swing.JButton jButtonBorrarUno;
    private javax.swing.JButton jButtonConsultarTodo;
    private javax.swing.JButton jButtonConsultarUno;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonOrdenarID;
    private javax.swing.JButton jButtonOrdenarNombreAsc;
    private javax.swing.JButton jButtonOrdenarNombreDesc;
    private javax.swing.JButton jButtonOrdenarPrecioAsc;
    private javax.swing.JButton jButtonOrdenarPrecioDesc;
    private javax.swing.JComboBox<String> jComboBoxMarca;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelMaterialCabezal;
    private javax.swing.JLabel jLabelMaterialMango;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPesoMartillo;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTamañoMartillo;
    private javax.swing.JLabel jLabelTipoMartillo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUrl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldColor;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldMaterialCabezal;
    private javax.swing.JTextField jTextFieldMaterialMango;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPesoMartillo;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldTamañoMartillo;
    private javax.swing.JTextField jTextFieldTipoMartillo;
    private javax.swing.JTextField jTextFieldUrl;
    // End of variables declaration//GEN-END:variables
}
