/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaGUI;

import controlador.ManejadorObjetos;
import controlador.ManejadorTelevisores;
import controladorDB.ManejadorMarcasDB;
import controladorDB.ManejadorTelevisorBD;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import modelo.CategoriaElectrodomesticos;
import modelo.Marca;
import modelo.Televisores;

/**
 *
 * @author danie
 */
public class MenuTvInter extends javax.swing.JFrame {

    /**
     * Creates new form MenuTvInter
     */
    ManejadorObjetos manobj;
    ManejadorTelevisores mantv;
    ManejadorMarcasDB manmarDB;
    ManejadorTelevisorBD mantvBD;
    Integer idMarcaTemporal = null;
    String nombreMarcaTemporal = "";
    DefaultTableModel model;
    int indiceFila = 0;
    String[] dato = new String[10];
    JFileChooser fileChooser = new JFileChooser();
    ImageIcon image = null;
    File archivo = null;
    String ruta = "E:\\daniel\\Descargas\\graySquare.jpeg";
    JLabel labelImagen = new JLabel("", new ImageIcon(ruta), JLabel.CENTER);

    public MenuTvInter() {
        initComponents();
        this.setLocationRelativeTo(null);
        manobj = new ManejadorObjetos();
        mantv = new ManejadorTelevisores();
        manmarDB = new ManejadorMarcasDB();
        mantvBD = new ManejadorTelevisorBD();
        model = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int column) {
                switch (column) {
                    case 10:
                        return ImageIcon.class;
                    default:
                        return String.class;
                }
            }
        };;
        model.addColumn("Id");
        model.addColumn("Nombre Marca");
        model.addColumn("Nombre");
        model.addColumn("Cantidad");
        model.addColumn("Precio");
        model.addColumn("Color");
        model.addColumn("Tipo Televisor");
        model.addColumn("Tamaño Pantalla");
        model.addColumn("Tipo Pantalla");
        model.addColumn("Resolucion");
        model.addColumn("Imagen");
        jTable1.setModel(model);
        jTable1.getColumnModel().getColumn(0).setMinWidth(30);
        jTable1.getColumnModel().getColumn(10).setMinWidth(150);
        model.insertRow(indiceFila, dato);
        inicializarComboBox();
        fileChooser.setAcceptAllFileFilterUsed(false);
        FileFilter imageFilter = new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());
        fileChooser.addChoosableFileFilter(imageFilter);
        panelImagen.setPreferredSize(new Dimension(132, 132));
        panelImagen.add(labelImagen, BorderLayout.CENTER);
        jTable1.setRowHeight(150);
        jTable1.setRowMargin(5);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.jpg")).getImage());
        ImageIcon ilogo = new ImageIcon(getClass().getResource("/imagenes/icono.jpg"));
        ImageIcon logo = new ImageIcon(ilogo.getImage().getScaledInstance(jlogo.getWidth(), jlogo.getHeight(), Image.SCALE_DEFAULT));
        jlogo.setIcon(logo);
    }

//    public void inicializarComboBox() {
//        for (int i = 0; i < manobj.arregloMarcas.size(); i++) {
//            jComboBoxMarca.addItem(manobj.arregloMarcas.get(i).getDescripcion());
//        }
//    }
    public void inicializarComboBox() {
        manmarDB.consultarTodos();
        for (int i = 0; i < ManejadorObjetos.arregloMarcas.size(); i++) {
            jComboBoxMarca.addItem(ManejadorObjetos.arregloMarcas.get(i).getDescripcion());
        }
    }

    public void limpiar() {
        jTextFieldId.setText("");
        jTextFieldNombre.setText("");
        jTextFieldCantidad.setText("");
        jTextFieldPrecio.setText("");
        jTextFieldColor.setText("");
        jTextFieldTipoTelevisor.setText("");
        jTextFieldTamañoPantalla.setText("");
        jTextFieldTipoPantalla.setText("");
        jTextFieldResolucion.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBorrarTodos = new javax.swing.JButton();
        jButtonConsultarUno = new javax.swing.JButton();
        jLabelId = new javax.swing.JLabel();
        jButtonConsultarTodo = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonInsertar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelMensaje = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jTextFieldTamañoPantalla = new javax.swing.JTextField();
        jTextFieldCantidad = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldColor = new javax.swing.JTextField();
        jTextFieldId = new javax.swing.JTextField();
        jLabelMarca = new javax.swing.JLabel();
        jComboBoxMarca = new javax.swing.JComboBox<>();
        jLabelTamañoPantalla = new javax.swing.JLabel();
        jLabelColor = new javax.swing.JLabel();
        jLabelTipoTelevisor = new javax.swing.JLabel();
        jButtonBorrarUno = new javax.swing.JButton();
        jLabelPrecio = new javax.swing.JLabel();
        jTextFieldTipoTelevisor = new javax.swing.JTextField();
        jLabelTipoPantalla = new javax.swing.JLabel();
        jTextFieldTipoPantalla = new javax.swing.JTextField();
        jLabelResolucion = new javax.swing.JLabel();
        jTextFieldResolucion = new javax.swing.JTextField();
        jButtonOrdenarNombreAsc = new javax.swing.JButton();
        jButtonOrdenarPrecioAsc = new javax.swing.JButton();
        jButtonOrdenarNombreDesc = new javax.swing.JButton();
        jButtonOrdenarPrecioDesc = new javax.swing.JButton();
        jButtonOrdenarID = new javax.swing.JButton();
        panelImagen = new javax.swing.JPanel();
        botonFileChooser = new javax.swing.JButton();
        jlogo = new javax.swing.JLabel();

        setTitle("Televisores\n");

        jButtonBorrarTodos.setText("Borrar Todos");
        jButtonBorrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTodosActionPerformed(evt);
            }
        });

        jButtonConsultarUno.setText("Consultar Uno");
        jButtonConsultarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarUnoActionPerformed(evt);
            }
        });

        jLabelId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId.setText("ID");

        jButtonConsultarTodo.setText("Consultar Todo");
        jButtonConsultarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarTodoActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonInsertar.setText("Insertar");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI Historic", 3, 36)); // NOI18N
        jLabelTitulo.setText("Televisor");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabelMensaje.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMensaje.setText("Estado");

        jLabelCantidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCantidad.setText("Cantidad");

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNombre.setText("Nombre");

        jLabelMarca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMarca.setText("Marca");

        jComboBoxMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMarcaItemStateChanged(evt);
            }
        });

        jLabelTamañoPantalla.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTamañoPantalla.setText("Tamaño Pantalla");

        jLabelColor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelColor.setText("Color");

        jLabelTipoTelevisor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTipoTelevisor.setText("Tipo Televisor");

        jButtonBorrarUno.setText("Borrar Uno");
        jButtonBorrarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarUnoActionPerformed(evt);
            }
        });

        jLabelPrecio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPrecio.setText("Precio");

        jTextFieldTipoTelevisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoTelevisorActionPerformed(evt);
            }
        });

        jLabelTipoPantalla.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTipoPantalla.setText("Tipo Pantalla");

        jLabelResolucion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelResolucion.setText("Resolucion");

        jButtonOrdenarNombreAsc.setText("Ordenar Nombre Ascendente");
        jButtonOrdenarNombreAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNombreAscActionPerformed(evt);
            }
        });

        jButtonOrdenarPrecioAsc.setText("Ordenar Precio Ascendente");
        jButtonOrdenarPrecioAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPrecioAscActionPerformed(evt);
            }
        });

        jButtonOrdenarNombreDesc.setText("Ordenar Nombre Descendente");
        jButtonOrdenarNombreDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNombreDescActionPerformed(evt);
            }
        });

        jButtonOrdenarPrecioDesc.setText("Ordenar Precio Descendente");
        jButtonOrdenarPrecioDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPrecioDescActionPerformed(evt);
            }
        });

        jButtonOrdenarID.setText("Ordenar ID");
        jButtonOrdenarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarIDActionPerformed(evt);
            }
        });

        panelImagen.setBackground(new java.awt.Color(204, 204, 204));
        panelImagen.setLayout(new java.awt.BorderLayout());

        botonFileChooser.setText("Examinar...");
        botonFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFileChooserActionPerformed(evt);
            }
        });

        jlogo.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelId)
                                    .addComponent(jLabelMarca)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jLabelCantidad)
                                    .addComponent(jLabelPrecio))
                                .addGap(45, 45, 45))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelColor)
                                .addGap(48, 48, 48)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxMarca, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPrecio)
                            .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTipoTelevisor)
                                    .addComponent(jLabelTamañoPantalla)
                                    .addComponent(jLabelTipoPantalla)
                                    .addComponent(jLabelResolucion))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldTipoTelevisor)
                                    .addComponent(jTextFieldTamañoPantalla)
                                    .addComponent(jTextFieldTipoPantalla)
                                    .addComponent(jTextFieldResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(84, 84, 84)
                                .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonFileChooser)
                                .addGap(19, 19, 19))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonOrdenarNombreDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonOrdenarNombreAsc, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonOrdenarPrecioDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonOrdenarPrecioAsc, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(jButtonOrdenarID)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonConsultarUno)
                    .addComponent(jButtonConsultarTodo)
                    .addComponent(jButtonBorrarUno)
                    .addComponent(jButtonBorrarTodos)
                    .addComponent(jButtonInsertar))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitulo))
                    .addComponent(jlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelId)
                                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelMarca)
                                            .addComponent(jComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelNombre)
                                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelCantidad)
                                            .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelTipoTelevisor)
                                            .addComponent(jTextFieldTipoTelevisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelTamañoPantalla)
                                            .addComponent(jTextFieldTamañoPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelTipoPantalla)
                                            .addComponent(jTextFieldTipoPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelResolucion))))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelPrecio)
                                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelColor)
                                    .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButtonOrdenarNombreAsc)
                                            .addComponent(jButtonOrdenarPrecioAsc))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButtonOrdenarNombreDesc)
                                            .addComponent(jButtonOrdenarPrecioDesc)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonOrdenarID)
                                        .addGap(16, 16, 16))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(botonFileChooser)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonInsertar)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonModificar)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonConsultarUno)
                        .addGap(15, 15, 15)
                        .addComponent(jButtonConsultarTodo)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonBorrarUno)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonBorrarTodos)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarTodoActionPerformed
        mantvBD.consultarTodos();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectrodomesticos.arreglotelevisores.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getTipotelevisor(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getTampantalla(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getTipopantalla(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getResolucion(), indiceFila, 9);
            jTable1.setValueAt(new ImageIcon(CategoriaElectrodomesticos.arreglotelevisores.get(i).getImagen()), indiceFila, 10);

            indiceFila++;
        }
    }//GEN-LAST:event_jButtonConsultarTodoActionPerformed

    private void jTextFieldTipoTelevisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoTelevisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoTelevisorActionPerformed

    private void jComboBoxMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMarcaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (jComboBoxMarca.getItemCount() > 0) {
                idMarcaTemporal = ManejadorObjetos.arregloMarcas.get(jComboBoxMarca.getSelectedIndex()).getId();
                nombreMarcaTemporal = ManejadorObjetos.arregloMarcas.get(jComboBoxMarca.getSelectedIndex()).getDescripcion();
            }
        }
    }//GEN-LAST:event_jComboBoxMarcaItemStateChanged

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
        Televisores tv = new Televisores();

        try {
            if (!ValidaEnteros.validaEnteros(jTextFieldId.getText())) {
                throw new ValidaEnteros();
            }
            if (!ValidaCantidad.validaCantidad(jTextFieldCantidad.getText())) {
                throw new ValidaCantidad();
            }
            if (!ValidaFlotantes.validaFlotantes(jTextFieldPrecio.getText())) {
                throw new ValidaFlotantes();
            }
            if (!ValidaTamañoPantalla.validaTamañoPantalla(jTextFieldTamañoPantalla.getText())) {
                throw new ValidaTamañoPantalla();
            }
            if (!ValidaResolucion.validaResolucion(jTextFieldResolucion.getText())) {
                throw new ValidaResolucion();
            }
        } catch (ValidaEnteros e) {
            jLabelMensaje.setText("El id que ingreso no es valido");
            jTextFieldId.setText("");
            return;
        } catch (ValidaCantidad e) {
            jLabelMensaje.setText("La cantidad que ingreso no es valida");
            jTextFieldCantidad.setText("");
            return;
        } catch (ValidaFlotantes e) {
            jLabelMensaje.setText("El precio que ingreso no es valido");
            jTextFieldPrecio.setText("");
            return;
        } catch (ValidaTamañoPantalla e) {
            jLabelMensaje.setText("El tamaño de pantalla que ingreso no es valido");
            jTextFieldTamañoPantalla.setText("");
            return;
        } catch (ValidaResolucion e) {
            jLabelMensaje.setText("La resolucion que ingreso no es valido");
            jTextFieldResolucion.setText("");
            return;
        }

        Marca mar = new Marca();
        tv.setIdArticulo(Integer.parseInt(jTextFieldId.getText()));
        mar.setId(idMarcaTemporal);
        mar.setDescripcion(nombreMarcaTemporal);
        tv.setMar(mar);
        tv.setNombre(jTextFieldNombre.getText());
        tv.setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
        tv.setPrecio(Float.parseFloat(jTextFieldPrecio.getText()));
        tv.setColor(jTextFieldColor.getText());
        tv.setImagen(ruta);
        tv.setTipotelevisor(jTextFieldTipoTelevisor.getText());
        tv.setTampantalla(Integer.parseInt(jTextFieldTamañoPantalla.getText()));
        tv.setTipopantalla(jTextFieldTipoPantalla.getText());
        tv.setResolucion(jTextFieldResolucion.getText());

        if (mantvBD.insertar(tv)) {
            jLabelMensaje.setText("El articulo " + jTextFieldNombre.getText() + " se insertó correctamente");
            //JOptionPane.showMessageDialog(this, "El articulo " + jTextFieldNombre.getText() + " se insertó correctamente");
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(jTextFieldId.getText(), indiceFila, 0);
            jTable1.setValueAt(nombreMarcaTemporal, indiceFila, 1);
            jTable1.setValueAt(jTextFieldNombre.getText(), indiceFila, 2);
            jTable1.setValueAt(jTextFieldCantidad.getText(), indiceFila, 3);
            jTable1.setValueAt(jTextFieldPrecio.getText(), indiceFila, 4);
            jTable1.setValueAt(jTextFieldColor.getText(), indiceFila, 5);
            jTable1.setValueAt(jTextFieldTipoTelevisor.getText(), indiceFila, 6);
            jTable1.setValueAt(jTextFieldTamañoPantalla.getText(), indiceFila, 7);
            jTable1.setValueAt(jTextFieldTipoPantalla.getText(), indiceFila, 8);
            jTable1.setValueAt(jTextFieldResolucion.getText(), indiceFila, 9);
            jTable1.setValueAt(ruta, indiceFila, 10);
            jTable1.setValueAt(new ImageIcon(ruta), indiceFila, 10);
            ruta = "E:\\daniel\\Descargas\\graySquare.jpeg";
            image = new ImageIcon(ruta);
            labelImagen.setIcon(image);

            indiceFila++;
            mantvBD.consultarTodos();
        } else {
            jLabelMensaje.setText("Error al insertar");
            //JOptionPane.showMessageDialog(this, "Error al insertar");
        }
        limpiar();
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        System.out.println(filaSeleccionada);

        if (filaSeleccionada >= 0) {

            Televisores tvmod = new Televisores();
            int a = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            jTextFieldId.setText(jTable1.getValueAt(filaSeleccionada, 0).toString());
            String nombreMarcaMod = jTable1.getValueAt(filaSeleccionada, 1).toString();
            jTextFieldNombre.setText(jTable1.getValueAt(filaSeleccionada, 2).toString());
            jTextFieldCantidad.setText(jTable1.getValueAt(filaSeleccionada, 3).toString());
            jTextFieldPrecio.setText(jTable1.getValueAt(filaSeleccionada, 4).toString());
            jTextFieldColor.setText(jTable1.getValueAt(filaSeleccionada, 5).toString());
            jTextFieldTipoTelevisor.setText(jTable1.getValueAt(filaSeleccionada, 6).toString());
            jTextFieldTamañoPantalla.setText(jTable1.getValueAt(filaSeleccionada, 7).toString());
            jTextFieldTipoPantalla.setText(jTable1.getValueAt(filaSeleccionada, 8).toString());
            jTextFieldResolucion.setText(jTable1.getValueAt(filaSeleccionada, 9).toString());
            String img = jTable1.getValueAt(filaSeleccionada, 10).toString();

            try {

                if (!ValidaCantidad.validaCantidad(jTextFieldCantidad.getText())) {
                    throw new ValidaCantidad();
                }
                if (!ValidaFlotantes.validaFlotantes(jTextFieldPrecio.getText())) {
                    throw new ValidaFlotantes();
                }
                if (!ValidaTamañoPantalla.validaTamañoPantalla(jTextFieldTamañoPantalla.getText())) {
                    throw new ValidaTamañoPantalla();
                }
                if (!ValidaResolucion.validaResolucion(jTextFieldResolucion.getText())) {
                    throw new ValidaResolucion();
                }
            } catch (ValidaCantidad e) {
                jLabelMensaje.setText("La cantidad que ingreso no es valida");
                jTextFieldCantidad.setText("");
                return;
            } catch (ValidaFlotantes e) {
                jLabelMensaje.setText("El precio que ingreso no es valido");
                jTextFieldPrecio.setText("");
                return;
            } catch (ValidaTamañoPantalla e) {
                jLabelMensaje.setText("El tamaño de pantalla que ingreso no es valido");
                jTextFieldTamañoPantalla.setText("");
                return;
            } catch (ValidaResolucion e) {
                jLabelMensaje.setText("La resolucion que ingreso no es valido");
                jTextFieldResolucion.setText("");
                return;
            }

            Marca marmod = new Marca();
            tvmod.setIdArticulo(Integer.parseInt(jTextFieldId.getText()));
            marmod.setId(a);
            marmod.setDescripcion(nombreMarcaMod);
            tvmod.setMar(marmod);
            tvmod.setNombre(jTextFieldNombre.getText());
            tvmod.setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
            tvmod.setPrecio(Float.parseFloat(jTextFieldPrecio.getText()));
            tvmod.setColor(jTextFieldColor.getText());
            tvmod.setTipotelevisor(jTextFieldTipoTelevisor.getText());
            tvmod.setTampantalla(Integer.parseInt(jTextFieldTamañoPantalla.getText()));
            tvmod.setTipopantalla(jTextFieldTipoPantalla.getText());
            tvmod.setResolucion(jTextFieldResolucion.getText());
            if (ruta.equals("E:\\daniel\\Descargas\\graySquare.jpeg")) {
                tvmod.setImagen(img);
            } else {
                tvmod.setImagen(ruta);
                ruta = "E:\\daniel\\Descargas\\graySquare.jpeg";
                image = new ImageIcon(ruta);
                labelImagen.setIcon(image);
            }

            //Marca marmod = new Marca(Integer.parseInt(jTextFieldId.getText()), jTextFieldMarca.getText());
//           
            if (mantvBD.modificar(a, tvmod)) {
                JOptionPane.showMessageDialog(this, "Televisor modificado exitosamente");
                indiceFila--;
                mantvBD.consultarTodos();

            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar");
            }
        }
        limpiar();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonConsultarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarUnoActionPerformed
//        int idBuscado = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el ID a buscar"));
//
//        Televisores resultado = (Televisores) mantv.consultarId(idBuscado);
//        if (resultado == null) {
//            JOptionPane.showMessageDialog(this, "Televisor no encontrado");
//        } else {
//            JOptionPane.showMessageDialog(this, "El televisor encontrado es:\n" + resultado.toString());
//        }
        try {
            int idBuscado = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el ID a buscar"));
            Televisores resultado = (Televisores) mantvBD.consultarId(idBuscado);
            JOptionPane.showMessageDialog(this, "El televisor encontrado es:\n" + resultado.toString());
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Televisor no encontrado");

        }
    }//GEN-LAST:event_jButtonConsultarUnoActionPerformed

    private void jButtonBorrarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarUnoActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada >= 0) {
            int idEliminar = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            model.removeRow(filaSeleccionada);
            if (mantvBD.borrar(idEliminar)) {
                JOptionPane.showMessageDialog(this, "Televisor borrado exitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Error al borrar");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar");
        }
    }//GEN-LAST:event_jButtonBorrarUnoActionPerformed

    private void jButtonBorrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTodosActionPerformed
        if (mantvBD.borrarTodo()) {
            while (model.getRowCount() > 0) {
                model.removeRow(0);
            }
            indiceFila = 0;
            JOptionPane.showMessageDialog(this, "Todos los televisores se borraron exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar todo");
        }
    }//GEN-LAST:event_jButtonBorrarTodosActionPerformed

    private void jButtonOrdenarNombreAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNombreAscActionPerformed
        mantv.ordenarMezcla();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectrodomesticos.arreglotelevisores.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getTipotelevisor(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getTampantalla(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getTipopantalla(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getResolucion(), indiceFila, 9);
            jTable1.setValueAt(new ImageIcon(CategoriaElectrodomesticos.arreglotelevisores.get(i).getImagen()), indiceFila, 10);

            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarNombreAscActionPerformed

    private void jButtonOrdenarPrecioAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPrecioAscActionPerformed
        mantv.quicksort();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectrodomesticos.arreglotelevisores.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getTipotelevisor(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getTampantalla(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getTipopantalla(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getResolucion(), indiceFila, 9);
            jTable1.setValueAt(new ImageIcon(CategoriaElectrodomesticos.arreglotelevisores.get(i).getImagen()), indiceFila, 10);

            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarPrecioAscActionPerformed

    private void jButtonOrdenarNombreDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNombreDescActionPerformed
        mantv.ordenarMezclaDesc();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectrodomesticos.arreglotelevisores.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getTipotelevisor(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getTampantalla(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getTipopantalla(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getResolucion(), indiceFila, 9);
            jTable1.setValueAt(new ImageIcon(CategoriaElectrodomesticos.arreglotelevisores.get(i).getImagen()), indiceFila, 10);

            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarNombreDescActionPerformed

    private void jButtonOrdenarPrecioDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPrecioDescActionPerformed
        mantv.quicksortDesc();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectrodomesticos.arreglotelevisores.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getTipotelevisor(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getTampantalla(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getTipopantalla(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getResolucion(), indiceFila, 9);
            jTable1.setValueAt(new ImageIcon(CategoriaElectrodomesticos.arreglotelevisores.get(i).getImagen()), indiceFila, 10);

            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarPrecioDescActionPerformed

    private void jButtonOrdenarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarIDActionPerformed
        mantv.sort();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectrodomesticos.arreglotelevisores.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getTipotelevisor(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getTampantalla(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getTipopantalla(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglotelevisores.get(i).getResolucion(), indiceFila, 9);
            jTable1.setValueAt(new ImageIcon(CategoriaElectrodomesticos.arreglotelevisores.get(i).getImagen()), indiceFila, 10);

            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarIDActionPerformed

    private void botonFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFileChooserActionPerformed
        fileChooser.showDialog(this, "Choose"); //
        archivo = fileChooser.getSelectedFile();
        ruta = archivo.getAbsolutePath();
        image = new ImageIcon(ruta);
        labelImagen.setIcon(image);
    }//GEN-LAST:event_botonFileChooserActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuTvInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuTvInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuTvInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuTvInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuTvInter().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonFileChooser;
    private javax.swing.JButton jButtonBorrarTodos;
    private javax.swing.JButton jButtonBorrarUno;
    private javax.swing.JButton jButtonConsultarTodo;
    private javax.swing.JButton jButtonConsultarUno;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonOrdenarID;
    private javax.swing.JButton jButtonOrdenarNombreAsc;
    private javax.swing.JButton jButtonOrdenarNombreDesc;
    private javax.swing.JButton jButtonOrdenarPrecioAsc;
    private javax.swing.JButton jButtonOrdenarPrecioDesc;
    private javax.swing.JComboBox<String> jComboBoxMarca;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelResolucion;
    private javax.swing.JLabel jLabelTamañoPantalla;
    private javax.swing.JLabel jLabelTipoPantalla;
    private javax.swing.JLabel jLabelTipoTelevisor;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldColor;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldResolucion;
    private javax.swing.JTextField jTextFieldTamañoPantalla;
    private javax.swing.JTextField jTextFieldTipoPantalla;
    private javax.swing.JTextField jTextFieldTipoTelevisor;
    private javax.swing.JLabel jlogo;
    private javax.swing.JPanel panelImagen;
    // End of variables declaration//GEN-END:variables
}
