/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaGUI;

import controlador.ManejadorConsolas;
import controlador.ManejadorObjetos;
import controladorDB.ManejadorConsolaDB;
import controladorDB.ManejadorMarcasDB;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import modelo.CategoriaVideojuegos;
import modelo.Consolas;
import modelo.Marca;

/**
 *
 * @author Daniel
 */
public class MenuConsolasInter extends javax.swing.JFrame {

    /**
     * Creates new form MenuConsolasInter
     */
    ManejadorObjetos manobj;
    ManejadorConsolas mancons;
    ManejadorMarcasDB manmarDB;
    ManejadorConsolaDB manconsDB;
    Integer idMarcaTemporal = null;
    String nombreMarcaTemporal = "";
    DefaultTableModel model;
    int indiceFila = 0;
    String[] dato = new String[10];
    JFileChooser fileChooser = new JFileChooser();
    ImageIcon image = null;
    File archivo = null;
    String ruta = "E:\\daniel\\Descargas\\graySquare.jpeg";
    JLabel labelImagen = new JLabel("", new ImageIcon(ruta), JLabel.CENTER);

    public MenuConsolasInter() {
        initComponents();
        this.setLocationRelativeTo(null);
        manobj = new ManejadorObjetos();
        mancons = new ManejadorConsolas();
        manmarDB = new ManejadorMarcasDB();
        manconsDB = new ManejadorConsolaDB();
        model = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int column) {
                switch (column) {
                    case 10:
                        return ImageIcon.class;
                    default:
                        return String.class;
                }
            }
        };;
        model.addColumn("Id");
        model.addColumn("Nombre Marca");
        model.addColumn("Nombre");
        model.addColumn("Cantidad");
        model.addColumn("Precio");
        model.addColumn("Color");
        model.addColumn("Tipo Consolas");
        model.addColumn("Numero Controles");
        model.addColumn("Realidad Virtual");
        model.addColumn("Capacidad Disco Duro");
        model.addColumn("Imagen");

        jTable1.setModel(model);
        jTable1.getColumnModel().getColumn(0).setMinWidth(30);
        jTable1.getColumnModel().getColumn(10).setMinWidth(150);
        model.insertRow(indiceFila, dato);
        inicializarComboBox();
        fileChooser.setAcceptAllFileFilterUsed(false);
        FileFilter imageFilter = new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());
        fileChooser.addChoosableFileFilter(imageFilter);
        panelImagen.setPreferredSize(new Dimension(132, 132));
        panelImagen.add(labelImagen, BorderLayout.CENTER);
        jTable1.setRowHeight(150);
        jTable1.setRowMargin(5);
    }

//    public void inicializarComboBox() {
//        for (int i = 0; i < manobj.arregloMarcas.size(); i++) {
//            jComboBoxMarca.addItem(manobj.arregloMarcas.get(i).getDescripcion());
//        }
//    }
    public void inicializarComboBox() {
        manmarDB.consultarTodos();
        for (int i = 0; i < ManejadorObjetos.arregloMarcas.size(); i++) {
            jComboBoxMarca.addItem(ManejadorObjetos.arregloMarcas.get(i).getDescripcion());
        }
    }

    public void limpiar() {
        jTextFieldId.setText("");
        jTextFieldNombre.setText("");
        jTextFieldCantidad.setText("");
        jTextFieldPrecio.setText("");
        jTextFieldColor.setText("");
        jTextFieldTipoConsola.setText("");
        jTextFieldNumeroControles.setText("");
        jTextFieldRealidadvirtual.setText("");
        jTextFieldCapacidadDiscoduro.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTipoConsola = new javax.swing.JLabel();
        jLabelNumeroControles = new javax.swing.JLabel();
        jLabelRealidadVirtual = new javax.swing.JLabel();
        jLabelCapacidadDiscoduro = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jComboBoxMarca = new javax.swing.JComboBox<>();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldCantidad = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldTipoConsola = new javax.swing.JTextField();
        jTextFieldNumeroControles = new javax.swing.JTextField();
        jTextFieldRealidadvirtual = new javax.swing.JTextField();
        jTextFieldCapacidadDiscoduro = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelColor = new javax.swing.JLabel();
        jTextFieldColor = new javax.swing.JTextField();
        jButtonModificar = new javax.swing.JButton();
        jButtonConsultarUno = new javax.swing.JButton();
        jButtonConsultarTodo = new javax.swing.JButton();
        jButtonBorrarUno = new javax.swing.JButton();
        jButtonBorrarTodos = new javax.swing.JButton();
        jButtonInsertar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelMensaje = new javax.swing.JLabel();
        jButtonOrdenarID = new javax.swing.JButton();
        jButtonOrdenarNombreAsc = new javax.swing.JButton();
        jButtonOrdenarPrecioAsc = new javax.swing.JButton();
        jButtonOrdenarNombreDesc = new javax.swing.JButton();
        jButtonOrdenarPrecioDesc = new javax.swing.JButton();
        botonFileChooserExaminar = new javax.swing.JButton();
        panelImagen = new javax.swing.JPanel();

        setTitle("Consolas");

        jLabelTipoConsola.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTipoConsola.setText("Tipo consola");

        jLabelNumeroControles.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNumeroControles.setText("Numero controles");

        jLabelRealidadVirtual.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelRealidadVirtual.setText("Realidad virtual");

        jLabelCapacidadDiscoduro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCapacidadDiscoduro.setText("Capacidad disco duro");

        jComboBoxMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMarcaItemStateChanged(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI Historic", 3, 36)); // NOI18N
        jLabelTitulo.setText("Consolas");

        jLabelId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId.setText("ID");

        jLabelMarca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMarca.setText("Marca");

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNombre.setText("Nombre");

        jLabelCantidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCantidad.setText("Cantidad");

        jLabelPrecio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPrecio.setText("Precio");

        jLabelColor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelColor.setText("Color");

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonConsultarUno.setText("Consultar Uno");
        jButtonConsultarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarUnoActionPerformed(evt);
            }
        });

        jButtonConsultarTodo.setText("Consultar Todo");
        jButtonConsultarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarTodoActionPerformed(evt);
            }
        });

        jButtonBorrarUno.setText("Borrar Uno");
        jButtonBorrarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarUnoActionPerformed(evt);
            }
        });

        jButtonBorrarTodos.setText("Borrar Todos");
        jButtonBorrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTodosActionPerformed(evt);
            }
        });

        jButtonInsertar.setText("Insertar");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabelMensaje.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMensaje.setText("Estado");

        jButtonOrdenarID.setText("Ordenar ID");
        jButtonOrdenarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarIDActionPerformed(evt);
            }
        });

        jButtonOrdenarNombreAsc.setText("Ordenar Nombre Ascendente");
        jButtonOrdenarNombreAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNombreAscActionPerformed(evt);
            }
        });

        jButtonOrdenarPrecioAsc.setText("Ordenar Precio Ascendente");
        jButtonOrdenarPrecioAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPrecioAscActionPerformed(evt);
            }
        });

        jButtonOrdenarNombreDesc.setText("Ordenar Nombre Descendente");
        jButtonOrdenarNombreDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNombreDescActionPerformed(evt);
            }
        });

        jButtonOrdenarPrecioDesc.setText("Ordenar Precio Descendente");
        jButtonOrdenarPrecioDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPrecioDescActionPerformed(evt);
            }
        });

        botonFileChooserExaminar.setText("Examinar...");
        botonFileChooserExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFileChooserExaminarActionPerformed(evt);
            }
        });

        panelImagen.setBackground(new java.awt.Color(204, 204, 204));
        panelImagen.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelId)
                                            .addComponent(jLabelMarca)
                                            .addComponent(jLabelNombre)
                                            .addComponent(jLabelCantidad)
                                            .addComponent(jLabelPrecio))
                                        .addGap(45, 45, 45))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelColor)
                                        .addGap(48, 48, 48)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxMarca, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldId, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPrecio)
                                    .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelTipoConsola)
                                            .addComponent(jLabelNumeroControles)
                                            .addComponent(jLabelRealidadVirtual)
                                            .addComponent(jLabelCapacidadDiscoduro))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldRealidadvirtual, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldNumeroControles, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldTipoConsola, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldCapacidadDiscoduro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(50, 50, 50)
                                        .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonFileChooserExaminar)
                                        .addGap(21, 21, 21)))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonModificar)
                                    .addComponent(jButtonConsultarUno)
                                    .addComponent(jButtonConsultarTodo)
                                    .addComponent(jButtonBorrarUno)
                                    .addComponent(jButtonBorrarTodos)
                                    .addComponent(jButtonInsertar)))
                            .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonOrdenarNombreDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonOrdenarNombreAsc, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonOrdenarPrecioDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonOrdenarPrecioAsc, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOrdenarID)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabelTitulo)
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelId)
                                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelMarca)
                                            .addComponent(jComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelNombre)
                                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelCantidad)
                                            .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelTipoConsola)
                                            .addComponent(jTextFieldTipoConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelNumeroControles)
                                            .addComponent(jTextFieldNumeroControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelRealidadVirtual)
                                            .addComponent(jTextFieldRealidadvirtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelCapacidadDiscoduro)
                                            .addComponent(jTextFieldCapacidadDiscoduro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelPrecio)
                                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelColor)
                                    .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonFileChooserExaminar))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonOrdenarNombreAsc)
                                    .addComponent(jButtonOrdenarPrecioAsc))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonOrdenarNombreDesc)
                                    .addComponent(jButtonOrdenarPrecioDesc))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonOrdenarID)
                                .addGap(35, 35, 35))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jButtonInsertar)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonModificar)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonConsultarUno)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonConsultarTodo)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonBorrarUno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBorrarTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarTodoActionPerformed

        manconsDB.consultarTodos();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaVideojuegos.arregloconsolas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getNumcontroles(), indiceFila, 7);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getRealidadvir(), indiceFila, 8);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getCapdiscoduro(), indiceFila, 9);
            jTable1.setValueAt(new ImageIcon(CategoriaVideojuegos.arregloconsolas.get(i).getImagen()), indiceFila, 10);

            indiceFila++;
        }

    }//GEN-LAST:event_jButtonConsultarTodoActionPerformed

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed

        Consolas cons = new Consolas();

        try {
            if (!ValidaEnteros.validaEnteros(jTextFieldId.getText())) {
                throw new ValidaEnteros();
            }
            if (!ValidaCantidad.validaCantidad(jTextFieldCantidad.getText())) {
                throw new ValidaCantidad();
            }
            if (!ValidaFlotantes.validaFlotantes(jTextFieldPrecio.getText())) {
                throw new ValidaFlotantes();
            }
            if (!ValidaNumeroControles.validaNumeroControles(jTextFieldNumeroControles.getText())) {
                throw new ValidaNumeroControles();
            }
            if (!ValidaMemoria.validaMemoria(jTextFieldCapacidadDiscoduro.getText())) {
                throw new ValidaMemoria();
            }
        } catch (ValidaEnteros e) {
            jLabelMensaje.setText("El id que ingreso no es valido");
            jTextFieldId.setText("");
            return;
        } catch (ValidaCantidad e) {
            jLabelMensaje.setText("La cantidad que ingreso no es valida");
            jTextFieldCantidad.setText("");
            return;
        } catch (ValidaFlotantes e) {
            jLabelMensaje.setText("El precio que ingreso no es valido");
            jTextFieldPrecio.setText("");
            return;
        } catch (ValidaNumeroControles e) {
            jLabelMensaje.setText("El numero de controles que ingreso es invalido");
            jTextFieldNumeroControles.setText("");
            return;
        } catch (ValidaMemoria e) {
            jLabelMensaje.setText("La capacidad de disco duro que ingreso no es valida");
            jTextFieldCapacidadDiscoduro.setText("");
            return;
        }

        Marca mar = new Marca();
        cons.setIdArticulo(Integer.parseInt(jTextFieldId.getText()));
        mar.setId(idMarcaTemporal);
        mar.setDescripcion(nombreMarcaTemporal);
        cons.setMar(mar);
        cons.setNombre(jTextFieldNombre.getText());
        cons.setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
        cons.setPrecio(Float.parseFloat(jTextFieldPrecio.getText()));
        cons.setColor(jTextFieldColor.getText());
        cons.setImagen(ruta);
        cons.setTipo(jTextFieldTipoConsola.getText());
        cons.setNumcontroles(Integer.parseInt(jTextFieldNumeroControles.getText()));
        cons.setRealidadvir(jTextFieldRealidadvirtual.getText());
        cons.setCapdiscoduro(jTextFieldCapacidadDiscoduro.getText());

        if (manconsDB.insertar(cons)) {
            jLabelMensaje.setText("El articulo " + jTextFieldNombre.getText() + " se insertó correctamente");
            //JOptionPane.showMessageDialog(this, "El articulo " + jTextFieldNombre.getText() + " se insertó correctamente");
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(jTextFieldId.getText(), indiceFila, 0);
            jTable1.setValueAt(nombreMarcaTemporal, indiceFila, 1);
            jTable1.setValueAt(jTextFieldNombre.getText(), indiceFila, 2);
            jTable1.setValueAt(jTextFieldCantidad.getText(), indiceFila, 3);
            jTable1.setValueAt(Float.parseFloat(jTextFieldPrecio.getText()), indiceFila, 4);
            jTable1.setValueAt(jTextFieldColor.getText(), indiceFila, 5);
            jTable1.setValueAt(jTextFieldTipoConsola.getText(), indiceFila, 6);
            jTable1.setValueAt(Integer.parseInt(jTextFieldNumeroControles.getText()), indiceFila, 7);
            jTable1.setValueAt(jTextFieldRealidadvirtual.getText(), indiceFila, 8);
            jTable1.setValueAt(jTextFieldCapacidadDiscoduro.getText(), indiceFila, 9);
            jTable1.setValueAt(ruta, indiceFila, 10);
            jTable1.setValueAt(new ImageIcon(ruta), indiceFila, 10);
            ruta = "E:\\daniel\\Descargas\\graySquare.jpeg";
            image = new ImageIcon(ruta);
            labelImagen.setIcon(image);
            indiceFila++;
            mancons.consultarTodos();
        } else {
            jLabelMensaje.setText("Error al insertar");
            //JOptionPane.showMessageDialog(this, "Error al insertar");
        }
        
        limpiar();
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed

        int filaSeleccionada = jTable1.getSelectedRow();
        System.out.println(filaSeleccionada);

        if (filaSeleccionada >= 0) {

            Consolas consmod = new Consolas();
            int a = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            jTextFieldId.setText(jTable1.getValueAt(filaSeleccionada, 0).toString());
            String nombreMarcaMod = jTable1.getValueAt(filaSeleccionada, 1).toString();
            jTextFieldNombre.setText(jTable1.getValueAt(filaSeleccionada, 2).toString());
            jTextFieldCantidad.setText(jTable1.getValueAt(filaSeleccionada, 3).toString());
            jTextFieldPrecio.setText(jTable1.getValueAt(filaSeleccionada, 4).toString());
            jTextFieldColor.setText(jTable1.getValueAt(filaSeleccionada, 5).toString());
            jTextFieldTipoConsola.setText(jTable1.getValueAt(filaSeleccionada, 6).toString());
            jTextFieldNumeroControles.setText(jTable1.getValueAt(filaSeleccionada, 7).toString());
            jTextFieldRealidadvirtual.setText(jTable1.getValueAt(filaSeleccionada, 8).toString());
            jTextFieldCapacidadDiscoduro.setText(jTable1.getValueAt(filaSeleccionada, 9).toString());
            String img = jTable1.getValueAt(filaSeleccionada, 10).toString();

            try {
                if (!ValidaCantidad.validaCantidad(jTextFieldCantidad.getText())) {
                    throw new ValidaCantidad();
                }
                if (!ValidaFlotantes.validaFlotantes(jTextFieldPrecio.getText())) {
                    throw new ValidaFlotantes();
                }
                if (!ValidaNumeroControles.validaNumeroControles(jTextFieldNumeroControles.getText())) {
                    throw new ValidaNumeroControles();
                }
                if (!ValidaMemoria.validaMemoria(jTextFieldCapacidadDiscoduro.getText())) {
                    throw new ValidaMemoria();
                }
            } catch (ValidaCantidad e) {
                jLabelMensaje.setText("La cantidad que ingreso no es valida");
                jTextFieldCantidad.setText("");
                return;
            } catch (ValidaFlotantes e) {
                jLabelMensaje.setText("El precio que ingreso no es valido");
                jTextFieldPrecio.setText("");
                return;
            } catch (ValidaNumeroControles e) {
                jLabelMensaje.setText("El numero de controles que ingreso es invalido");
                jTextFieldNumeroControles.setText("");
                return;
            } catch (ValidaMemoria e) {
                jLabelMensaje.setText("La capacidad de disco duro que ingreso no es valida");
                jTextFieldCapacidadDiscoduro.setText("");
                return;
            }
            Marca marmod = new Marca();
            consmod.setIdArticulo(Integer.parseInt(jTextFieldId.getText()));
            marmod.setId(a);
            marmod.setDescripcion(nombreMarcaMod);
            consmod.setMar(marmod);
            consmod.setNombre(jTextFieldNombre.getText());
            consmod.setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
            consmod.setPrecio(Float.parseFloat(jTextFieldPrecio.getText()));
            consmod.setColor(jTextFieldColor.getText());
            consmod.setTipo(jTextFieldTipoConsola.getText());
            consmod.setNumcontroles(Integer.parseInt(jTextFieldNumeroControles.getText()));
            consmod.setRealidadvir(jTextFieldRealidadvirtual.getText());
            consmod.setCapdiscoduro(jTextFieldCapacidadDiscoduro.getText());
            consmod.setImagen(img);

            //Marca marmod = new Marca(Integer.parseInt(jTextFieldId.getText()), jTextFieldMarca.getText());
//            int posicion = mancons.busquedaBinaria(a);
//            if (!(posicion == -1)) {
//                if (mancons.modificar(posicion, consmod)) {
//                    JOptionPane.showMessageDialog(this, "Consola modificada exitosamente");
//                    indiceFila--;
//                }
//            } else {
//                JOptionPane.showMessageDialog(this, "Error al modificar");
//            }
              if (manconsDB.modificar(a, consmod)) {
                JOptionPane.showMessageDialog(this, "Consola modificada exitosamente");
                indiceFila--;
                manconsDB.consultarTodos();

              } else {
                JOptionPane.showMessageDialog(this, "Error al modificar");
            }
        }
        limpiar();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonConsultarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarUnoActionPerformed

//        int idBuscado = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el ID a buscar"));
//
//        Consolas resultado = (Consolas) mancons.consultarId(idBuscado);
//        if (resultado == null) {
//            JOptionPane.showMessageDialog(this, "Consola no encontrada");
//        } else {
//            JOptionPane.showMessageDialog(this, "La Consola encontrada es:\n" + resultado.toString());
//        }
          try {
            int idBuscado = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el ID a buscar"));
            Consolas resultado = (Consolas) manconsDB.consultarId(idBuscado);
            JOptionPane.showMessageDialog(this, "La consola encontrada es:\n" + resultado.toString());
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Consola no encontrada");

        }

    }//GEN-LAST:event_jButtonConsultarUnoActionPerformed

    private void jButtonBorrarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarUnoActionPerformed

        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada >= 0) {
            int idEliminar = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            model.removeRow(filaSeleccionada);
            if (manconsDB.borrar(idEliminar)) {
                JOptionPane.showMessageDialog(this, "Consola borrada exitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Error al borrar");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar");
        }

    }//GEN-LAST:event_jButtonBorrarUnoActionPerformed

    private void jButtonBorrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTodosActionPerformed

        if (manconsDB.borrarTodo()) {
            while (model.getRowCount() > 0) {
                model.removeRow(0);
            }
            indiceFila = 0;
            JOptionPane.showMessageDialog(this, "Todos las consolas se borraron exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar todo");
        }

    }//GEN-LAST:event_jButtonBorrarTodosActionPerformed

    private void jComboBoxMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMarcaItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (jComboBoxMarca.getItemCount() > 0) {
                idMarcaTemporal = ManejadorObjetos.arregloMarcas.get(jComboBoxMarca.getSelectedIndex()).getId();
                nombreMarcaTemporal = ManejadorObjetos.arregloMarcas.get(jComboBoxMarca.getSelectedIndex()).getDescripcion();
            }
        }

    }//GEN-LAST:event_jComboBoxMarcaItemStateChanged

    private void jButtonOrdenarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarIDActionPerformed
        mancons.sort();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaVideojuegos.arregloconsolas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getNumcontroles(), indiceFila, 7);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getRealidadvir(), indiceFila, 8);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getCapdiscoduro(), indiceFila, 9);
            jTable1.setValueAt(new ImageIcon(CategoriaVideojuegos.arregloconsolas.get(i).getImagen()), indiceFila, 10);

            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarIDActionPerformed

    private void jButtonOrdenarNombreAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNombreAscActionPerformed
        mancons.ordenarMezcla();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaVideojuegos.arregloconsolas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getNumcontroles(), indiceFila, 7);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getRealidadvir(), indiceFila, 8);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getCapdiscoduro(), indiceFila, 9);
            jTable1.setValueAt(new ImageIcon(CategoriaVideojuegos.arregloconsolas.get(i).getImagen()), indiceFila, 10);

            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarNombreAscActionPerformed

    private void jButtonOrdenarPrecioAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPrecioAscActionPerformed
        mancons.quicksort();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaVideojuegos.arregloconsolas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getNumcontroles(), indiceFila, 7);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getRealidadvir(), indiceFila, 8);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getCapdiscoduro(), indiceFila, 9);
            jTable1.setValueAt(new ImageIcon(CategoriaVideojuegos.arregloconsolas.get(i).getImagen()), indiceFila, 10);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarPrecioAscActionPerformed

    private void jButtonOrdenarNombreDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNombreDescActionPerformed
        mancons.ordenarMezclaDesc();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaVideojuegos.arregloconsolas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getNumcontroles(), indiceFila, 7);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getRealidadvir(), indiceFila, 8);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getCapdiscoduro(), indiceFila, 9);
            jTable1.setValueAt(new ImageIcon(CategoriaVideojuegos.arregloconsolas.get(i).getImagen()), indiceFila, 10);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarNombreDescActionPerformed

    private void jButtonOrdenarPrecioDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPrecioDescActionPerformed
        mancons.quicksortDesc();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaVideojuegos.arregloconsolas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getTipo(), indiceFila, 6);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getNumcontroles(), indiceFila, 7);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getRealidadvir(), indiceFila, 8);
            jTable1.setValueAt(CategoriaVideojuegos.arregloconsolas.get(i).getCapdiscoduro(), indiceFila, 9);
            jTable1.setValueAt(new ImageIcon(CategoriaVideojuegos.arregloconsolas.get(i).getImagen()), indiceFila, 10);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarPrecioDescActionPerformed

    private void botonFileChooserExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFileChooserExaminarActionPerformed
        fileChooser.showDialog(this, "Choose"); //
        archivo = fileChooser.getSelectedFile();
        ruta = archivo.getAbsolutePath();
        image = new ImageIcon(ruta);
        labelImagen.setIcon(image);
    }//GEN-LAST:event_botonFileChooserExaminarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuConsolasInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuConsolasInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuConsolasInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuConsolasInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuConsolasInter().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonFileChooserExaminar;
    private javax.swing.JButton jButtonBorrarTodos;
    private javax.swing.JButton jButtonBorrarUno;
    private javax.swing.JButton jButtonConsultarTodo;
    private javax.swing.JButton jButtonConsultarUno;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonOrdenarID;
    private javax.swing.JButton jButtonOrdenarNombreAsc;
    private javax.swing.JButton jButtonOrdenarNombreDesc;
    private javax.swing.JButton jButtonOrdenarPrecioAsc;
    private javax.swing.JButton jButtonOrdenarPrecioDesc;
    private javax.swing.JComboBox<String> jComboBoxMarca;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCapacidadDiscoduro;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumeroControles;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelRealidadVirtual;
    private javax.swing.JLabel jLabelTipoConsola;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldCapacidadDiscoduro;
    private javax.swing.JTextField jTextFieldColor;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumeroControles;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldRealidadvirtual;
    private javax.swing.JTextField jTextFieldTipoConsola;
    private javax.swing.JPanel panelImagen;
    // End of variables declaration//GEN-END:variables
}
