/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaGUI;

import controlador.ManejadorHornosmicroondas;
import controlador.ManejadorObjetos;
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.CategoriaElectrodomesticos;
import modelo.Hornosmicroondas;
import modelo.Marca;

/**
 *
 * @author Daniel
 */
public class MenuHornosmicroondasInter extends javax.swing.JFrame {

    /**
     * Creates new form MenuHornosmicroondas
     */
    ManejadorObjetos manobj;
    ManejadorHornosmicroondas manhornmic;
    Integer idMarcaTemporal = null;
    String nombreMarcaTemporal = "";
    DefaultTableModel model;
    int indiceFila = 0;
    String[] dato = new String[10];

    public MenuHornosmicroondasInter() {
        initComponents();
        this.setLocationRelativeTo(null);
        manobj = new ManejadorObjetos();
        manhornmic = new ManejadorHornosmicroondas();
        model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Nombre Marca");
        model.addColumn("Nombre");
        model.addColumn("Cantidad");
        model.addColumn("Precio");
        model.addColumn("Color");
        model.addColumn("Capacidad");
        model.addColumn("Compartimiento");
        model.addColumn("Potencia");
        model.addColumn("Voltaje");
        jTable1.setModel(model);
        model.insertRow(indiceFila, dato);
        inicializarComboBox();
    }

    public void inicializarComboBox() {
        for (int i = 0; i < manobj.arregloMarcas.size(); i++) {
            jComboBoxMarca.addItem(manobj.arregloMarcas.get(i).getDescripcion());
        }
    }

    public void limpiar() {
        jTextFieldId.setText("");
        jTextFieldNombre.setText("");
        jTextFieldCantidad.setText("");
        jTextFieldPrecio.setText("");
        jTextFieldColor.setText("");
        jTextFieldUrl.setText("");
        jTextFieldCapacidad.setText("");
        jTextFieldCompartimiento.setText("");
        jTextFieldPotencia.setText("");
        jTextFieldVoltaje.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCantidad = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelUrl = new javax.swing.JLabel();
        jLabelColor = new javax.swing.JLabel();
        jTextFieldColor = new javax.swing.JTextField();
        jLabelCapacidad = new javax.swing.JLabel();
        jLabelCompartimiento = new javax.swing.JLabel();
        jLabelPotencia = new javax.swing.JLabel();
        jLabelVoltaje = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jComboBoxMarca = new javax.swing.JComboBox<>();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldCantidad = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldUrl = new javax.swing.JTextField();
        jTextFieldCapacidad = new javax.swing.JTextField();
        jTextFieldCompartimiento = new javax.swing.JTextField();
        jTextFieldPotencia = new javax.swing.JTextField();
        jTextFieldVoltaje = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jButtonModificar = new javax.swing.JButton();
        jButtonConsultarUno = new javax.swing.JButton();
        jButtonConsultarTodo = new javax.swing.JButton();
        jButtonBorrarUno = new javax.swing.JButton();
        jButtonBorrarTodos = new javax.swing.JButton();
        jButtonInsertar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelMensaje = new javax.swing.JLabel();
        jButtonOrdenarID = new javax.swing.JButton();
        jButtonOrdenarNombreAsc = new javax.swing.JButton();
        jButtonOrdenarPrecioAsc = new javax.swing.JButton();
        jButtonOrdenarNombreDesc = new javax.swing.JButton();
        jButtonOrdenarPrecioDesc = new javax.swing.JButton();

        setTitle("Hornos Microondas");

        jLabelCantidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCantidad.setText("Cantidad");

        jLabelPrecio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPrecio.setText("Precio");

        jLabelUrl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelUrl.setText("Url");

        jLabelColor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelColor.setText("Color");

        jLabelCapacidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCapacidad.setText("Capacidad");

        jLabelCompartimiento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCompartimiento.setText("Compartimiento");

        jLabelPotencia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPotencia.setText("Potencia");

        jLabelVoltaje.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelVoltaje.setText("Voltaje");

        jComboBoxMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMarcaItemStateChanged(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI Historic", 3, 36)); // NOI18N
        jLabelTitulo.setText("Hornos Microondas");

        jLabelId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelId.setText("ID");

        jLabelMarca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMarca.setText("Marca");

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNombre.setText("Nombre");

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonConsultarUno.setText("Consultar Uno");
        jButtonConsultarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarUnoActionPerformed(evt);
            }
        });

        jButtonConsultarTodo.setText("Consultar Todo");
        jButtonConsultarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarTodoActionPerformed(evt);
            }
        });

        jButtonBorrarUno.setText("Borrar Uno");
        jButtonBorrarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarUnoActionPerformed(evt);
            }
        });

        jButtonBorrarTodos.setText("Borrar Todos");
        jButtonBorrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTodosActionPerformed(evt);
            }
        });

        jButtonInsertar.setText("Insertar");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabelMensaje.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMensaje.setText("Estado");

        jButtonOrdenarID.setText("Ordenar ID");
        jButtonOrdenarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarIDActionPerformed(evt);
            }
        });

        jButtonOrdenarNombreAsc.setText("Ordenar Nombre Ascendente");
        jButtonOrdenarNombreAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNombreAscActionPerformed(evt);
            }
        });

        jButtonOrdenarPrecioAsc.setText("Ordenar Precio Ascendente");
        jButtonOrdenarPrecioAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPrecioAscActionPerformed(evt);
            }
        });

        jButtonOrdenarNombreDesc.setText("Ordenar Nombre Descendente");
        jButtonOrdenarNombreDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNombreDescActionPerformed(evt);
            }
        });

        jButtonOrdenarPrecioDesc.setText("Ordenar Precio Descendente");
        jButtonOrdenarPrecioDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPrecioDescActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonOrdenarNombreDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonOrdenarNombreAsc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonOrdenarPrecioDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonOrdenarPrecioAsc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addComponent(jButtonOrdenarID)))
                .addGap(0, 115, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelId)
                            .addComponent(jLabelMarca)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelCantidad)
                            .addComponent(jLabelPrecio))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelColor)
                        .addGap(48, 48, 48)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxMarca, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPrecio)
                    .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUrl)
                    .addComponent(jLabelCapacidad)
                    .addComponent(jLabelCompartimiento)
                    .addComponent(jLabelPotencia)
                    .addComponent(jLabelVoltaje))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldPotencia, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCompartimiento, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCapacidad, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldVoltaje, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldUrl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonConsultarUno)
                    .addComponent(jButtonConsultarTodo)
                    .addComponent(jButtonBorrarUno)
                    .addComponent(jButtonBorrarTodos)
                    .addComponent(jButtonInsertar))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitulo)
                        .addGap(11, 11, 11)
                        .addComponent(jButtonInsertar)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonModificar)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonConsultarUno)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonConsultarTodo)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonBorrarUno))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelUrl)
                                    .addComponent(jTextFieldUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelCapacidad)
                                    .addComponent(jTextFieldCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelCompartimiento)
                                    .addComponent(jTextFieldCompartimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelPotencia)
                                    .addComponent(jTextFieldPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelVoltaje)
                                    .addComponent(jTextFieldVoltaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelId)
                                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelMarca)
                                    .addComponent(jComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelCantidad)
                                    .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelPrecio)
                                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelColor)
                                    .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBorrarTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonOrdenarNombreAsc)
                            .addComponent(jButtonOrdenarPrecioAsc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonOrdenarNombreDesc)
                            .addComponent(jButtonOrdenarPrecioDesc)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonOrdenarID)
                        .addGap(16, 16, 16)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarTodoActionPerformed

        manhornmic.consultarTodos();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectrodomesticos.arreglohornosmicroondas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getCapacidad(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getCompartimiento(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getPotencia(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getVoltaje(), indiceFila, 9);
            indiceFila++;
        }

    }//GEN-LAST:event_jButtonConsultarTodoActionPerformed

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed

        Hornosmicroondas hornmic = new Hornosmicroondas();

        try {
            if (!ValidaEnteros.validaEnteros(jTextFieldId.getText())) {
                throw new ValidaEnteros();
            }
            if (!ValidaCantidad.validaCantidad(jTextFieldCantidad.getText())) {
                throw new ValidaCantidad();
            }
            if (!ValidaFlotantes.validaFlotantes(jTextFieldPrecio.getText())) {
                throw new ValidaFlotantes();
            }
            if (!ValidaMemoria.validaMemoria(jTextFieldCapacidad.getText())) {
                throw new ValidaMemoria();
            }
            if (!ValidaPotencia.validaPotencia(jTextFieldPotencia.getText())) {
                throw new ValidaPotencia();
            }
            if (!ValidaVoltage.validaVoltage(jTextFieldVoltaje.getText())) {
                throw new ValidaVoltage();
            }
        } catch (ValidaEnteros e) {
            jLabelMensaje.setText("El id que ingreso no es valido");
            jTextFieldId.setText("");
            return;
        } catch (ValidaCantidad e) {
            jLabelMensaje.setText("La cantidad que ingreso no es valida");
            jTextFieldCantidad.setText("");
            return;
        } catch (ValidaFlotantes e) {
            jLabelMensaje.setText("El precio que ingreso no es valido");
            jTextFieldPrecio.setText("");
            return;
        } catch (ValidaMemoria e) {
            jLabelMensaje.setText("La capacidad que ingreso no es valida");
            jTextFieldCapacidad.setText("");
            return;
        } catch (ValidaPotencia e) {
            jLabelMensaje.setText("La potencia que ingreso no es valida");
            jTextFieldPotencia.setText("");
            return;
        } catch (ValidaVoltage e) {
            jLabelMensaje.setText("El voltage que ingreso no es valido");
            jTextFieldVoltaje.setText("");
            return;
        }

        Marca mar = new Marca();
        hornmic.setIdArticulo(Integer.parseInt(jTextFieldId.getText()));
        mar.setId(idMarcaTemporal);
        mar.setDescripcion(nombreMarcaTemporal);
        hornmic.setMar(mar);
        hornmic.setNombre(jTextFieldNombre.getText());
        hornmic.setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
        hornmic.setPrecio(Float.parseFloat(jTextFieldPrecio.getText()));
        hornmic.setColor(jTextFieldColor.getText());
        hornmic.setCapacidad(jTextFieldCapacidad.getText());
        hornmic.setCompartimiento(jTextFieldCompartimiento.getText());
        hornmic.setPotencia(jTextFieldPotencia.getText());
        hornmic.setVoltaje(jTextFieldVoltaje.getText());

        if (manhornmic.insertar(hornmic)) {
            jLabelMensaje.setText("El articulo " + jTextFieldNombre.getText() + " se insertó correctamente");
            //JOptionPane.showMessageDialog(this, "El articulo " + jTextFieldNombre.getText() + " se insertó correctamente");
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(jTextFieldId.getText(), indiceFila, 0);
            jTable1.setValueAt(nombreMarcaTemporal, indiceFila, 1);
            jTable1.setValueAt(jTextFieldNombre.getText(), indiceFila, 2);
            jTable1.setValueAt(jTextFieldCantidad.getText(), indiceFila, 3);
            jTable1.setValueAt(Float.parseFloat(jTextFieldPrecio.getText()), indiceFila, 4);
            jTable1.setValueAt(jTextFieldColor.getText(), indiceFila, 5);
            jTable1.setValueAt(jTextFieldCapacidad.getText(), indiceFila, 6);
            jTable1.setValueAt(jTextFieldCompartimiento.getText(), indiceFila, 7);
            jTable1.setValueAt(jTextFieldPotencia.getText(), indiceFila, 8);
            jTable1.setValueAt(jTextFieldVoltaje.getText(), indiceFila, 9);
            indiceFila++;
            manhornmic.consultarTodos();
        } else {
            jLabelMensaje.setText("Error al insertar");
            //JOptionPane.showMessageDialog(this, "Error al insertar");
        }
        limpiar();
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed

        int filaSeleccionada = jTable1.getSelectedRow();
        System.out.println(filaSeleccionada);

        if (filaSeleccionada >= 0) {

            Hornosmicroondas hornmicmod = new Hornosmicroondas();
            int a = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            jTextFieldId.setText(jTable1.getValueAt(filaSeleccionada, 0).toString());
            String nombreMarcaMod = jTable1.getValueAt(filaSeleccionada, 1).toString();
            jTextFieldNombre.setText(jTable1.getValueAt(filaSeleccionada, 2).toString());
            jTextFieldCantidad.setText(jTable1.getValueAt(filaSeleccionada, 3).toString());
            jTextFieldPrecio.setText(jTable1.getValueAt(filaSeleccionada, 4).toString());
            jTextFieldColor.setText(jTable1.getValueAt(filaSeleccionada, 5).toString());
            jTextFieldCapacidad.setText(jTable1.getValueAt(filaSeleccionada, 6).toString());
            jTextFieldCompartimiento.setText(jTable1.getValueAt(filaSeleccionada, 7).toString());
            jTextFieldPotencia.setText(jTable1.getValueAt(filaSeleccionada, 8).toString());
            jTextFieldVoltaje.setText(jTable1.getValueAt(filaSeleccionada, 9).toString());

            try {
                if (!ValidaCantidad.validaCantidad(jTextFieldCantidad.getText())) {
                    throw new ValidaCantidad();
                }
                if (!ValidaFlotantes.validaFlotantes(jTextFieldPrecio.getText())) {
                    throw new ValidaFlotantes();
                }
                if (!ValidaMemoria.validaMemoria(jTextFieldCapacidad.getText())) {
                    throw new ValidaMemoria();
                }
                if (!ValidaPotencia.validaPotencia(jTextFieldPotencia.getText())) {
                    throw new ValidaPotencia();
                }
                if (!ValidaVoltage.validaVoltage(jTextFieldVoltaje.getText())) {
                    throw new ValidaVoltage();
                }
            } catch (ValidaCantidad e) {
                jLabelMensaje.setText("La cantidad que ingreso no es valida");
                jTextFieldCantidad.setText("");
                return;
            } catch (ValidaFlotantes e) {
                jLabelMensaje.setText("El precio que ingreso no es valido");
                jTextFieldPrecio.setText("");
                return;
            } catch (ValidaMemoria e) {
                jLabelMensaje.setText("La capacidad que ingreso no es valida");
                jTextFieldCapacidad.setText("");
                return;
            } catch (ValidaPotencia e) {
                jLabelMensaje.setText("La potencia que ingreso no es valida");
                jTextFieldPotencia.setText("");
                return;
            } catch (ValidaVoltage e) {
                jLabelMensaje.setText("El voltage que ingreso no es valido");
                jTextFieldVoltaje.setText("");
                return;
            }
            Marca marmod = new Marca();
            hornmicmod.setIdArticulo(Integer.parseInt(jTextFieldId.getText()));
            marmod.setId(a);
            marmod.setDescripcion(nombreMarcaMod);
            hornmicmod.setMar(marmod);
            hornmicmod.setNombre(jTextFieldNombre.getText());
            hornmicmod.setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
            hornmicmod.setPrecio(Float.parseFloat(jTextFieldPrecio.getText()));
            hornmicmod.setColor(jTextFieldColor.getText());
            hornmicmod.setCapacidad(jTextFieldCapacidad.getText());
            hornmicmod.setCompartimiento(jTextFieldCompartimiento.getText());
            hornmicmod.setPotencia(jTextFieldPotencia.getText());
            hornmicmod.setPotencia(jTextFieldVoltaje.getText());

            //Marca marmod = new Marca(Integer.parseInt(jTextFieldId.getText()), jTextFieldMarca.getText());
            int posicion = manhornmic.busquedaBinaria(a);
            if (!(posicion == -1)) {
                if (manhornmic.modificar(posicion, hornmicmod)) {
                    JOptionPane.showMessageDialog(this, "Horno microondas modificado exitosamente");
                    indiceFila--;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar");
            }
        }
        limpiar();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonConsultarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarUnoActionPerformed

        int idBuscado = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el ID a buscar"));

        Hornosmicroondas resultado = (Hornosmicroondas) manhornmic.consultarId(idBuscado);
        if (resultado == null) {
            JOptionPane.showMessageDialog(this, "Horno microondas no encontrado");
        } else {
            JOptionPane.showMessageDialog(this, "El Horno microondas encontrada es:\n" + resultado.toString());
        }

    }//GEN-LAST:event_jButtonConsultarUnoActionPerformed

    private void jButtonBorrarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarUnoActionPerformed

        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada >= 0) {
            int idEliminar = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            model.removeRow(filaSeleccionada);
            if (manhornmic.borrar(idEliminar)) {
                JOptionPane.showMessageDialog(this, "Horno microondas borrado exitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Error al borrar");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar");
        }

    }//GEN-LAST:event_jButtonBorrarUnoActionPerformed

    private void jButtonBorrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTodosActionPerformed

        if (manhornmic.borrarTodo()) {
            while (model.getRowCount() > 0) {
                model.removeRow(0);
            }
            indiceFila = 0;
            JOptionPane.showMessageDialog(this, "Todos los Hornos microondas se borraron exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar todo");
        }

    }//GEN-LAST:event_jButtonBorrarTodosActionPerformed

    private void jComboBoxMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMarcaItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (jComboBoxMarca.getItemCount() > 0) {
                idMarcaTemporal = ManejadorObjetos.arregloMarcas.get(jComboBoxMarca.getSelectedIndex()).getId();
                nombreMarcaTemporal = ManejadorObjetos.arregloMarcas.get(jComboBoxMarca.getSelectedIndex()).getDescripcion();
            }
        }

    }//GEN-LAST:event_jComboBoxMarcaItemStateChanged

    private void jButtonOrdenarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarIDActionPerformed
        manhornmic.sort();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectrodomesticos.arreglohornosmicroondas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getCapacidad(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getCompartimiento(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getPotencia(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getVoltaje(), indiceFila, 9);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarIDActionPerformed

    private void jButtonOrdenarNombreAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNombreAscActionPerformed
        manhornmic.ordenarMezcla();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectrodomesticos.arreglohornosmicroondas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getCapacidad(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getCompartimiento(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getPotencia(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getVoltaje(), indiceFila, 9);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarNombreAscActionPerformed

    private void jButtonOrdenarPrecioAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPrecioAscActionPerformed
        manhornmic.quicksort();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectrodomesticos.arreglohornosmicroondas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getCapacidad(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getCompartimiento(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getPotencia(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getVoltaje(), indiceFila, 9);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarPrecioAscActionPerformed

    private void jButtonOrdenarNombreDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNombreDescActionPerformed
        manhornmic.ordenarMezclaDesc();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectrodomesticos.arreglohornosmicroondas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getCapacidad(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getCompartimiento(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getPotencia(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getVoltaje(), indiceFila, 9);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarNombreDescActionPerformed

    private void jButtonOrdenarPrecioDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPrecioDescActionPerformed
        manhornmic.quicksortDesc();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectrodomesticos.arreglohornosmicroondas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getCapacidad(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getCompartimiento(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getPotencia(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornosmicroondas.get(i).getVoltaje(), indiceFila, 9);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarPrecioDescActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuHornosmicroondasInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuHornosmicroondasInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuHornosmicroondasInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuHornosmicroondasInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuHornosmicroondasInter().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrarTodos;
    private javax.swing.JButton jButtonBorrarUno;
    private javax.swing.JButton jButtonConsultarTodo;
    private javax.swing.JButton jButtonConsultarUno;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonOrdenarID;
    private javax.swing.JButton jButtonOrdenarNombreAsc;
    private javax.swing.JButton jButtonOrdenarNombreDesc;
    private javax.swing.JButton jButtonOrdenarPrecioAsc;
    private javax.swing.JButton jButtonOrdenarPrecioDesc;
    private javax.swing.JComboBox<String> jComboBoxMarca;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCapacidad;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelCompartimiento;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPotencia;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUrl;
    private javax.swing.JLabel jLabelVoltaje;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldCapacidad;
    private javax.swing.JTextField jTextFieldColor;
    private javax.swing.JTextField jTextFieldCompartimiento;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPotencia;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldUrl;
    private javax.swing.JTextField jTextFieldVoltaje;
    // End of variables declaration//GEN-END:variables
}
