/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaGUI;

import controlador.ManejadorHornoselectricosygas;
import controlador.ManejadorObjetos;
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.CategoriaElectrodomesticos;
import modelo.Hornoselectricosygas;
import modelo.Marca;

/**
 *
 * @author Daniel
 */
public class MenuHornoselectricosygasInter extends javax.swing.JFrame {

    /**
     * Creates new form MenuHornoselectricosygasInter
     */
    
    ManejadorObjetos manobj;
    ManejadorHornoselectricosygas manhorneg;
    Integer idMarcaTemporal = null;
    String nombreMarcaTemporal = "";
    DefaultTableModel model;
    int indiceFila = 0;
    String[] dato = new String[11];
    public MenuHornoselectricosygasInter() {
        initComponents();
        manobj = new ManejadorObjetos();
        manhorneg = new ManejadorHornoselectricosygas();
        model = new DefaultTableModel();
        model.addColumn("Id");              
        model.addColumn("Nombre Marca");
        model.addColumn("Nombre");
        model.addColumn("Cantidad");
        model.addColumn("Precio");
        model.addColumn("Color");
        model.addColumn("Potencia Horno");
        model.addColumn("Numero Bandejas");
        model.addColumn("Gratinador");
        model.addColumn("Tipo Control");
        model.addColumn("Temperatura Maxima");
        jTable1.setModel(model);
        model.insertRow(indiceFila, dato);
        inicializarComboBox();
    }

        public void inicializarComboBox(){
        for(int i=0;i<manobj.arregloMarcas.size();i++){
           jComboBoxMarca.addItem(manobj.arregloMarcas.get(i).getDescripcion());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCantidad = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelUrl = new javax.swing.JLabel();
        jLabelColor = new javax.swing.JLabel();
        jTextFieldColor = new javax.swing.JTextField();
        jLabelPotenciaHorno = new javax.swing.JLabel();
        jLabelNumeroBandejas = new javax.swing.JLabel();
        jLabelGratinador = new javax.swing.JLabel();
        jLabelTipoControl = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jComboBoxMarca = new javax.swing.JComboBox<>();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldCantidad = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldUrl = new javax.swing.JTextField();
        jTextFieldPotenciaHorno = new javax.swing.JTextField();
        jTextFieldNumeroBandejas = new javax.swing.JTextField();
        jTextFieldGratinador = new javax.swing.JTextField();
        jTextFieldTipoControl = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelTemperaturaMaxima = new javax.swing.JLabel();
        jTextFieldTemperaturaMaxima = new javax.swing.JTextField();
        jButtonModificar = new javax.swing.JButton();
        jButtonConsultarUno = new javax.swing.JButton();
        jButtonConsultarTodo = new javax.swing.JButton();
        jButtonBorrarUno = new javax.swing.JButton();
        jButtonBorrarTodos = new javax.swing.JButton();
        jButtonInsertar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelMensaje = new javax.swing.JLabel();
        jButtonOrdenarID = new javax.swing.JButton();
        jButtonOrdenarNombreAsc = new javax.swing.JButton();
        jButtonOrdenarPrecioAsc = new javax.swing.JButton();
        jButtonOrdenarNombreDesc = new javax.swing.JButton();
        jButtonOrdenarPrecioDesc = new javax.swing.JButton();

        setTitle("Hornos Electricos y a Gas");

        jLabelCantidad.setText("Cantidad");

        jLabelPrecio.setText("Precio");

        jLabelUrl.setText("Url");

        jLabelColor.setText("Color");

        jLabelPotenciaHorno.setText("Potencia horno");

        jLabelNumeroBandejas.setText("Numero bandejas");

        jLabelGratinador.setText("Gratinador");

        jLabelTipoControl.setText("Tipo control");

        jComboBoxMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMarcaItemStateChanged(evt);
            }
        });
        jComboBoxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMarcaActionPerformed(evt);
            }
        });

        jTextFieldPotenciaHorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPotenciaHornoActionPerformed(evt);
            }
        });

        jLabelTitulo.setText("Hornos electricos y a gas");

        jLabelId.setText("ID");

        jLabelMarca.setText("Marca");

        jLabelNombre.setText("Nombre");

        jLabelTemperaturaMaxima.setText("Temperatura maxima");

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonConsultarUno.setText("Consultar Uno");
        jButtonConsultarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarUnoActionPerformed(evt);
            }
        });

        jButtonConsultarTodo.setText("Consultar Todo");
        jButtonConsultarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarTodoActionPerformed(evt);
            }
        });

        jButtonBorrarUno.setText("Borrar Uno");
        jButtonBorrarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarUnoActionPerformed(evt);
            }
        });

        jButtonBorrarTodos.setText("Borrar Todos");
        jButtonBorrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTodosActionPerformed(evt);
            }
        });

        jButtonInsertar.setText("Insertar");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabelMensaje.setText("Estado");

        jButtonOrdenarID.setText("Ordenar ID");
        jButtonOrdenarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarIDActionPerformed(evt);
            }
        });

        jButtonOrdenarNombreAsc.setText("Ordenar Nombre Ascendente");
        jButtonOrdenarNombreAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNombreAscActionPerformed(evt);
            }
        });

        jButtonOrdenarPrecioAsc.setText("Ordenar Precio Ascendente");
        jButtonOrdenarPrecioAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPrecioAscActionPerformed(evt);
            }
        });

        jButtonOrdenarNombreDesc.setText("Ordenar Nombre Descendente");
        jButtonOrdenarNombreDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNombreDescActionPerformed(evt);
            }
        });

        jButtonOrdenarPrecioDesc.setText("Ordenar Precio Descendente");
        jButtonOrdenarPrecioDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPrecioDescActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelId)
                                    .addComponent(jLabelMarca)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jLabelCantidad)
                                    .addComponent(jLabelPrecio))
                                .addGap(45, 45, 45))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelColor)
                                .addGap(48, 48, 48)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxMarca, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPrecio)
                            .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUrl)
                            .addComponent(jLabelPotenciaHorno)
                            .addComponent(jLabelNumeroBandejas)
                            .addComponent(jLabelGratinador)
                            .addComponent(jLabelTipoControl)
                            .addComponent(jLabelTemperaturaMaxima))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldGratinador, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNumeroBandejas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPotenciaHorno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldUrl, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTipoControl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jTextFieldTemperaturaMaxima, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonConsultarUno)
                    .addComponent(jButtonConsultarTodo)
                    .addComponent(jButtonBorrarUno)
                    .addComponent(jButtonBorrarTodos)
                    .addComponent(jButtonInsertar))
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonOrdenarNombreDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonOrdenarNombreAsc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonOrdenarPrecioDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonOrdenarPrecioAsc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addComponent(jButtonOrdenarID))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabelTitulo)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonInsertar)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonModificar)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonConsultarUno)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonConsultarTodo)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonBorrarUno)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBorrarTodos))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMarca)
                            .addComponent(jComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombre)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCantidad)
                            .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrecio)
                            .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelColor)
                            .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUrl)
                            .addComponent(jTextFieldUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPotenciaHorno)
                            .addComponent(jTextFieldPotenciaHorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNumeroBandejas)
                            .addComponent(jTextFieldNumeroBandejas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGratinador)
                            .addComponent(jTextFieldGratinador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTipoControl)
                            .addComponent(jTextFieldTipoControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTemperaturaMaxima)
                            .addComponent(jTextFieldTemperaturaMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonOrdenarNombreAsc)
                            .addComponent(jButtonOrdenarPrecioAsc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonOrdenarNombreDesc)
                            .addComponent(jButtonOrdenarPrecioDesc)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonOrdenarID)
                        .addGap(16, 16, 16)))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPotenciaHornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPotenciaHornoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPotenciaHornoActionPerformed

    private void jButtonConsultarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarTodoActionPerformed

        manhorneg.consultarTodos();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectrodomesticos.arreglohornoselectricosygas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getPotencia(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getNumbandejas(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getGratinador(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getTipocontrol(), indiceFila, 9);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getTemperaturamax(), indiceFila, 10);
            indiceFila++;
        }
        
    }//GEN-LAST:event_jButtonConsultarTodoActionPerformed

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed

       Hornoselectricosygas horno = new Hornoselectricosygas();
       
       try {
            if (!ValidaEnteros.validaEnteros(jTextFieldId.getText())) {
                throw new ValidaEnteros();
            }
            if (!ValidaCantidad.validaCantidad(jTextFieldCantidad.getText())) {
               throw new ValidaCantidad();
           }
            if (!ValidaFlotantes.validaFlotantes(jTextFieldPrecio.getText())) {
                throw new ValidaFlotantes();
            }
        } catch (ValidaEnteros e) {
            jLabelMensaje.setText("El id que ingreso no es valido");
            jTextFieldId.setText("");
            return;
        } catch (ValidaCantidad e){
            jLabelMensaje.setText("La cantidad que ingreso no es valida");
            jTextFieldCantidad.setText("");
            return;
        }catch (ValidaFlotantes e){
            jLabelMensaje.setText("El precio que ingreso no es valido");
            jTextFieldPrecio.setText("");
            return;
        }
       
       Marca mar = new Marca();
       horno.setIdArticulo(Integer.parseInt(jTextFieldId.getText()));
       mar.setId(idMarcaTemporal);
       mar.setDescripcion(nombreMarcaTemporal);
       horno.setMar(mar);
       horno.setNombre(jTextFieldNombre.getText());
       horno.setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
       horno.setPrecio(Float.parseFloat(jTextFieldPrecio.getText()));
       horno.setColor(jTextFieldColor.getText());
       horno.setPotencia(jTextFieldPotenciaHorno.getText());
       horno.setNumbandejas(Integer.parseInt(jTextFieldNumeroBandejas.getText()));
       horno.setGratinador(jTextFieldGratinador.getText());
       horno.setTipocontrol(jTextFieldTipoControl.getText());
       horno.setTemperaturamax(Integer.parseInt(jTextFieldTemperaturaMaxima.getText()));
       
        if (manhorneg.insertar(horno)) {
            jLabelMensaje.setText("El articulo " + jTextFieldNombre.getText() + " se insertó correctamente");
            //JOptionPane.showMessageDialog(this, "El articulo " + jTextFieldNombre.getText() + " se insertó correctamente");
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(jTextFieldId.getText(), indiceFila, 0);
            jTable1.setValueAt(nombreMarcaTemporal, indiceFila, 1);
            jTable1.setValueAt(jTextFieldNombre.getText(), indiceFila, 2);
            jTable1.setValueAt(jTextFieldCantidad.getText(), indiceFila, 3);
            jTable1.setValueAt(Float.parseFloat(jTextFieldPrecio.getText()), indiceFila, 4);
            jTable1.setValueAt(jTextFieldColor.getText(), indiceFila, 5);
            jTable1.setValueAt(jTextFieldPotenciaHorno.getText(), indiceFila, 6);
            jTable1.setValueAt(Integer.parseInt(jTextFieldNumeroBandejas.getText()), indiceFila, 7);
            jTable1.setValueAt(jTextFieldGratinador.getText(), indiceFila, 8);
            jTable1.setValueAt(jTextFieldTipoControl.getText(), indiceFila, 9);
            jTable1.setValueAt(Integer.parseInt(jTextFieldTemperaturaMaxima.getText()), indiceFila, 10);
            indiceFila++;
            manhorneg.consultarTodos();
        }
        else{
            jLabelMensaje.setText("Error al insertar");
            //JOptionPane.showMessageDialog(this, "Error al insertar");
        }
        
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed

        int filaSeleccionada = jTable1.getSelectedRow();
            System.out.println(filaSeleccionada);
        
            if (filaSeleccionada >= 0) {
            
            Hornoselectricosygas hornomod = new Hornoselectricosygas();
            int a = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            jTextFieldId.setText(jTable1.getValueAt(filaSeleccionada, 0).toString());
            String nombreMarcaMod = jTable1.getValueAt(filaSeleccionada, 1).toString();
            jTextFieldNombre.setText(jTable1.getValueAt(filaSeleccionada, 2).toString());
            jTextFieldCantidad.setText(jTable1.getValueAt(filaSeleccionada, 3).toString());
            jTextFieldPrecio.setText(jTable1.getValueAt(filaSeleccionada, 4).toString());
            jTextFieldColor.setText(jTable1.getValueAt(filaSeleccionada, 5).toString());
            jTextFieldPotenciaHorno.setText(jTable1.getValueAt(filaSeleccionada, 6).toString());
            jTextFieldNumeroBandejas.setText(jTable1.getValueAt(filaSeleccionada, 7).toString());
            jTextFieldGratinador.setText(jTable1.getValueAt(filaSeleccionada, 8).toString());
            jTextFieldTipoControl.setText(jTable1.getValueAt(filaSeleccionada, 9).toString());
            jTextFieldTemperaturaMaxima.setText(jTable1.getValueAt(filaSeleccionada, 10).toString());
            
            Marca marmod = new Marca();
            hornomod.setIdArticulo(Integer.parseInt(jTextFieldId.getText()));
            marmod.setId(a);
            marmod.setDescripcion(nombreMarcaMod);
            hornomod.setMar(marmod);
            hornomod.setNombre(jTextFieldNombre.getText());
            hornomod.setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
            hornomod.setPrecio(Float.parseFloat(jTextFieldPrecio.getText()));
            hornomod.setColor(jTextFieldColor.getText());
            hornomod.setPotencia(jTextFieldPotenciaHorno.getText());
            hornomod.setNumbandejas(Integer.parseInt(jTextFieldNumeroBandejas.getText()));
            hornomod.setGratinador(jTextFieldGratinador.getText());
            hornomod.setTipocontrol(jTextFieldTipoControl.getText());
            hornomod.setTemperaturamax(Integer.parseInt(jTextFieldTemperaturaMaxima.getText()));
            
            //Marca marmod = new Marca(Integer.parseInt(jTextFieldId.getText()), jTextFieldMarca.getText());
            int posicion = manhorneg.busquedaBinaria(a);
                    if (!(posicion==-1)) {
                    if (manhorneg.modificar(posicion, hornomod)) {
                        JOptionPane.showMessageDialog(this, "Horno modificado exitosamente");
                        indiceFila--;
                    }
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Error al modificar");
                    }
        }
        
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonConsultarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarUnoActionPerformed

        int idBuscado = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el ID a buscar"));
            
        Hornoselectricosygas resultado = (Hornoselectricosygas) manhorneg.consultarId(idBuscado);
        if (resultado == null) {
            JOptionPane.showMessageDialog(this, "Horno no encontrado");
        }
        else{
            JOptionPane.showMessageDialog(this, "El Horno encontrado es:\n" + resultado.toString());
        }
        
    }//GEN-LAST:event_jButtonConsultarUnoActionPerformed

    private void jButtonBorrarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarUnoActionPerformed

        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada >= 0) {
            int idEliminar = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            model.removeRow(filaSeleccionada);
            if (manhorneg.borrar(idEliminar)) {
                    JOptionPane.showMessageDialog(this, "Horno borrado exitosamente");    
                    }
            else {
            JOptionPane.showMessageDialog(this, "Error al borrar");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar");
        }
        
    }//GEN-LAST:event_jButtonBorrarUnoActionPerformed

    private void jButtonBorrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTodosActionPerformed

        if (manhorneg.borrarTodo()) {
            while (model.getRowCount() > 0) {
                model.removeRow(0);
            }
            indiceFila = 0;
            JOptionPane.showMessageDialog(this, "Todos los hornos se borraron exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar todo");
        }
        
    }//GEN-LAST:event_jButtonBorrarTodosActionPerformed

    private void jComboBoxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMarcaActionPerformed

    private void jComboBoxMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMarcaItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (jComboBoxMarca.getItemCount() > 0) {
                idMarcaTemporal = ManejadorObjetos.arregloMarcas.get(jComboBoxMarca.getSelectedIndex()).getId();
                nombreMarcaTemporal = ManejadorObjetos.arregloMarcas.get(jComboBoxMarca.getSelectedIndex()).getDescripcion();
            }
        }
        
    }//GEN-LAST:event_jComboBoxMarcaItemStateChanged

    private void jButtonOrdenarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarIDActionPerformed
        manhorneg.sort();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectrodomesticos.arreglohornoselectricosygas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getPotencia(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getNumbandejas(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getGratinador(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getTipocontrol(), indiceFila, 9);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getTemperaturamax(), indiceFila, 10);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarIDActionPerformed

    private void jButtonOrdenarNombreAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNombreAscActionPerformed
        manhorneg.ordenarMezcla();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectrodomesticos.arreglohornoselectricosygas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getPotencia(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getNumbandejas(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getGratinador(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getTipocontrol(), indiceFila, 9);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getTemperaturamax(), indiceFila, 10);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarNombreAscActionPerformed

    private void jButtonOrdenarPrecioAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPrecioAscActionPerformed
        manhorneg.quicksort();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectrodomesticos.arreglohornoselectricosygas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getPotencia(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getNumbandejas(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getGratinador(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getTipocontrol(), indiceFila, 9);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getTemperaturamax(), indiceFila, 10);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarPrecioAscActionPerformed

    private void jButtonOrdenarNombreDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNombreDescActionPerformed
        manhorneg.ordenarMezclaDesc();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectrodomesticos.arreglohornoselectricosygas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getPotencia(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getNumbandejas(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getGratinador(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getTipocontrol(), indiceFila, 9);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getTemperaturamax(), indiceFila, 10);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarNombreDescActionPerformed

    private void jButtonOrdenarPrecioDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPrecioDescActionPerformed
        manhorneg.quicksortDesc();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        indiceFila = 0;

        for (int i = 0; i < CategoriaElectrodomesticos.arreglohornoselectricosygas.size(); i++) {
            model.insertRow(indiceFila, dato);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getIdArticulo(), indiceFila, 0);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getMar().getDescripcion(), indiceFila, 1);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getNombre(), indiceFila, 2);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getCantidad(), indiceFila, 3);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getPrecio(), indiceFila, 4);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getColor(), indiceFila, 5);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getPotencia(), indiceFila, 6);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getNumbandejas(), indiceFila, 7);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getGratinador(), indiceFila, 8);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getTipocontrol(), indiceFila, 9);
            jTable1.setValueAt(CategoriaElectrodomesticos.arreglohornoselectricosygas.get(i).getTemperaturamax(), indiceFila, 10);
            indiceFila++;
        }
    }//GEN-LAST:event_jButtonOrdenarPrecioDescActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuHornoselectricosygasInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuHornoselectricosygasInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuHornoselectricosygasInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuHornoselectricosygasInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuHornoselectricosygasInter().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrarTodos;
    private javax.swing.JButton jButtonBorrarUno;
    private javax.swing.JButton jButtonConsultarTodo;
    private javax.swing.JButton jButtonConsultarUno;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonOrdenarID;
    private javax.swing.JButton jButtonOrdenarNombreAsc;
    private javax.swing.JButton jButtonOrdenarNombreDesc;
    private javax.swing.JButton jButtonOrdenarPrecioAsc;
    private javax.swing.JButton jButtonOrdenarPrecioDesc;
    private javax.swing.JComboBox<String> jComboBoxMarca;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelGratinador;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumeroBandejas;
    private javax.swing.JLabel jLabelPotenciaHorno;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTemperaturaMaxima;
    private javax.swing.JLabel jLabelTipoControl;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUrl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldColor;
    private javax.swing.JTextField jTextFieldGratinador;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumeroBandejas;
    private javax.swing.JTextField jTextFieldPotenciaHorno;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldTemperaturaMaxima;
    private javax.swing.JTextField jTextFieldTipoControl;
    private javax.swing.JTextField jTextFieldUrl;
    // End of variables declaration//GEN-END:variables
}
